import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createAppSandboxClient,createAppApiClient} from '@metro/platform-sdk/app-sandbox';
import {platformUiCss} from '@metro/platform-sdk/ui-styles';
import {createSandboxImageClient} from '@metro/platform-sdk/app-files';
import {Button,DropdownSelect,DatePicker,TimePicker,Field,Dialog,FilterBar,DataList,TableHeader,TableBody,TableRow,TableHead,TableCell,ListPagination,TableActions,TableActionButton,SearchSelect,Card,CardHeader,CardTitle,CardContent} from '@metro/platform-sdk/ui';
import {pageForRoute,visiblePages} from './workspace.mjs';

const script=document.currentScript,origin=script?.dataset.platformOrigin;
if(!origin)throw Error('PLATFORM_ORIGIN_REQUIRED');
document.documentElement.classList.add('afc-theme-neutral');
const style=document.createElement('style');style.nonce=script?.nonce??'';
style.textContent=platformUiCss+`
.hazards{padding:24px;max-width:1480px;margin:auto}.hazards h1{font-size:22px;margin:0}
.hazards-sub,.hazards-note{color:var(--afc-color-muted);font-size:13px}.hazards-sub{margin:4px 0 24px}
.hazards-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.hazards-toolbar{margin-bottom:18px}
.hazards-report{display:grid;grid-template-columns:minmax(280px,1fr) minmax(0,2fr);gap:24px;align-items:start;margin-top:24px}
.hazards-report>*{min-width:0}.hazards-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;border:0;padding:0;margin:0;min-width:0}
.hazards-wide{grid-column:1/-1}.hazards-form textarea,.hazards-ai textarea{width:100%;box-sizing:border-box;resize:vertical;min-height:88px;padding:10px;border:1px solid var(--afc-color-line,#ddd);border-radius:8px;background:var(--afc-color-paper,#fff);color:inherit}
.hazards-ai{display:grid;gap:16px}.hazards-ai textarea{min-height:160px}.hazards-ai>.afc-button{justify-self:center;width:calc(100% - 24px);max-width:360px}
.hazards-time{display:grid;grid-template-columns:minmax(0,1fr) 120px;gap:8px}
.hazards-warning{background:var(--afc-color-canvas);border:1px solid var(--afc-color-line);padding:12px;border-radius:8px;margin:10px 0}
.hazards-error{color:var(--afc-color-danger,#b91c1c);padding:10px 0;margin:0 0 12px}.hazards-success{color:var(--afc-color-ink);background:var(--afc-color-canvas);border:1px solid var(--afc-color-line);padding:12px;border-radius:8px;margin:10px 0}
.hazards-suggestion{display:grid;gap:12px}.hazards-suggestion dl{display:grid;gap:8px}.hazards-suggestion dt{font-size:12px;color:var(--afc-color-muted)}.hazards-suggestion dd{margin:0;overflow-wrap:anywhere}
.hazards-cell{max-width:340px;white-space:normal;overflow-wrap:anywhere}.hazards-cell small{display:block;color:var(--afc-color-muted)}
.hazards-photo{max-width:100%;max-height:300px;object-fit:contain;border:1px solid var(--afc-color-line,#ddd);border-radius:8px}
.hazards-mobile{display:none}.hazards-card{border:1px solid var(--afc-color-line,#ddd);background:var(--afc-color-paper,#fff);border-radius:10px;padding:12px;margin-bottom:8px}.hazards-card p{margin:5px 0}
.hazards-footer{justify-content:flex-end;margin-top:20px}.hazards-report .hazards-footer{border-top:1px solid var(--afc-color-line);padding-top:20px}
@media(max-width:800px){.hazards-report{grid-template-columns:1fr}.hazards-ai textarea{min-height:120px}}
@media(max-width:700px){.hazards{padding:12px}.hazards-form{grid-template-columns:minmax(0,1fr)}.hazards-wide{grid-column:1}.hazards-desktop{display:none}.hazards-mobile{display:block}.hazards-time{grid-template-columns:minmax(0,1fr)}.hazards-time>*{min-width:0}.hazards-report{gap:16px}}
`;
document.head.append(style);
const sandbox=createAppSandboxClient({appId:'hazards',platformOrigin:origin,port:{parent:window.parent,send:(data,target)=>window.parent.postMessage(data,target),listen:listener=>{window.addEventListener('message',listener);return()=>window.removeEventListener('message',listener);}}});
const api=createAppApiClient(sandbox);
const categories=['设备运行维修','设施监测养护','行车组织','客运组织','运营环境','人员管理','施工管理','仓储管理'],levels=['一般隐患II级','一般隐患I级','重大隐患'];
const messages={INVALID_INPUT:'请检查填写内容',INVALID_STATION:'车站不在所选线路和工班责任范围内，请重新选择',INVALID_PERSON:'请选择所选工班的在岗责任人',ACCESS_DENIED:'没有此操作权限',CLOSURE_EVIDENCE_REQUIRED:'提交复审前请填写治理措施、治理时限、治理情况并上传整改后照片',SELF_REVIEW_DENIED:'提报人不能复审自己的隐患',NOT_READY_TO_CLOSE:'隐患尚未达到关闭条件或已被更新',CONFLICT:'记录已被其他人修改，请重新打开',AI_UNAVAILABLE:'模型当前不可用，可直接填写右侧表单后提报',AI_INVALID_RESULT:'模型返回结果不符合字段要求，可直接手工填写',INVALID_PHOTO:'照片状态已变化，请重新上传',PHOTO_CORRUPT:'照片校验失败，请重新上传',PHOTO_INCOMPLETE:'照片上传不完整，请重新上传',INVALID_IMAGE:'无法处理这张图片，请选择有效的 JPG、PNG 或 WebP',IMAGE_TOO_LARGE:'照片压缩后仍超过 220 KB，请选择较小的照片',FILE_TOO_LARGE:'原始图片不能超过 8 MB',UNSUPPORTED_FILE:'请选择 JPG、PNG 或 WebP 图片'};
let writing=false,uncertain=false;
const dateTime=value=>{if(!value)return '';const date=new Date(value);if(Number.isNaN(date.getTime()))return '';return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(date).replace(' ','T');};
const iso=value=>value?new Date(value+':00+08:00').toISOString():null,complete=value=>/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value)&&!Number.isNaN(Date.parse(value+':00+08:00')),fmt=value=>value?dateTime(value).replace('T',' '):'—';
const blank=org=>({organizationId:org,inspectedAt:dateTime(new Date().toISOString()),stationId:null,location:'',line:'',description:'',category:categories[0],level:levels[0],temporaryControls:'',governanceMeasures:'',governanceDeadline:'',governanceDetails:'',responsiblePerson:'',responsiblePersonId:null,beforePhotoId:null,afterPhotoId:null,status:'open',aiConfidence:null,aiBasis:''});
const fromRow=row=>({organizationId:row.organization_id,inspectedAt:dateTime(row.inspected_at),stationId:row.station_id??null,location:row.location,line:row.line,description:row.description,category:row.category,level:row.level,temporaryControls:row.temporary_controls??'',governanceMeasures:row.governance_measures??'',governanceDeadline:dateTime(row.governance_deadline),governanceDetails:row.governance_details??'',responsiblePerson:row.responsible_person,responsiblePersonId:row.responsible_person_id??null,beforePhotoId:row.before_photo_id??null,afterPhotoId:row.after_photo_id??null,status:row.status==='closed'?'pending_review':row.status,aiConfidence:row.ai_confidence??null,aiBasis:row.ai_basis??''});
const statusLabel=value=>({open:'整改中',pending_review:'待复审',closed:'已关闭'})[value]??value;

function App(){
 const [route,setRoute]=useState(decodeURIComponent(script?.dataset.appRoute??'/'));
 const [session,setSession]=useState(null),[rows,setRows]=useState([]),[next,setNext]=useState(null),[cursors,setCursors]=useState([null]),[filters,setFilters]=useState({organizationId:'',status:'all',search:''});
 const [busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[analyzing,setAnalyzing]=useState(false),[error,setError]=useState(''),[aiError,setAiError]=useState(''),[notice,setNotice]=useState(''),[dialog,setDialog]=useState(null);
 const [draft,setDraft]=useState(blank('')),[draftKey,setDraftKey]=useState(0),[editing,setEditing]=useState(blank('')),[rawText,setRawText]=useState(''),[suggestion,setSuggestion]=useState(null);
 const [availableLines,setAvailableLines]=useState([]),[stations,setStations]=useState([]),[stationSearch,setStationSearch]=useState(''),[people,setPeople]=useState([]),[personSearch,setPersonSearch]=useState('');
 const [draftPhoto,setDraftPhoto]=useState(null),[editPhoto,setEditPhoto]=useState(null),[afterFile,setAfterFile]=useState(null),[photoUrl,setPhotoUrl]=useState(null),[photoKind,setPhotoKind]=useState('');
 const token=useRef(0),catalogToken=useRef(0),cursor=cursors.at(-1),organizations=session?.organizations??[],can=name=>session?.permissions.includes('app.hazards.'+name);
 const page=pageForRoute(route,session),view=page?.id,form=dialog?editing:draft,setForm=dialog?setEditing:setDraft,beforeFile=dialog?editPhoto:draftPhoto;
 const readonly=dialog?.kind==='view',hasRecord=!!dialog?.row,fieldsActive=view==='report'||['edit','view'].includes(dialog?.kind);
 useEffect(()=>sandbox.onRouteChange(path=>{setRoute(path);token.current++;setRows([]);setCursors([null]);setNext(null);setDialog(null);setError('');setNotice('');setFilters({organizationId:'',status:'all',search:''});}),[]);
 useEffect(()=>{let alive=true;const deadline=Date.now()+10000,timer=setInterval(async()=>{if(!sandbox.ready()){if(Date.now()>deadline){clearInterval(timer);if(alive)setError('应用连接未就绪，请重新打开');}return;}clearInterval(timer);try{const result=await call('session',{});if(alive){setSession(result);setDraft(blank(result.organizationId));await sandbox.invoke('platform.ui.navigation',{ids:visiblePages(result).map(item=>item.id)});}}catch(e){if(alive)setError(e.message);}},25);return()=>{alive=false;clearInterval(timer);};},[]);
 useEffect(()=>{if(!session)return;void sandbox.invoke('platform.ui.theme',{}).then(value=>{if(['light','dark'].includes(value.theme))document.documentElement.dataset.theme=value.theme;}).catch(()=>{});},[session]);
 useEffect(()=>{if(!session)return;void sandbox.invoke('platform.ui.modal',{open:!!dialog}).catch(()=>{});},[session,!!dialog]);
 useEffect(()=>{if(!fieldsActive||!form.organizationId)return;const current=++catalogToken.current,timer=setTimeout(async()=>{try{const result=await call('catalog',{organizationId:form.organizationId,...(form.line?{lineName:form.line}:{}),...(stationSearch?{stationSearch}:{}),...(personSearch?{personSearch}:{})});if(current===catalogToken.current){setAvailableLines(result.lines);setStations(result.stations);setPeople(result.people);}}catch(e){if(current===catalogToken.current)setError(e.message);}},250);return()=>{clearTimeout(timer);catalogToken.current++;};},[fieldsActive,dialog?.kind,form.organizationId,form.line,stationSearch,personSearch]);
 useEffect(()=>()=>{if(photoUrl)URL.revokeObjectURL(photoUrl);},[photoUrl]);
 async function call(name,payload,write=false){
  if(write&&(writing||uncertain))throw Error('写入结果待核对，请先联系管理员');if(write)writing=true;
  try{const result=await api.invoke(name,payload);if(!result.ok){if(write&&result.error?.writeOutcome==='unknown')uncertain=true;const ex=Error(messages[result.error?.code]??(write?'结果未确认，请联系管理员核对':'读取失败，请重试'));ex.definitive=result.error?.writeOutcome==='not_started';throw ex;}return result.result;}
  catch(e){if(write&&!e.definitive)uncertain=true;throw e;}finally{if(write)writing=false;}
 }
 const imageClient=()=>createSandboxImageClient((name,payload,write)=>call(name,payload,write),{begin:'photo-begin',part:'photo-part',finish:'photo-finish',read:'photo-read'});
 async function load(){if(!session||!['records','cases'].includes(view))return;const id=++token.current;setBusy(true);setError('');try{const result=await call(view==='cases'?'cases':'list',{pageSize:20,...(filters.organizationId?{organizationId:filters.organizationId}:{}),...(view==='records'?{status:filters.status}:{}),...(filters.search?{search:filters.search}:{}),...(cursor?{after:cursor}:{})});if(id===token.current){setRows(result.rows);setNext(result.nextCursor??null);}}catch(e){if(id===token.current)setError(e.message);}finally{if(id===token.current)setBusy(false);}}
 useEffect(()=>{const timer=setTimeout(()=>void load(),filters.search?250:0);return()=>{clearTimeout(timer);token.current++;};},[session,view,filters,cursor]);
 function setFilter(name,value){setCursors([null]);setFilters(current=>({...current,[name]:value}));}
 const activeFilters=useMemo(()=>({selectedOptions:{organization:filters.organizationId?[filters.organizationId]:[],...(view==='records'?{status:filters.status==='all'?[]:[filters.status]}:{})}}),[filters,view]);
 const filterGroups=[...(view==='records'?[{id:'status',title:'隐患状态',options:[{id:'open',label:'整改中'},{id:'pending_review',label:'待复审'},{id:'closed',label:'已关闭'}],isMulti:false,allowAll:true}]:[]),{id:'organization',title:'工班',options:organizations.map(org=>({id:org.id,label:org.name})),isMulti:false,allowAll:true}];
 function open(kind,row){setError('');setNotice('');setDialog({kind,row});setEditing(kind==='case'?blank(''):fromRow(row));setAvailableLines([]);setStations([]);setStationSearch('');setPeople([]);setPersonSearch('');setEditPhoto(null);setAfterFile(null);setPhotoUrl(null);}
 function close(){if(!saving){setDialog(null);setPhotoUrl(null);}}
 function change(name,value){setError('');setForm(current=>({...current,[name]:value,...(name==='location'?{stationId:null}:{}),...(name==='responsiblePerson'?{responsiblePersonId:null}:{})}));}
 function changeOrganization(value){setForm(current=>({...current,organizationId:value,line:'',stationId:null,location:'',responsiblePerson:'',responsiblePersonId:null}));setSuggestion(null);setStations([]);setPeople([]);setStationSearch('');setPersonSearch('');setError('');setAiError('');}
 function datePart(name,part,value){setForm(current=>{const [date='',time='']=(current[name]??'').split('T');return {...current,[name]:value?(part==='date'?value:date)+'T'+(part==='time'?value:time):''};});}
 const dateField=(name,label,required=false)=>{const [date='',time='']=(form[name]??'').split('T');return <Field label={label} required={required}><div className="hazards-time"><DatePicker value={date} onChange={value=>datePart(name,'date',value)} disabled={readonly||saving} clearable={!required}/><TimePicker value={time} onChange={value=>datePart(name,'time',value)} minuteStep={1} disabled={readonly||saving} clearable={!required}/></div></Field>;};
 async function suggest(){if(rawText.trim().length<4){setAiError('请先输入至少四个字的现场描述');return;}setAnalyzing(true);setAiError('');setSuggestion(null);try{setSuggestion(await call('suggest',{organizationId:draft.organizationId,rawText}));}catch(e){setAiError(e.message);}finally{setAnalyzing(false);}}
 function applySuggestion(){if(!suggestion||saving)return;setDraft(current=>({...current,description:suggestion.description,category:suggestion.category,level:suggestion.level,governanceMeasures:suggestion.measures,aiConfidence:suggestion.confidence,aiBasis:suggestion.basis}));setError('');setNotice('建议已填入表单，请核对后提报。');}
 async function save(){
  const creating=!dialog;if(saving||uncertain||(!creating&&dialog.kind!=='edit')||(creating&&view!=='report'))return;
  if(!form.line||!form.stationId||!form.location.trim()||!form.description.trim()||!form.responsiblePersonId||!complete(form.inspectedAt)){setError('请先选择线路和本工班车站、从人员列表选择责任人，并填写描述及排查时间');return;}
  if(form.status==='pending_review'&&(!form.governanceMeasures.trim()||!form.governanceDetails.trim()||!complete(form.governanceDeadline)||!afterFile&&!form.afterPhotoId)){setError(messages.CLOSURE_EVIDENCE_REQUIRED);return;}
  const requestId=crypto.randomUUID();setSaving(true);setError('');
  try{const images=imageClient(),beforePhotoId=beforeFile?await images.upload(beforeFile,{organizationId:form.organizationId,kind:'before'}):form.beforePhotoId,afterPhotoId=!creating&&afterFile?await images.upload(afterFile,{organizationId:form.organizationId,kind:'after'}):form.afterPhotoId,record={...form,inspectedAt:iso(form.inspectedAt),governanceDeadline:iso(form.governanceDeadline),beforePhotoId,afterPhotoId};
   await call(creating?'create':'update',{requestId,id:creating?crypto.randomUUID():dialog.row.id,...(!creating?{revision:dialog.row.revision}:{}),record},true);
   if(creating){setDraft(blank(form.organizationId));setDraftKey(value=>value+1);setDraftPhoto(null);setRawText('');setSuggestion(null);setStationSearch('');setPersonSearch('');setNotice('提报成功，隐患已进入整改流程。');}else{setDialog(null);setNotice('隐患已保存');setCursors([null]);await load();}
  }catch(e){setError((messages[e.message]??e.message)+(uncertain?'（请求编号：'+requestId+'）':''));}finally{setSaving(false);}
 }
 async function review(){if(!dialog?.row||saving||uncertain)return;const requestId=crypto.randomUUID();setSaving(true);setError('');try{await call('close',{requestId,id:dialog.row.id,revision:dialog.row.revision},true);setDialog(null);setNotice('复审通过，隐患已关闭并写入案例库');setCursors([null]);await load();}catch(e){setError(e.message+(uncertain?'（请求编号：'+requestId+'）':''));}finally{setSaving(false);}}
 async function showPhoto(kind){const id=kind==='before'?dialog?.row?.before_photo_id:dialog?.row?.after_photo_id;if(!id)return;setError('');try{const blob=await imageClient().read({recordId:dialog.row.id,photoId:id});setPhotoUrl(URL.createObjectURL(blob));setPhotoKind(kind);}catch(e){setError(messages[e.message]??e.message);}}
 const recordFields=<fieldset className="hazards-form" disabled={readonly||saving}>
  {organizations.length>1&&<Field label="所属工班"><DropdownSelect value={form.organizationId} options={organizations.map(org=>({value:org.id,label:org.name}))} disabled={hasRecord||saving||analyzing} onChange={changeOrganization}/></Field>}{dateField('inspectedAt','排查时间',true)}
  <Field label="线路" required><DropdownSelect value={form.line} options={[{value:'',label:'请选择线路'},...availableLines.map(item=>({value:item.name,label:item.name}))]} disabled={readonly||saving} onChange={value=>{setForm(current=>({...current,line:value,stationId:null,location:''}));setStations([]);setStationSearch('');}}/></Field>
  <Field label="车站" htmlFor="hazard-station" required><SearchSelect id="hazard-station" value={form.location} options={stations.map(item=>({id:item.id,label:item.name}))} allowCustom={false} emptyText="暂无本线路本工班负责的车站，请先配置管辖范围" placeholder={form.line?'搜索本工班负责的车站':'请先选择线路'} disabled={readonly||saving||!form.line} onSearch={setStationSearch} onInput={value=>change('location',value)} onSelect={item=>setForm(current=>({...current,stationId:item.id,location:item.label}))}/></Field>
  <Field className="hazards-wide" label="隐患描述" htmlFor="hazard-description" required><textarea id="hazard-description" value={form.description} maxLength={2000} disabled={readonly||saving} onChange={event=>change('description',event.target.value)} placeholder="描述具体位置、异常现象和可能造成的影响"/></Field>
  <Field label="隐患分类"><DropdownSelect value={form.category} options={categories.map(item=>({value:item,label:item}))} disabled={readonly||saving} onChange={value=>change('category',value)}/></Field>
  <Field label="隐患等级"><DropdownSelect value={form.level} options={levels.map(item=>({value:item,label:item}))} disabled={readonly||saving} onChange={value=>change('level',value)}/></Field>
  <Field className="hazards-wide" label="临时管控措施" htmlFor="hazard-controls"><textarea id="hazard-controls" value={form.temporaryControls} maxLength={1000} disabled={readonly||saving} onChange={event=>change('temporaryControls',event.target.value)}/></Field>
  <Field className="hazards-wide" label="治理措施" htmlFor="hazard-measures"><textarea id="hazard-measures" value={form.governanceMeasures} maxLength={2000} disabled={readonly||saving} onChange={event=>change('governanceMeasures',event.target.value)}/></Field>
  <Field label="治理责任人" htmlFor="hazard-person" required><SearchSelect id="hazard-person" value={form.responsiblePerson} options={people.map(item=>({id:item.id,label:item.name,detail:item.employeeNo}))} allowCustom={false} emptyText="暂无匹配的本工班在岗人员" placeholder="搜索或选择本工班人员" disabled={readonly||saving} onSearch={setPersonSearch} onInput={value=>change('responsiblePerson',value)} onSelect={item=>setForm(current=>({...current,responsiblePersonId:item.id,responsiblePerson:item.label}))}/></Field>{dateField('governanceDeadline','治理时限',form.status==='pending_review')}
  {hasRecord&&<Field className="hazards-wide" label="具体治理情况" htmlFor="hazard-remedy"><textarea id="hazard-remedy" value={form.governanceDetails} maxLength={2000} disabled={readonly||saving} onChange={event=>change('governanceDetails',event.target.value)}/></Field>}
  <Field label="提报前照片">{!readonly&&can('photo')&&<input type="file" accept="image/jpeg,image/png,image/webp" disabled={saving} aria-label="提报前照片" onChange={event=>(dialog?setEditPhoto:setDraftPhoto)(event.target.files?.[0]??null)}/>}<span className="hazards-note">{beforeFile?.name??(form.beforePhotoId?'已上传':can('photo')?'可选；用于现场留证':'需照片上传权限')}</span>{hasRecord&&form.beforePhotoId&&<Button size="xs" variant="secondary" onClick={()=>void showPhoto('before')}>查看照片</Button>}</Field>
  {hasRecord&&<Field label="整改后照片">{!readonly&&can('photo')&&<input type="file" accept="image/jpeg,image/png,image/webp" disabled={saving} aria-label="整改后照片" onChange={event=>setAfterFile(event.target.files?.[0]??null)}/>}<span className="hazards-note">{afterFile?.name??(form.afterPhotoId?'已上传':can('photo')?'提交复审前必填':'需照片上传权限')}</span>{form.afterPhotoId&&<Button size="xs" variant="secondary" onClick={()=>void showPhoto('after')}>查看照片</Button>}</Field>}
  {!readonly&&dialog?.kind==='edit'&&<Field className="hazards-wide" label="治理状态"><DropdownSelect value={form.status} options={[{value:'open',label:'整改中'},{value:'pending_review',label:'提交安全复审'}]} disabled={saving} onChange={value=>change('status',value)}/></Field>}
  {readonly&&dialog?.row?.status==='closed'&&<p className="hazards-wide hazards-success">已复审关闭，信息锁定。</p>}{photoUrl&&<div className="hazards-wide"><p className="hazards-note">{photoKind==='before'?'提报前':'整改后'}照片</p><img className="hazards-photo" src={photoUrl} alt={photoKind==='before'?'提报前现场照片':'整改后现场照片'}/></div>}
 </fieldset>;
 return <main className="hazards"><h1>{page?.label??'隐患提报 · 识隐'}</h1>{view!=='report'&&<p className="hazards-sub">{view==='cases'?'查阅有权访问的闭环案例和治理经验。':'查看隐患记录，跟进治理和安全复审。'}</p>}
  {error&&!dialog&&<p role="alert" className="hazards-error">{error}</p>}{notice&&!dialog&&<p role="status" className="hazards-success">{notice}</p>}
  {!session&&!error&&<p role="status" className="hazards-note">正在读取应用权限…</p>}{session&&!page&&<p role="alert" className="hazards-error">没有此页面的访问权限，请从侧栏选择已授权功能。</p>}
  {view==='report'&&<div className="hazards-report">
   <Card><CardHeader><CardTitle>AI 识别</CardTitle></CardHeader><CardContent><div className="hazards-ai">
    <Field label="现场描述" htmlFor="hazard-raw"><textarea id="hazard-raw" value={rawText} maxLength={2000} disabled={analyzing||saving} onChange={event=>{setRawText(event.target.value);setSuggestion(null);setAiError('');}}/></Field>
    <Button variant="secondary" disabled={analyzing||saving||uncertain||rawText.trim().length<4} onClick={suggest}>{analyzing?'识别中…':'识别隐患'}</Button>
    {aiError&&<p role="alert" className="hazards-error">{aiError}</p>}
    {suggestion&&<section className="hazards-suggestion" aria-label="AI 识别建议"><p className="hazards-note">参考 {suggestion.referenceCount} 条闭环案例 · 置信度 {Math.round(suggestion.confidence*100)}%</p><dl><div><dt>隐患描述</dt><dd>{suggestion.description}</dd></div><div><dt>分类 / 等级</dt><dd>{suggestion.category} · {suggestion.level}</dd></div><div><dt>治理措施</dt><dd>{suggestion.measures}</dd></div></dl>{suggestion.manualReview&&<p className="hazards-warning">该建议需要重点人工复核。</p>}<p className="hazards-note">{suggestion.basis}</p><Button onClick={applySuggestion} disabled={saving}>采用建议填入表单</Button></section>}
   </div></CardContent></Card>
   <Card><CardHeader><CardTitle>隐患信息</CardTitle></CardHeader><CardContent><div key={draftKey}>{recordFields}<div className="hazards-actions hazards-footer"><Button onClick={()=>void save()} disabled={saving||analyzing||uncertain}>{saving?'提报中…':'提报隐患'}</Button></div></div></CardContent></Card>
  </div>}
  {['records','cases'].includes(view)&&<>
   <FilterBar className="hazards-toolbar" searchValue={filters.search} onSearchChange={value=>setFilter('search',value)} searchPlaceholder={view==='records'?'搜索隐患、地点或分类':'搜索案例描述、分类或措施'} filterGroups={filterGroups} activeFilters={activeFilters} onApplyFilters={value=>{setCursors([null]);setFilters(current=>({...current,organizationId:value.selectedOptions?.organization?.[0]||'',status:value.selectedOptions?.status?.[0]||'all'}));}} onResetFilters={()=>{setCursors([null]);setFilters({organizationId:'',status:'all',search:''});}}/>
   <div className="hazards-desktop"><DataList emptyState={busy?'加载中…':rows.length?'':view==='cases'?'暂无闭环案例':'暂无隐患记录'} pagination={<ListPagination page={cursors.length} hasNext={!!next} busy={busy} onPrevious={()=>setCursors(value=>value.slice(0,-1))} onNext={()=>setCursors(value=>[...value,next])}/>}><TableHeader><TableRow>{(view==='records'?['隐患描述','地点','排查时间','分类 / 等级','状态','操作']:['案例描述','分类 / 等级','质量评分','检索状态','操作']).map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(row=>view==='records'?<TableRow key={row.id}><TableCell className="hazards-cell">{row.description}<small>{row.responsible_person}</small></TableCell><TableCell>{row.location}</TableCell><TableCell>{fmt(row.inspected_at)}</TableCell><TableCell>{row.category}<small>{row.level}</small></TableCell><TableCell>{statusLabel(row.status)}</TableCell><TableCell><TableActions><TableActionButton onClick={()=>open('view',row)}>查看</TableActionButton>{row.status!=='closed'&&can('update')&&<TableActionButton onClick={()=>open('edit',row)}>治理</TableActionButton>}{row.status==='pending_review'&&can('review')&&row.created_by!==session?.personId&&<TableActionButton onClick={()=>open('review',row)}>复审</TableActionButton>}</TableActions></TableCell></TableRow>:<TableRow key={row.id}><TableCell className="hazards-cell">{row.description}<small>{row.governance_measures}</small></TableCell><TableCell>{row.category}<small>{row.level}</small></TableCell><TableCell>{row.quality_score}</TableCell><TableCell>{row.retrieval_enabled?'参与建议':'待补充'}</TableCell><TableCell><TableActions><TableActionButton onClick={()=>open('case',row)}>查看</TableActionButton></TableActions></TableCell></TableRow>)}</TableBody></DataList></div>
   <div className="hazards-mobile">{rows.map(row=><article className="hazards-card" key={row.id}><b>{row.description}</b><p>{row.category} · {row.level}</p><p>{view==='records'?row.location+' · '+statusLabel(row.status):'质量 '+row.quality_score+' · '+(row.retrieval_enabled?'参与建议':'待补充')}</p><div className="hazards-actions"><Button size="xs" variant="secondary" onClick={()=>open(view==='records'?'view':'case',row)}>查看</Button>{view==='records'&&row.status!=='closed'&&can('update')&&<Button size="xs" variant="secondary" onClick={()=>open('edit',row)}>治理</Button>}{view==='records'&&row.status==='pending_review'&&can('review')&&row.created_by!==session?.personId&&<Button size="xs" onClick={()=>open('review',row)}>复审</Button>}</div></article>)}{!rows.length&&<p className="hazards-note">{busy?'加载中…':'暂无记录'}</p>}<div className="hazards-actions"><Button size="xs" variant="secondary" disabled={busy||cursors.length===1} onClick={()=>setCursors(value=>value.slice(0,-1))}>上一页</Button><Button size="xs" variant="secondary" disabled={busy||!next} onClick={()=>setCursors(value=>[...value,next])}>下一页</Button></div></div>
  </>}
  <Dialog open={['edit','view'].includes(dialog?.kind)} onClose={close} title={dialog?.kind==='edit'?'治理隐患':'隐患详情'} size="lg" footer={<div className="hazards-actions hazards-footer"><Button variant="secondary" disabled={saving} onClick={close}>关闭</Button>{!readonly&&<Button onClick={save} disabled={saving||uncertain}>{saving?'保存中…':'保存隐患'}</Button>}</div>}>
   {error&&<p role="alert" className="hazards-error">{error}</p>}{hasRecord&&form.aiConfidence!=null&&<p className="hazards-note">提报时 AI 参考置信度：{Math.round(Number(form.aiConfidence)*100)}%；最终字段由提报人确认。</p>}{recordFields}
  </Dialog>
  <Dialog open={dialog?.kind==='review'} onClose={close} title="复审并关闭隐患" footer={<div className="hazards-actions hazards-footer"><Button variant="secondary" disabled={saving} onClick={close}>取消</Button><Button onClick={review} disabled={saving||uncertain}>{saving?'关闭中…':'复审通过并关闭'}</Button></div>}>
   {error&&<p role="alert" className="hazards-error">{error}</p>}<p><b>隐患描述：</b>{dialog?.row?.description}</p><p><b>地点：</b>{dialog?.row?.location} · {dialog?.row?.line}</p><p><b>治理责任人：</b>{dialog?.row?.responsible_person} · <b>治理时限：</b>{fmt(dialog?.row?.governance_deadline)}</p><p><b>治理措施：</b>{dialog?.row?.governance_measures}</p><p><b>具体治理情况：</b>{dialog?.row?.governance_details}</p>
   <div className="hazards-actions">{dialog?.row?.before_photo_id&&<Button size="sm" variant="secondary" onClick={()=>void showPhoto('before')}>查看提报前照片</Button>}{dialog?.row?.after_photo_id&&<Button size="sm" variant="secondary" onClick={()=>void showPhoto('after')}>查看整改后照片</Button>}</div>{photoUrl&&<img className="hazards-photo" src={photoUrl} alt={photoKind==='before'?'提报前现场照片':'整改后现场照片'}/>}<p className="hazards-note">关闭后自动评分进入案例库，低质量案例暂不参与 AI 检索。</p>
  </Dialog>
  <Dialog open={dialog?.kind==='case'} onClose={close} title="闭环案例" footer={<Button variant="secondary" onClick={close}>关闭</Button>}><p><b>{dialog?.row?.description}</b></p><p>分类：{dialog?.row?.category} · 等级：{dialog?.row?.level}</p><p>治理措施：{dialog?.row?.governance_measures}</p><p>治理结果：{dialog?.row?.governance_details}</p><p className="hazards-note">质量评分 {dialog?.row?.quality_score} · {dialog?.row?.retrieval_enabled?'参与后续建议':'待补充，不参与检索'} · 模型训练关闭</p></Dialog>
 </main>;
}
createRoot(document.getElementById('app')).render(<App/>);
window.addEventListener('pagehide',()=>sandbox.close(),{once:true});
