import React,{useEffect,useState} from 'react';
import {PencilSimpleLine} from '@phosphor-icons/react';
import {Button,Input,Select,Dialog,DataList,TableActionButton,OrganizationPeoplePicker,type PickerPerson,type PickerOrganization} from '../../components/ui';
import {employeeRequest} from './client';
import {emptyAudience,included,lineage,selectPerson,selectOrganization,type Audience} from './membership-selection';
const labels={self:'本人',workgroup:'本工班',department:'本部室及下属工班',organizations:'指定组织',all:'全平台'};
type Scope=keyof typeof labels;
type Rule={permission:string;scope:Scope;organizationIds:string[]};
type Role={id:string;name:string;status:'active'|'inactive';rules:Rule[]};
type State={revision:string;defaultRoleId:string|null;audience:Audience|null;roles:Role[];permissions:{code:string;description:string;scopeKinds?:Scope[]}[]};
type Person=PickerPerson&{roleId:string|null};
type Directory={people:Person[];organizations:PickerOrganization[];hasMore:boolean};
export function BusinessAuthorization({appId,name,initialSection,onClose,onSaved}:{appId:string;name:string;initialSection:'people'|'roles';onClose:()=>void;onSaved?:(message:string)=>void}){
 const [state,setState]=useState<State|null>(null),[draft,setDraft]=useState<Audience>(emptyAudience),[section,setSection]=useState<'roles'|'members'>('roles');
 const [directory,setDirectory]=useState<Directory>({people:[],organizations:[],hasMore:false}),[organizationId,setOrganization]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [selected,setSelected]=useState<string[]>([]),[batchRole,setBatchRole]=useState(''),[edit,setEdit]=useState<Role|null>(null),[notice,setNotice]=useState('');
 const path=`/apps/${encodeURIComponent(appId)}/business-authorization`,peopleMode=initialSection==='people';
 useEffect(()=>{const c=new AbortController();employeeRequest<State>(path,{signal:c.signal}).then(v=>{setState(v);setDraft({...emptyAudience,...v.audience})}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[path]);
 useEffect(()=>{const c=new AbortController();setLoading(true);employeeRequest<Directory>(`/apps/${encodeURIComponent(appId)}/business-directory?search=${encodeURIComponent(search)}&page=${page}${organizationId?`&organizationId=${organizationId}`:''}&membersOnly=${!peopleMode&&section==='members'}`,{signal:c.signal}).then(setDirectory).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[appId,search,page,organizationId,peopleMode,section,state?.revision]);
 async function save(change:object,closeAfterSave=false){if(!state||busy)return;setBusy(true);setError('');setNotice('');try{const next=await employeeRequest<State>(path,{method:'POST',body:{...change,revision:state.revision}});setState(next);setDraft({...emptyAudience,...next.audience});setEdit(null);setSelected([]);setNotice('已保存');if(closeAfterSave)onSaved?.(peopleMode?'人员范围已保存。':'角色分配已保存。');if(closeAfterSave)onClose()}catch(e){const code=(e as Error).message;setError(code.includes('APP_MULTIPLE_ROLES')?'旧配置存在一人多个角色，请先核对后再切换。':code.includes('APP_DELEGATIONS_REQUIRE_REVIEW')?'旧配置包含工班委派，需先核对后再切换。':code)}finally{setBusy(false)}}
 const picker=<OrganizationPeoplePicker organizations={directory.organizations} people={directory.people} organizationId={organizationId} onOrganizationChange={id=>{setOrganization(id);setPage(1)}} search={search} onSearchChange={v=>{setSearch(v);setPage(1)}} page={page} hasNext={directory.hasMore} onPageChange={setPage} loading={loading} disabled={busy}
 selected={p=>peopleMode?included(draft,p,directory.organizations):selected.includes(p.id)} onPersonChange={(p,checked)=>{if(peopleMode)setDraft(old=>selectPerson(old,p,checked,directory.organizations));else setSelected(old=>checked?[...new Set([...old,p.id])]:old.filter(id=>id!==p.id))}}
 organizationSelection={peopleMode?id=>{const current=included(draft,{id:'',name:'',employeeNo:'',organizationId:id},directory.organizations);const children=directory.organizations.filter(o=>lineage(o.id,directory.organizations).includes(id));const flags=children.map(o=>included(draft,{id:'',name:'',employeeNo:'',organizationId:o.id},directory.organizations));return flags.some(v=>v!==current)||(draft.personOverrides??[]).some(o=>lineage(o.organizationId,directory.organizations).includes(id))?'mixed':current}:undefined} onOrganizationSelection={peopleMode?(id,checked)=>setDraft(old=>selectOrganization(old,id,checked,directory.organizations)):undefined}
 renderPersonAction={!peopleMode?p=><Select aria-label={`${p.name}的角色`} disabled={busy} value={(p as Person).roleId??state?.defaultRoleId??''} onChange={e=>void save({action:'assign',personIds:[p.id],roleId:e.target.value})}><option value="" disabled>请选择角色</option>{state?.roles.map(r=><option key={r.id} value={r.id} disabled={r.status!=='active'}>{r.name}{r.status==='inactive'?'（已停用）':''}</option>)}</Select>:undefined}/>;
 const alerts=<>{error&&<p className="afc-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</>;
 const roleList=<><div className="admin-heading"><h2>角色配置</h2><Button disabled={busy} onClick={()=>setEdit({id:'',name:'',status:'active',rules:[]})}>新增角色</Button></div>{!state?.defaultRoleId&&<p className="afc-muted">保存人员范围后自动创建普通成员角色；操作权限由负责人配置。</p>}<DataList emptyState={!state?.roles.length?'暂无角色':undefined}><thead><tr><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>{state?.roles.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.status==='active'?'启用':'停用'}</td><td><TableActionButton icon={<PencilSimpleLine size={18}/>} disabled={busy} onClick={()=>setEdit(structuredClone(r))}>修改</TableActionButton></td></tr>)}</tbody></DataList></>;
 return <><Dialog open title={peopleMode?`${name} · 人员管理`:name} size="xl" className={peopleMode?undefined:'afc-profile-dialog afc-sidebar-dialog'} onClose={()=>{if(!busy)onClose()}} footer={peopleMode?<Button disabled={busy||!state} onClick={()=>void save({action:'membership',audience:draft},true)}>{busy?'保存中…':'保存人员范围'}</Button>:undefined}>
 {peopleMode?<>{alerts}<p className="afc-muted">所选组织的成员自动加入并使用普通成员角色；取消工班或个人即可排除。</p><label className="app-members-all"><input type="checkbox" checked={draft.all} disabled={busy} onChange={e=>setDraft({...draft,all:e.target.checked})}/>全体在职员工</label>{picker}</>:<div className="afc-profile-layout"><nav className="afc-profile-nav" aria-label="角色设置"><Button variant="ghost" shape="rounded" aria-current={section==='roles'?'page':undefined} onClick={()=>setSection('roles')}>角色配置</Button><Button variant="ghost" shape="rounded" aria-current={section==='members'?'page':undefined} onClick={()=>setSection('members')}>角色分配</Button></nav><section className="afc-profile-content app-role-content">{alerts}{section==='roles'?roleList:<><h2>角色分配</h2>{!state?.defaultRoleId?<p>请先在人员管理中保存使用范围。</p>:<><div className="admin-actions"><Select aria-label="批量分配角色" value={batchRole} onChange={e=>setBatchRole(e.target.value)}><option value="">选择角色</option>{state.roles.filter(r=>r.status==='active').map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</Select><Button disabled={busy||!selected.length||!batchRole} onClick={()=>void save({action:'assign',personIds:selected,roleId:batchRole},true)}>{busy?'保存中…':`应用到选中 ${selected.length} 人`}</Button></div>{picker}</>}</>}</section></div>}
 </Dialog>{edit&&<Dialog open title={edit.id?'修改角色':'新增角色'} size="lg" onClose={()=>{if(!busy)setEdit(null)}} footer={<Button disabled={busy||!edit.name.trim()||edit.rules.some(r=>r.scope==='organizations'&&!r.organizationIds.length)} onClick={()=>{const {id,...rest}=edit;void save({action:'role',...rest,...(id?{id}:{})})}}>{busy?'保存中…':'保存角色'}</Button>}><div className="admin-form">{alerts}<label>名称<Input disabled={busy||edit.id===state?.defaultRoleId} maxLength={100} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>状态<Select disabled={busy||edit.id===state?.defaultRoleId} value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value as Role['status']})}><option value="active">启用</option><option value="inactive">停用</option></Select></label>{state?.permissions.map(p=>{const rule=edit.rules.find(r=>r.permission===p.code);return <div key={p.code}><label>{p.description}<Select disabled={busy} value={rule?.scope??''} onChange={e=>setEdit({...edit,rules:[...edit.rules.filter(r=>r.permission!==p.code),...(e.target.value?[{permission:p.code,scope:e.target.value as Scope,organizationIds:[]}]:[])]})}><option value="">不授权</option>{(p.scopeKinds??['all']).map(scope=><option value={scope} key={scope}>{labels[scope]}</option>)}</Select></label>{rule?.scope==='organizations'&&<div className="app-choice-list">{directory.organizations.map(o=><label key={o.id}><input type="checkbox" checked={rule.organizationIds.includes(o.id)} onChange={e=>setEdit({...edit,rules:edit.rules.map(r=>r===rule?{...r,organizationIds:e.target.checked?[...r.organizationIds,o.id]:r.organizationIds.filter(id=>id!==o.id)}:r)})}/>{o.name}</label>)}</div>}</div>})}</div></Dialog>}</>;
}
