import {PencilSimpleLine,UserMinus} from '@phosphor-icons/react';
import React,{useEffect,useState,useId} from 'react';
import {Button,Input,Select,DataList,TableActionButton,Dialog,FilterBar} from '../../components/ui';
import {employeeRequest} from './client';
const labels={self:'本人',workgroup:'本工班',department:'本部室及下属工班',organizations:'指定组织',all:'全平台'};
type Scope=keyof typeof labels;
type Rule={permission:string;scope:Scope;organizationIds:string[]};
type Role={id:string;name:string;status:'active'|'inactive';rules:Rule[]};
type Audience={all:boolean;personIds:string[];organizationIds:string[];departmentIds:string[]};
type State={audience:Audience|null;revision:string;mode:string;permissions:{code:string;description:string;scopeKinds?:Scope[]}[];roles:Role[];members:{roleId:string;personId:string;name:string;employeeNo:string}[]};
type Directory={people:{id:string;name:string;employeeNo:string}[];hasMore:boolean;organizations:{id:string;name:string;type:string}[]};
export function BusinessAuthorization({appId}:{appId:string}){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[section,setSection]=useState<'audience'|'roles'|'members'>('audience');
 const [directory,setDirectory]=useState<Directory>({people:[],organizations:[],hasMore:false}),[search,setSearch]=useState(''),[page,setPage]=useState(1),[person,setPerson]=useState(''),[role,setRole]=useState('');
 const [edit,setEdit]=useState<Partial<Role>|null>(null),[dialog,setDialog]=useState(false),[activate,setActivate]=useState(false);
 const path=`/apps/${encodeURIComponent(appId)}/business-authorization`;
 useEffect(()=>{const c=new AbortController();employeeRequest<State>(path,{signal:c.signal}).then(setState).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[path]);
 useEffect(()=>{const c=new AbortController();employeeRequest<Directory>(`/apps/${encodeURIComponent(appId)}/business-directory?search=${encodeURIComponent(search)}&page=${page}`,{signal:c.signal}).then(setDirectory).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[appId,search,page]);
 async function save(change:object){if(!state||busy)return;setBusy(true);setError('');try{setState(await employeeRequest<State>(path,{method:'POST',body:{...change,revision:state.revision}}));setEdit(null);setActivate(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const open=(name:typeof section)=>{setSection(name);setDialog(true);};
 return <section className="employee-app-management"><div className="admin-heading"><div><h1>应用管理</h1><p className="afc-muted">配置使用人群、业务角色和人员分配。应用停用时仍可维护配置。</p></div></div>{error&&<p role="alert" className="afc-error">{error}</p>}
  <DataList emptyState={!state?'加载中…':state.roles.length===0?'尚未创建角色':undefined}><thead><tr><th>角色</th><th>权限与数据范围</th><th>状态</th></tr></thead><tbody>{state?.roles.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.rules.map((g,i)=><span className="app-business-rule-chip" key={i}>{state.permissions.find(p=>p.code===g.permission)?.description??g.permission} · {labels[g.scope]}</span>)}</td><td>{r.status==='active'?'启用':'停用'}</td></tr>)}</tbody></DataList>
  <div className="employee-app-management-actions"><Button variant="secondary" disabled={!state} onClick={()=>open('audience')}>使用人群</Button><Button variant="secondary" disabled={!state} onClick={()=>open('roles')}>角色设置</Button><Button variant="secondary" disabled={!state} onClick={()=>open('members')}>分配人员</Button></div>
  <Dialog open={dialog} title="应用管理" size="xl" className="afc-profile-dialog afc-sidebar-dialog" onClose={()=>{if(!busy)setDialog(false);}}>
   <div className="afc-profile-layout"><nav className="afc-profile-nav" aria-label="应用管理设置">{([['audience','使用人群'],['roles','角色设置'],['members','人员分配']] as const).map(([id,label])=><Button key={id} variant="ghost" shape="rounded" aria-current={section===id?'page':undefined} onClick={()=>setSection(id)}>{label}</Button>)}</nav>
    <section className="afc-profile-content">{section==='audience'&&state&&<AudienceEditor value={state.audience} directory={directory} busy={busy} save={audience=>save({action:'audience',audience})}/>} {section==='roles'&&state&&<RoleEditor state={state} edit={edit} setEdit={setEdit} busy={busy} save={change=>save({action:'role',...change})}/>} {section==='members'&&state&&<MemberEditor state={state} directory={directory} search={search} setSearch={v=>{setSearch(v);setPage(1)}} page={page} setPage={setPage} person={person} setPerson={setPerson} role={role} setRole={setRole} busy={busy} save={save}/>}</section>
   </div>
  </Dialog>
  <Dialog open={activate} title="切换应用授权" onClose={()=>{if(!busy)setActivate(false);}} footer={<><Button variant="secondary" disabled={busy} onClick={()=>setActivate(false)}>取消</Button><Button disabled={busy} onClick={()=>void save({action:'activate',confirm:true})}>确认切换</Button></>}><p>切换后，仅此处的角色和人员分配生效。</p></Dialog>
 </section>;
}
function AudienceEditor({value,directory,busy,save}:{value:Audience|null;directory:Directory;busy:boolean;save:(value:Audience)=>Promise<void>}){const [draft,setDraft]=useState<Audience>(value??{all:false,personIds:[],organizationIds:[],departmentIds:[]});const selected=(e:React.ChangeEvent<HTMLSelectElement>)=>Array.from(e.target.selectedOptions,o=>o.value);return <div><h2>使用人群</h2><p className="afc-muted">{value?value.all?'全体在职员工':`指定 ${value.personIds.length} 位人员、${value.organizationIds.length} 个组织、${value.departmentIds.length} 个部室及下属组织`:'沿用现有人员角色配置'}</p><div className="admin-form"><label>范围<Select value={draft.all?'all':'selected'} onChange={e=>setDraft({...draft,all:e.target.value==='all'})}><option value="selected">指定人群</option><option value="all">全体在职员工</option></Select></label>{!draft.all&&<><label>指定人员<Select multiple value={draft.personIds} onChange={e=>setDraft({...draft,personIds:selected(e)})}>{[...new Set([...draft.personIds,...directory.people.map(p=>p.id)])].map(id=><option key={id} value={id}>{directory.people.find(p=>p.id===id)?.name??'已选人员'}</option>)}</Select></label><label>指定组织<Select multiple value={draft.organizationIds} onChange={e=>setDraft({...draft,organizationIds:selected(e)})}>{directory.organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></label><label>部室及下属组织<Select multiple value={draft.departmentIds} onChange={e=>setDraft({...draft,departmentIds:selected(e)})}>{directory.organizations.filter(o=>o.type==='department').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></label></>}<Button disabled={busy} onClick={()=>void save(draft)}>保存使用人群</Button></div></div>}
function RoleEditor({state,edit,setEdit,busy,save}:{state:State;edit:Partial<Role>|null;setEdit:(v:Partial<Role>|null)=>void;busy:boolean;save:(v:Partial<Role>)=>Promise<void>}){return <div><div className="admin-heading"><h2>角色设置</h2><Button onClick={()=>setEdit({name:'',status:'active',rules:[]})}>新增角色</Button></div><DataList emptyState="暂无角色"><thead><tr><th>角色</th><th>权限与范围</th><th>操作</th></tr></thead><tbody>{state.roles.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.rules.map(g=><span className="app-business-rule-chip" key={g.permission}>{state.permissions.find(p=>p.code===g.permission)?.description??g.permission} · {labels[g.scope]}</span>)}</td><td><TableActionButton icon={<PencilSimpleLine size={18}/>} onClick={()=>setEdit(structuredClone(r))}>修改</TableActionButton></td></tr>)}</tbody></DataList>{edit&&<Dialog open title={edit.id?'修改角色':'新增角色'} size="lg" onClose={()=>setEdit(null)} footer={<Button disabled={busy} onClick={()=>void save(edit)}>保存角色</Button>}><div className="admin-form"><label>角色名称<Input required value={edit.name??''} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>状态<Select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value as Role['status']})}><option value="active">启用</option><option value="inactive">停用</option></Select></label>{state.permissions.map(p=>{const g=edit.rules?.find(r=>r.permission===p.code);return <label key={p.code}>{p.description}<Select value={g?.scope??''} onChange={e=>setEdit({...edit,rules:[...(edit.rules??[]).filter(r=>r.permission!==p.code),...(e.target.value?[{permission:p.code,scope:e.target.value as Scope,organizationIds:[]}]:[])]})}><option value="">不授权</option>{(p.scopeKinds??['all']).map(k=><option key={k} value={k}>{labels[k]}</option>)}</Select></label>})}</div></Dialog>}</div>}
function MemberEditor({state,directory,search,setSearch,page,setPage,person,setPerson,role,setRole,busy,save}:{state:State;directory:Directory;search:string;setSearch:(v:string)=>void;page:number;setPage:(v:number)=>void;person:string;setPerson:(v:string)=>void;role:string;setRole:(v:string)=>void;busy:boolean;save:(v:object)=>Promise<void>}){return <div><h2>分配人员</h2><FilterBar showDateRange={false} searchValue={search} onSearchChange={setSearch} searchPlaceholder="姓名或工号"/><form className="admin-form app-business-member-form" onSubmit={e=>{e.preventDefault();void save({action:'member',personId:person,roleId:role,enabled:true});}}><label>人员<Select required value={person} onChange={e=>setPerson(e.target.value)}><option value="">请选择人员</option>{directory.people.map(p=><option key={p.id} value={p.id}>{p.name} · {p.employeeNo}</option>)}</Select></label><label>角色<Select required value={role} onChange={e=>setRole(e.target.value)}><option value="">请选择角色</option>{state.roles.filter(r=>r.status==='active').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</Select></label><Button type="submit" disabled={busy||!person||!role}>分配角色</Button></form><DataList emptyState="尚未分配人员"><thead><tr><th>人员</th><th>角色</th><th>操作</th></tr></thead><tbody>{state.members.map(m=><tr key={`${m.personId}:${m.roleId}`}><td>{m.name} · {m.employeeNo}</td><td>{state.roles.find(r=>r.id===m.roleId)?.name}</td><td><TableActionButton icon={<UserMinus size={18}/>} disabled={busy} onClick={()=>void save({action:'member',roleId:m.roleId,personId:m.personId,enabled:false})}>撤销</TableActionButton></td></tr>)}</tbody></DataList></div>}
