import React,{useMemo,useState} from 'react';
import {Button,Plus,QueryList,ListPagination,TableHeader,TableBody,TableRow,TableHead,TableCell,TableActions,TableActionButton,PencilSimpleLine,ArrowLineUp} from '@metro/platform-sdk/ui';

export function PlanList({contextQuery,cycle,categories,items,search,setSearch,filters,setFilters,cursors,setCursors,nextCursor,loading,busy,statusLabels,can,personId,openItem,openProgress}){
 const byId=useMemo(()=>new Map(categories.map(row=>[row.id,row])),[categories]);
 const categoryOptions=categories.map(row=>{const names=[row.name];let parent=byId.get(row.parent_id);while(parent){names.unshift(parent.name);parent=byId.get(parent.parent_id);}return {id:row.id,label:names.join(' / ')};});
 const visible=items.filter(row=>{const category=byId.get(row.category_id),parent=byId.get(category?.parent_id);return (!search||[row.content,row.quality_standard,row.category_name,...(row.assignees??[]).map(value=>value.personName)].some(value=>String(value??'').toLocaleLowerCase().includes(search.toLocaleLowerCase())))&&(!filters.category||[row.category_id,category?.parent_id,parent?.parent_id].includes(filters.category))&&(!filters.status||row.status===filters.status);});
 const query={...contextQuery,searchValue:search,onSearchChange:setSearch,searchPlaceholder:'搜索计划内容、质量标准或责任人',filterGroups:[...contextQuery.filterGroups,{id:'category',title:'分类范围',isMulti:false,options:categoryOptions},{id:'status',title:'状态',isMulti:false,options:['draft','submitted','approved','in_progress','completed','cancelled','pending_confirm'].map(id=>({id,label:statusLabels[id]}))}],activeFilters:{selectedOptions:{...contextQuery.activeFilters.selectedOptions,category:filters.category?[filters.category]:[],status:filters.status?[filters.status]:[]}},onApplyFilters:value=>{contextQuery.onApplyFilters(value);setFilters({category:value.selectedOptions.category?.[0]??'',status:value.selectedOptions.status?.[0]??''});},onResetFilters:()=>{contextQuery.onResetFilters();setFilters({category:'',status:''});setSearch('');}};
 return <QueryList query={query} actions={can('fill')?<Button size="sm" leadingIcon={<Plus size={16}/>} onClick={()=>openItem()} disabled={loading||busy||!!cycle&&cycle.status!=='drafting'}>新增计划</Button>:null} emptyState={loading?'加载中…':!visible.length?items.length?'本页暂无符合条件的计划':!categories.some(row=>row.level===3&&row.enabled)?'暂无可用的业务模块':'该月暂无计划':undefined}
  pagination={cycle&&<ListPagination page={cursors.length} hasNext={!!nextCursor} busy={loading} onPrevious={()=>setCursors(value=>value.slice(0,-1))} onNext={()=>setCursors(value=>[...value,nextCursor])}/>}>
  <TableHeader><TableRow>{['模块 / 分类 / 业务模块','工作计划内容','质量标准','计划时间','责任人','状态','操作'].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader>
  <TableBody>{visible.map(row=><TableRow key={row.id}><TableCell>{row.root_name} / {row.parent_name} / {row.category_name}</TableCell><TableCell className="hct-wrap">{row.content}{row.escalated&&<small>拟提报中心</small>}</TableCell><TableCell className="hct-wrap">{row.quality_standard}</TableCell><TableCell>{row.start_date} 至 {row.end_date}</TableCell><TableCell>{row.assignees?.find(person=>person.isLead)?.personName??'—'}</TableCell><TableCell className="hct-status">{statusLabels[row.status]??row.status}{row.remark&&<small>{row.remark}</small>}</TableCell><TableCell><TableActions>{cycle?.status==='drafting'&&row.status==='draft'&&(can('manage')||can('fill')&&row.created_by===personId)&&<TableActionButton disabled={busy} icon={<PencilSimpleLine size={18}/>} onClick={()=>openItem(row)}>编辑</TableActionButton>}{['draft','in_progress'].includes(row.status)&&['drafting','locked','closing'].includes(cycle?.status)&&(can('manage')||can('fill')&&row.assignees?.some(person=>person.personId===personId))&&<TableActionButton disabled={busy} icon={<ArrowLineUp size={18}/>} onClick={()=>openProgress(row)}>更新进度</TableActionButton>}</TableActions></TableCell></TableRow>)}</TableBody>
 </QueryList>;
}

export function CategoryList({contextQuery,categories,search,setSearch,statusFilter,setStatusFilter,loading,busy,can,openCategory,toggleCategory}){
 const [collapsed,setCollapsed]=useState([]);
 const byId=useMemo(()=>new Map(categories.map(row=>[row.id,row])),[categories]);
 const children=useMemo(()=>new Set(categories.map(row=>row.parent_id)),[categories]);
 const matches=new Set(categories.filter(row=>(!search||row.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()))&&(!statusFilter||String(row.enabled)===statusFilter)).map(row=>row.id));
 const included=new Set(matches);
 for(const row of categories){if(!matches.has(row.id))continue;let parent=byId.get(row.parent_id);while(parent){included.add(parent.id);parent=byId.get(parent.parent_id);}}
 const visible=categories.filter(row=>{let parent=byId.get(row.parent_id),ancestorMatched=false;while(parent){if(!search&&collapsed.includes(parent.id))return false;if(matches.has(parent.id))ancestorMatched=true;parent=byId.get(parent.parent_id);}return included.has(row.id)||!!search&&!statusFilter&&ancestorMatched;});
 return <QueryList query={{...contextQuery,searchValue:search,onSearchChange:setSearch,searchPlaceholder:'搜索分类名称',filterGroups:[...contextQuery.filterGroups,{id:'status',title:'状态',isMulti:false,options:[{id:'true',label:'启用'},{id:'false',label:'停用'}]}],activeFilters:{selectedOptions:{...contextQuery.activeFilters.selectedOptions,status:statusFilter?[statusFilter]:[]}},onApplyFilters:value=>{contextQuery.onApplyFilters(value);setStatusFilter(value.selectedOptions.status?.[0]??'');},onResetFilters:()=>{contextQuery.onResetFilters();setStatusFilter('');setSearch('');}}} actions={can('manage')?<Button size="sm" leadingIcon={<Plus size={16}/>} disabled={loading||busy} onClick={()=>openCategory()}>新增分类</Button>:null} emptyState={loading?'加载中…':!visible.length?categories.length?'暂无符合条件的分类':'暂无分类':undefined}>
  <TableHeader><TableRow><TableHead>模块 / 分类 / 业务模块</TableHead><TableHead>层级</TableHead><TableHead>排序</TableHead><TableHead>状态</TableHead><TableHead>操作</TableHead></TableRow></TableHeader>
  <TableBody>{visible.map(row=><TableRow key={row.id}><TableCell><div className="hct-tree-name" style={{paddingInlineStart:`${(row.level-1)*24}px`}}>{children.has(row.id)?<button type="button" className="hct-tree-toggle" aria-label={`${collapsed.includes(row.id)?'展开':'收起'}${row.name}`} aria-expanded={search?true:!collapsed.includes(row.id)} onClick={()=>setCollapsed(old=>old.includes(row.id)?old.filter(id=>id!==row.id):[...old,row.id])}>{search?'▾':collapsed.includes(row.id)?'▸':'▾'}</button>:<span className="hct-tree-spacer"/>}{row.name}</div></TableCell><TableCell>{['模块','业务分类','业务模块'][row.level-1]}</TableCell><TableCell>{row.sort}</TableCell><TableCell>{row.enabled?'启用':'停用'}</TableCell><TableCell><TableActions>{can('manage')&&<TableActionButton disabled={busy} icon={<PencilSimpleLine size={18}/>} onClick={()=>openCategory(row)}>编辑</TableActionButton>}{can('manage')&&row.level===3&&<TableActionButton disabled={busy} icon={<ArrowLineUp size={18}/>} onClick={()=>toggleCategory(row)}>{row.enabled?'停用':'启用'}</TableActionButton>}</TableActions></TableCell></TableRow>)}</TableBody>
 </QueryList>;
}
