import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Button,Input,Field,Dialog,DropdownSelect,OrganizationPicker,OrganizationPeoplePicker} from '@metro/platform-sdk/ui';
import {platformUiCss} from '@metro/platform-sdk/ui-styles';
import {createAppSandboxClient,createAppApiClient} from '@metro/platform-sdk/app-sandbox';
import {downloadSandboxFile} from '@metro/platform-sdk/app-files';
import {PlanList,CategoryList} from './lists.jsx';
import {validMonth,monthCycle} from './month.mjs';

const script=document.currentScript,origin=script?.dataset.platformOrigin;
if(!origin)throw Error('PLATFORM_ORIGIN_REQUIRED');
const initialRoute=decodeURIComponent(script?.dataset.appRoute??'/')==='/bindings'?'/bindings':'/';
document.documentElement.classList.add('afc-theme-neutral');
const style=document.createElement('style');style.nonce=script?.nonce??'';style.textContent=platformUiCss+`
body{margin:0;background:var(--afc-color-canvas,#fafafa);color:var(--afc-color-ink,#18181b);font-family:var(--afc-font-ui,system-ui)}
*{box-sizing:border-box}.hct{max-width:1200px;margin:auto;padding:24px}.hct h1{font-size:22px;margin:0}.hct h2{font-size:17px;margin:0 0 12px}.hct-muted{color:var(--afc-color-muted,#71717a);font-size:13px}.hct-head,.hct-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.hct-head{justify-content:space-between;margin-bottom:22px}.hct-panel{background:var(--afc-color-surface,#fff);border:1px solid var(--afc-color-border,#e4e4e7);border-radius:12px;padding:18px;margin-bottom:16px}.hct-row{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;padding:11px 0;border-top:1px solid var(--afc-color-border,#e4e4e7)}.hct-row b{display:block}.hct-row small,.hct-wrap small{display:block;color:var(--afc-color-muted,#71717a)}.hct-alert{padding:12px 14px;border-radius:9px;background:#fff1f2;color:#9f1239;margin-bottom:14px}.hct-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.hct-wide{grid-column:1/-1}.hct-form textarea{width:100%;min-height:84px}.hct-footer{display:flex;gap:8px;justify-content:flex-end}.hct-people-picker .afc-people-picker{min-height:230px}.hct-wrap{min-width:180px;max-width:320px;white-space:normal;overflow-wrap:anywhere}.hct-tree-name{display:flex;align-items:center;white-space:nowrap}.hct-tree-toggle,.hct-tree-spacer{width:24px;flex:none}.hct-tree-toggle{border:0;background:transparent;color:inherit;cursor:pointer}.hct-table{width:100%;border-collapse:collapse;min-width:980px}.hct-table td,.hct-table th{border:1px solid var(--afc-color-border,#e4e4e7);padding:8px;text-align:left;vertical-align:top}.hct-scroll{overflow:auto}.hct .afc-filter-bar-wrapper--spread{width:100%}.hct .afc-filter-bar-wrapper--spread .afc-filter-bar{justify-content:flex-end}.hct .afc-filter-bar-wrapper--spread .afc-filter-right-action{margin-left:0}.hct .afc-filter-right-action .hct-actions{flex-wrap:nowrap}.hct .afc-filter-right-action .hct-actions>input{width:155px}.hct .afc-filter-right-action .hct-actions>div{width:135px}@media(max-width:700px){.hct{padding:12px}.hct-form{grid-template-columns:1fr}.hct-wide{grid-column:1}.hct-row{flex-direction:column}.hct-head{align-items:flex-start}.hct .afc-filter-right-action .hct-actions{flex-wrap:wrap}}
`;document.head.append(style);
const sandbox=createAppSandboxClient({appId:'huicetong',platformOrigin:origin,port:{parent:window.parent,send:(data,target)=>window.parent.postMessage(data,target),listen:listener=>{window.addEventListener('message',listener);return()=>window.removeEventListener('message',listener);}}});
const api=createAppApiClient(sandbox);
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const blankItem=(month=today().slice(0,7))=>({categoryId:'',content:'',qualityStandard:'',startDate:`${month}-01`,endDate:new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0)).toISOString().slice(0,10),escalated:false,remark:'',assignees:[]});
const blankCategory=()=>({id:null,level:3,parentId:null,name:'',sort:0,enabled:true,expectedRevision:undefined});
const messages={INVALID_INPUT:'请检查填写内容',EMPLOYEE_REQUIRED:'员工身份不可用',ACCESS_DENIED:'没有此操作权限',CONFLICT:'记录已被修改，请重新打开后再编辑',CYCLE_LOCKED:'本月计划已进入后续流程，不可提报',CATEGORY_INVALID:'分类无效或已停用',PERSON_INVALID:'责任人须为该部门下在岗工班成员',ITEM_TOO_LARGE:'数据超过单次处理上限'};
const statusLabels={draft:'待开始',submitted:'已提交',approved:'已通过',in_progress:'进行中',completed:'已完成',cancelled:'已取消',pending_confirm:'待确认'};
const columns=['序号','模块','业务分类','业务模块','工作计划内容','质量标准','开始时间','完成时间','责任人','备注'];
const sortCategories=rows=>{const result=[];const visit=parent=>{for(const row of rows.filter(value=>value.parent_id===parent).sort((a,b)=>a.sort-b.sort||a.name.localeCompare(b.name))){result.push(row);visit(row.id);}};visit(null);return result;};
const previewRows=rows=>rows.map((row,index)=>[index+1,row.root_name,row.parent_name,row.category_name,row.content,row.quality_standard,row.start_date,row.end_date,(row.assignees??[]).map(person=>person.personName).join('、'),row.remark??'']);

function App(){
 const [session,setSession]=useState(null),[organizationId,setOrganizationId]=useState(''),[cycles,setCycles]=useState([]),[month,setMonth]=useState(today().slice(0,7)),[categories,setCategories]=useState([]),[items,setItems]=useState([]),[bindings,setBindings]=useState([]),[people,setPeople]=useState([]),[peopleSearch,setPeopleSearch]=useState(''),[peopleLoading,setPeopleLoading]=useState(false),[route,setRoute]=useState(initialRoute),[search,setSearch]=useState(''),[categoryFilter,setCategoryFilter]=useState(''),[statusFilter,setStatusFilter]=useState(''),[categorySearch,setCategorySearch]=useState(''),[categoryStatus,setCategoryStatus]=useState(''),[dialog,setDialog]=useState(null),[itemForm,setItemForm]=useState(blankItem()),[categoryForm,setCategoryForm]=useState(blankCategory()),[progressStatus,setProgressStatus]=useState('in_progress'),[progressRemark,setProgressRemark]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reload,setReload]=useState(0);
 const [cursors,setCursors]=useState([null]),[nextCursor,setNextCursor]=useState(null),[itemsLoading,setItemsLoading]=useState(false),[previewItems,setPreviewItems]=useState([]),[previewLoading,setPreviewLoading]=useState(false);
 const uncertain=useRef(null),writing=useRef(false);
 const can=name=>session?.permissions.includes(`app.huicetong.${name}`);
 const cycle=monthCycle(cycles,month),orgName=session?.organizations.find(value=>value.id===organizationId)?.name??'当前部门';
 const categoryOptions=useMemo(()=>{const byId=new Map(categories.map(value=>[value.id,value]));return categories.map(value=>{let current=value,active=true;const seen=new Set();while(current&&!seen.has(current.id)){seen.add(current.id);if(!current.enabled)active=false;current=current.parent_id?byId.get(current.parent_id):null;}return {id:value.id,name:value.name,parentId:value.parent_id,status:active?'active':'inactive'};});},[categories]);
 async function call(name,payload,write=false){
  if(write&&(writing.current||uncertain.current))throw Error(uncertain.current?`请求 ${uncertain.current} 的写入结果待核对，请勿重试`:'正在保存');
  if(write)writing.current=true;
  try{const response=await api.invoke(name,payload);if(!response.ok){const definitive=response.error?.writeOutcome==='not_started';if(write&&!definitive)uncertain.current=payload.requestId;const failure=Error(messages[response.error?.code]??(write?'写入结果未确认，请核对后再处理':'读取失败，请重试'));failure.definitive=definitive;throw failure;}return response.result;}
  catch(failure){if(write&&!failure.definitive)uncertain.current=payload.requestId;throw failure;}
  finally{if(write)writing.current=false;}
 }
 async function loadAll(name,payload){const rows=[];let after;for(let pageNumber=0;pageNumber<100;pageNumber++){const page=await call(name,{...payload,...(after?{after}:{})});rows.push(...page.rows);if(!page.nextCursor)return rows;after=page.nextCursor;}throw Error('记录较多，请缩小范围后重试');}
 useEffect(()=>{let alive=true;const timer=setInterval(async()=>{if(!sandbox.ready())return;clearInterval(timer);try{const value=await call('session',{});if(alive){setSession(value);setOrganizationId(value.organizations[0]?.id??value.organizationId);}}catch(failure){if(alive)setError(failure.message);}},25);return()=>{alive=false;clearInterval(timer);};},[]);
 useEffect(()=>sandbox.onRouteChange(path=>setRoute(path==='/bindings'?'/bindings':'/')),[]);
 useEffect(()=>{setDialog(null);setSearch('');setCategoryFilter('');setStatusFilter('');},[route]);
 useEffect(()=>{if(!session||!organizationId)return;let alive=true;Promise.all([loadAll('cycle-list',{organizationId}),loadAll('category-list',{organizationId}),call('binding-list',{organizationId})]).then(([cycleRows,categoryRows,bindingPage])=>{if(alive){setCycles(cycleRows);setCategories(sortCategories(categoryRows));setBindings(bindingPage.rows);setError('');}}).catch(failure=>{if(alive)setError(failure.message);});return()=>{alive=false;};},[session,organizationId,reload]);
 useEffect(()=>{setCursors([null]);setNextCursor(null);setItems([]);},[cycle?.id,organizationId,reload]);
 useEffect(()=>{if(!session||!cycle){setItems([]);setNextCursor(null);return;}let alive=true;setItemsLoading(true);call('item-list',{cycleId:cycle.id,...(cursors.at(-1)?{after:cursors.at(-1)}:{})}).then(page=>{if(alive){setItems(page.rows);setNextCursor(page.nextCursor??null);}}).catch(failure=>{if(alive)setError(failure.message);}).finally(()=>{if(alive)setItemsLoading(false);});return()=>{alive=false;};},[session,cycle?.id,reload,cursors]);
 useEffect(()=>{if(!session||!organizationId||!(route==='/bindings'||['item','binding'].includes(dialog?.kind)))return;let alive=true;setPeopleLoading(true);call('members',{organizationId,workgroupId:session.organizationId,...(peopleSearch?{search:peopleSearch}:{})}).then(page=>{if(alive)setPeople(page.rows);}).catch(failure=>{if(alive)setError(failure.message);}).finally(()=>{if(alive)setPeopleLoading(false);});return()=>{alive=false;};},[session,organizationId,route,dialog?.kind,peopleSearch]);
 useEffect(()=>{if(dialog?.kind!=='preview'||!cycle){setPreviewItems([]);return;}let alive=true;setPreviewLoading(true);loadAll('item-list',{cycleId:cycle.id}).then(rows=>{if(alive)setPreviewItems(rows);}).catch(failure=>{if(alive)setError(failure.message);}).finally(()=>{if(alive)setPreviewLoading(false);});return()=>{alive=false;};},[dialog?.kind,cycle?.id,reload]);
 useEffect(()=>{if(!session)return;void sandbox.invoke('platform.ui.modal',{open:!!dialog}).catch(()=>{});},[session,!!dialog]);
 function openItem(row=null){setError('');setPeopleSearch('');setItemForm(row?{categoryId:row.category_id,content:row.content,qualityStandard:row.quality_standard,startDate:row.start_date,endDate:row.end_date,escalated:row.escalated,remark:row.remark??'',assignees:row.assignees??[]}:blankItem(month));setDialog({kind:'item',row});}
 function openCategory(row=null){setError('');setCategoryForm(row?{id:row.id,level:row.level,parentId:row.parent_id,name:row.name,sort:row.sort,enabled:row.enabled,expectedRevision:row.revision}:blankCategory());setDialog({kind:'category'});}
 async function saveCategory(){if(busy)return;setBusy(true);setError('');try{await call('category-upsert',{id:categoryForm.id??crypto.randomUUID(),requestId:crypto.randomUUID(),organizationId,parentId:categoryForm.level===1?null:categoryForm.parentId,level:categoryForm.level,name:categoryForm.name,sort:Number(categoryForm.sort),enabled:categoryForm.enabled,...(categoryForm.id?{expectedRevision:categoryForm.expectedRevision}:{})},true);setDialog(null);setReload(value=>value+1);}catch(failure){setError(failure.message);}finally{setBusy(false);}}
 async function saveItem(){if(busy||!validMonth(month)){setError('请选择有效的计划月份');return;}if(!itemForm.assignees.length||!itemForm.assignees.some(value=>value.isLead)){setError('请选择责任人并指定牵头人');return;}setBusy(true);setError('');try{const draft={...itemForm,assignees:itemForm.assignees.map(value=>({personId:value.personId,organizationUnitId:value.organizationUnitId,isLead:value.isLead}))};await call(dialog.row?'item-update':'item-create',{id:dialog.row?.id??crypto.randomUUID(),requestId:crypto.randomUUID(),...(dialog.row?{expectedVersion:dialog.row.version}:{organizationId,year:Number(month.slice(0,4)),month:Number(month.slice(5,7))}),draft},true);setDialog(null);setReload(value=>value+1);}catch(failure){setError(failure.message);}finally{setBusy(false);}}
 async function runWrite(name,payload){if(busy)return;setBusy(true);setError('');try{await call(name,{...payload,requestId:crypto.randomUUID()},true);setDialog(null);setReload(value=>value+1);}catch(failure){setError(failure.message);}finally{setBusy(false);}}
 async function exportPlan(){if(!cycle){setError('该月暂无计划可导出');return;}if(busy)return;setBusy(true);setError('');try{const result=await call('export-plan',{cycleId:cycle.id,scope:'all',requestId:crypto.randomUUID()},true);const bytes=Uint8Array.from(atob(result.base64),character=>character.charCodeAt(0));downloadSandboxFile(result.fileName,bytes,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}catch(failure){setError(failure.message);}finally{setBusy(false);}}
 function choosePerson(person,selected){if(selected&&itemForm.assignees.length>=6){setError('责任人最多选择 6 人');return;}setItemForm(old=>{const remaining=old.assignees.filter(value=>value.personId!==person.id);const assignees=selected?[...remaining,{personId:person.id,organizationUnitId:person.organizationId,personName:person.name,isLead:remaining.length===0,sort:remaining.length}]:remaining.map((value,index)=>({...value,isLead:value.isLead||!remaining.some(other=>other.isLead)&&index===0,sort:index}));return {...old,assignees};});}
 const selectedMonth=validMonth(month);
 return <main className="hct"><div className="hct-head"><h1>慧策通 · 计划督办</h1>{route==='/'&&can('fill')&&<Button onClick={()=>openItem()} disabled={!selectedMonth||!!cycle&&cycle.status!=='drafting'||busy||!!uncertain.current}>新增计划</Button>}</div>
  {error&&<p role="alert" className="hct-alert">{error}</p>}{uncertain.current&&<p role="alert" className="hct-alert">写入结果未知，请核对计划列表；请求编号：{uncertain.current}</p>}
  {!session?<p role="status">正在读取员工授权…</p>:route==='/bindings'?(can('manage')?<>
   <section className="hct-panel"><h2>归口配置</h2><p className="hct-muted">设置业务分类对应的归口人 · {orgName}</p>{categories.filter(row=>row.level===2&&row.enabled).map(category=><div className="hct-row" key={category.id}><div><b>{category.name}</b><small>{bindings.filter(row=>row.category_id===category.id).map(row=>people.find(person=>person.id===row.person_id)?.name??row.person_id).join('、')||'尚无归口人'}</small></div><div className="hct-actions"><Button size="sm" onClick={()=>{setDialog({kind:'binding',categoryId:category.id,personId:''});setPeopleSearch('');}}>增加归口人</Button>{bindings.filter(row=>row.category_id===category.id).map(row=><Button key={row.id} size="sm" variant="secondary" onClick={()=>void runWrite('binding-delete',{id:row.id})}>移除 {people.find(person=>person.id===row.person_id)?.name??row.person_id}</Button>)}</div></div>)}{!categories.some(row=>row.level===2&&row.enabled)&&<p className="hct-muted">请先在分类字典中建立业务分类。</p>}</section>
   <section className="hct-panel"><h2>分类字典</h2><CategoryList categories={categories} search={categorySearch} setSearch={setCategorySearch} statusFilter={categoryStatus} setStatusFilter={setCategoryStatus} loading={busy} error={error} can={can} openCategory={openCategory} toggleCategory={row=>void runWrite('category-upsert',{id:row.id,organizationId,parentId:row.parent_id,level:row.level,name:row.name,sort:row.sort,enabled:!row.enabled,expectedRevision:row.revision})}/></section>
  </>:<p role="alert">没有基础配置权限</p>):<section className="hct-panel"><PlanList cycle={cycle} month={month} setMonth={setMonth} categories={categories} items={items} search={search} setSearch={setSearch} filters={{category:categoryFilter,status:statusFilter}} setFilters={value=>{setCategoryFilter(value.category);setStatusFilter(value.status);}} cursors={cursors} setCursors={setCursors} nextCursor={nextCursor} loading={itemsLoading} statusLabels={statusLabels} can={can} personId={session.personId} openItem={openItem} openProgress={row=>{setProgressStatus('in_progress');setProgressRemark('');setDialog({kind:'progress',row});}} onFunction={value=>{if(value==='preview')setDialog({kind:'preview'});if(value==='export')void exportPlan();}}/></section>}
  <Dialog open={dialog?.kind==='preview'} onClose={()=>setDialog(null)} title={`${orgName} · ${month} 工作计划汇总`} size="xl" footer={<div className="hct-footer"><Button variant="secondary" onClick={()=>setDialog(null)}>关闭</Button><Button onClick={()=>void exportPlan()} disabled={!cycle||busy||!!uncertain.current}>导出 xlsx</Button></div>}>{previewLoading?<p role="status">加载中…</p>:previewItems.length?<div className="hct-scroll"><table className="hct-table"><thead><tr>{columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{previewRows(previewItems).map((row,index)=><tr key={index}>{row.map((cell,column)=><td key={column}>{cell}</td>)}</tr>)}</tbody></table></div>:<p className="hct-muted">该月尚无计划，点击「新增计划」开始提报。</p>}</Dialog>
  <Dialog open={dialog?.kind==='progress'} onClose={()=>!busy&&setDialog(null)} title="更新进度" footer={<div className="hct-footer"><Button variant="secondary" onClick={()=>setDialog(null)}>取消</Button><Button loading={busy} disabled={!progressRemark.trim()||!!uncertain.current} onClick={()=>void runWrite('item-progress',{id:dialog.row.id,expectedVersion:dialog.row.version,status:progressStatus,remark:progressRemark})}>保存进度</Button></div>}><div className="hct-form"><Field label="进度状态"><DropdownSelect value={progressStatus} options={[{value:'in_progress',label:'进行中'},{value:'completed',label:'已完成'},{value:'cancelled',label:'已取消'}]} onChange={setProgressStatus}/></Field><Field className="hct-wide" label="进度备注"><Input maxLength={500} value={progressRemark} onChange={event=>setProgressRemark(event.target.value)} placeholder="填写本次进度说明"/></Field></div></Dialog>
  <Dialog open={dialog?.kind==='binding'} onClose={()=>!busy&&setDialog(null)} title="增加归口人" footer={<div className="hct-footer"><Button variant="secondary" onClick={()=>setDialog(null)}>取消</Button><Button loading={busy} disabled={!dialog?.personId||!!uncertain.current} onClick={()=>void runWrite('binding-upsert',{id:crypto.randomUUID(),organizationId,categoryId:dialog.categoryId,personId:dialog.personId,personOrganizationId:session.organizationId})}>保存</Button></div>}><Field label="归口人（当前工班）"><DropdownSelect value={dialog?.personId??''} options={people.map(person=>({value:person.id,label:person.name}))} onChange={personId=>setDialog(old=>({...old,personId}))}/></Field></Dialog>
  <Dialog open={dialog?.kind==='category'} onClose={()=>!busy&&setDialog(null)} title={categoryForm.id?'编辑分类':'新增分类'} footer={<div className="hct-footer"><Button variant="secondary" onClick={()=>setDialog(null)}>取消</Button><Button loading={busy} disabled={!!uncertain.current} onClick={()=>void saveCategory()}>保存</Button></div>}><div className="hct-form"><Field label="层级"><DropdownSelect value={String(categoryForm.level)} options={[1,2,3].map(level=>({value:String(level),label:level+' 级'}))} onChange={value=>setCategoryForm(old=>({...old,level:Number(value),parentId:null}))} disabled={!!categoryForm.id}/></Field>{categoryForm.level>1&&<Field label="上级分类"><OrganizationPicker label="上级分类" value={categoryForm.parentId??''} options={categoryOptions} selectable={option=>categories.find(row=>row.id===option.id)?.level===categoryForm.level-1} onChange={value=>setCategoryForm(old=>({...old,parentId:value}))} disabled={!!categoryForm.id} required/></Field>}<Field label="名称"><Input value={categoryForm.name} onChange={event=>setCategoryForm(old=>({...old,name:event.target.value}))}/></Field><Field label="排序"><Input type="number" min="0" max="10000" value={categoryForm.sort} onChange={event=>setCategoryForm(old=>({...old,sort:event.target.value}))}/></Field><Field label="状态"><DropdownSelect value={categoryForm.enabled?'enabled':'disabled'} options={[{value:'enabled',label:'启用'},{value:'disabled',label:'停用'}]} onChange={value=>setCategoryForm(old=>({...old,enabled:value==='enabled'}))}/></Field></div><p className="hct-muted">停用分类相当于移出可选字典，已有计划保留历史分类。</p></Dialog>
  <Dialog open={dialog?.kind==='item'} onClose={()=>!busy&&setDialog(null)} title={dialog?.row?'编辑计划':'新增计划'} size="xl" footer={<div className="hct-footer"><Button variant="secondary" onClick={()=>setDialog(null)}>取消</Button><Button loading={busy} disabled={!!uncertain.current} onClick={()=>void saveItem()}>保存计划</Button></div>}><div className="hct-form"><Field label="业务模块"><OrganizationPicker label="业务模块" value={itemForm.categoryId} options={categoryOptions} selectable={option=>categories.find(row=>row.id===option.id)?.level===3} onChange={value=>setItemForm(old=>({...old,categoryId:value}))} required/></Field><Field label="拟提报中心"><DropdownSelect value={itemForm.escalated?'yes':'no'} options={[{value:'no',label:'否'},{value:'yes',label:'是'}]} onChange={value=>setItemForm(old=>({...old,escalated:value==='yes'}))}/></Field><Field className="hct-wide" label="工作计划内容"><textarea className="afc-control" maxLength={500} value={itemForm.content} onChange={event=>setItemForm(old=>({...old,content:event.target.value}))}/></Field><Field className="hct-wide" label="完成质量标准"><textarea className="afc-control" maxLength={500} value={itemForm.qualityStandard} onChange={event=>setItemForm(old=>({...old,qualityStandard:event.target.value}))}/></Field><Field label="开始日期"><Input type="date" value={itemForm.startDate} onChange={event=>setItemForm(old=>({...old,startDate:event.target.value}))}/></Field><Field label="完成日期"><Input type="date" value={itemForm.endDate} onChange={event=>setItemForm(old=>({...old,endDate:event.target.value}))}/></Field><Field className="hct-wide" label="备注"><Input maxLength={500} value={itemForm.remark} onChange={event=>setItemForm(old=>({...old,remark:event.target.value}))}/></Field><div className="hct-wide hct-people-picker"><b>责任人（最多 6 人）</b><OrganizationPeoplePicker organizations={[{id:session?.organizationId??'',name:session?.organizations.find(value=>value.id===session.organizationId)?.name??'当前工班',parentId:null}]} people={people.map(person=>({id:person.id,name:person.name,employeeNo:person.employeeNo,organizationId:person.organizationUnitId}))} organizationId={session?.organizationId??''} onOrganizationChange={()=>{}} search={peopleSearch} onSearchChange={value=>setPeopleSearch(value.slice(0,100))} page={1} hasNext={false} onPageChange={()=>{}} selected={person=>itemForm.assignees.some(value=>value.personId===person.id)} onPersonChange={choosePerson} loading={peopleLoading}/></div><Field className="hct-wide" label="牵头人"><DropdownSelect value={itemForm.assignees.find(value=>value.isLead)?.personId??''} options={itemForm.assignees.map(value=>({value:value.personId,label:value.personName??people.find(person=>person.id===value.personId)?.name??value.personId}))} onChange={personId=>setItemForm(old=>({...old,assignees:old.assignees.map(value=>({...value,isLead:value.personId===personId}))}))}/></Field></div></Dialog>
 </main>;
}
createRoot(document.getElementById('app')).render(<App/>);
window.addEventListener('pagehide',()=>sandbox.close(),{once:true});
