import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as XLSX from 'xlsx';
import {Button,Input,Field,Dialog,QueryList,TableHeader,TableBody,TableRow,TableHead,TableCell,TableActions,TableActionButton,ListPagination,SearchSelect,DropdownSelect,Plus,PencilSimpleLine,Trash,ArrowLineDown,ArrowLineUp} from '@metro/platform-sdk/ui';
import {platformUiCss} from '@metro/platform-sdk/ui-styles';
import {createAppSandboxClient,createAppApiClient} from '@metro/platform-sdk/app-sandbox';

const script=document.currentScript,origin=script?.dataset.platformOrigin;
if(!origin)throw Error('PLATFORM_ORIGIN_REQUIRED');
document.documentElement.classList.add('afc-theme-neutral');
const style=document.createElement('style');style.nonce=script?.nonce??'';style.textContent=platformUiCss+`
body{margin:0;background:var(--afc-color-canvas,#fafafa);color:var(--afc-color-ink,#18181b);font-family:var(--afc-font-ui,system-ui)}
*{box-sizing:border-box}.maintenance{padding:24px;max-width:1200px;margin:auto}.maintenance h1{font-size:22px;margin:0}.maintenance-sub{font-size:13px;color:var(--afc-color-muted);margin:4px 0 18px}.maintenance-error{padding:10px 12px;background:#fff1f2;color:#991b1b;border-radius:8px;margin:10px 0}.maintenance-note{font-size:13px;color:var(--afc-color-muted);margin:8px 0}.maintenance-cell{max-width:260px;white-space:normal;overflow-wrap:anywhere}.maintenance-cell small{display:block;color:var(--afc-color-muted)}.maintenance-progress{width:96px;height:5px;background:var(--afc-color-neutral-soft,#eee);border-radius:5px;overflow:hidden;margin-top:6px}.maintenance-progress span{display:block;height:100%;background:var(--afc-color-ink,#18181b)}.maintenance-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.maintenance-wide{grid-column:1/-1}.maintenance-form textarea{width:100%}.maintenance-items{display:grid;gap:12px}.maintenance-item{border:1px solid var(--afc-color-border,#ddd);border-radius:10px;padding:14px}.maintenance-item h3{margin:0 0 10px;font-size:14px}.maintenance-item-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.maintenance-item-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:12px}.maintenance-footer{display:flex;gap:8px;justify-content:flex-end}.maintenance-batch{display:flex;gap:8px;margin:8px 0}.maintenance-batch .afc-control{flex:1;min-width:0}.maintenance-batch .afc-button{flex:none}.maintenance-import{width:100%;max-height:220px;overflow:auto}.maintenance-file{display:none}@media(max-width:700px){.maintenance{padding:12px}.maintenance-form,.maintenance-item-grid{grid-template-columns:1fr}.maintenance-wide{grid-column:1}.maintenance-footer{flex-wrap:wrap}}
`;document.head.append(style);
const sandbox=createAppSandboxClient({appId:'maintenance',platformOrigin:origin,port:{parent:window.parent,send:(data,target)=>window.parent.postMessage(data,target),listen:listener=>{window.addEventListener('message',listener);return()=>window.removeEventListener('message',listener);}}});
const api=createAppApiClient(sandbox);
const messages={INVALID_INPUT:'请检查计划、设备与派工内容',PLAN_TOO_LARGE:'这组计划内容过多，请拆成多组计划后保存',ACCESS_DENIED:'没有此操作权限',INVALID_PERSON:'作业人已不在所选工班',INVALID_STATION:'车站信息已变化，请重新选择',CONFLICT:'计划已被修改，请刷新后重试',COMPLETED_PROTECTED:'已完成的设备不能删除或改回待执行',EMPLOYEE_REQUIRED:'员工身份不可用'};
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const blank=(org='')=>({organizationId:org,scheduledDate:today(),stationId:null,stationName:'',deviceTypeName:'',content:'',items:[{deviceNumber:'',operatorId:null,operatorName:'',secondaryOperatorId:null,secondaryOperatorName:'',operatorShare:0.5,status:'pending'}]});
const fromRow=row=>({organizationId:row.organization_id,scheduledDate:row.scheduled_date,stationId:row.station_id,stationName:row.station_name,deviceTypeName:row.device_type_name,content:row.content,items:row.items.map(item=>({id:item.id,deviceNumber:item.deviceNumber,operatorId:item.operatorId,operatorName:item.operatorName,secondaryOperatorId:item.secondaryOperatorId,secondaryOperatorName:item.secondaryOperatorName,operatorShare:item.operatorShare??0.5,status:item.status}))});
const safe=value=>typeof value==='string'&&/^[=+@-]/.test(value)?"'"+value:value??'';
const splitDevices=value=>String(value).split(/[\/\\,，、;；\s]+/).map(part=>part.trim()).filter(Boolean);
const normalizeDate=value=>{if(typeof value==='number')return String(XLSX.SSF.format('yyyy-mm-dd',value));const match=String(value??'').trim().replace(/[./年]/g,'-').replace(/月/g,'-').replace(/日/g,'').match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);return match?`${match[1]}-${match[2].padStart(2,'0')}-${match[3].padStart(2,'0')}`:'';};
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(value+'T00:00:00Z'))&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;

function App(){
 const [session,setSession]=useState(null),[rows,setRows]=useState([]),[next,setNext]=useState(null),[cursors,setCursors]=useState([null]),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[dialog,setDialog]=useState(null),[form,setForm]=useState(blank()),[catalog,setCatalog]=useState({people:[],stations:[],assets:[]}),[terms,setTerms]=useState({person:'',station:'',asset:''}),[assetMode,setAssetMode]=useState('type'),[batchDevices,setBatchDevices]=useState(''),[importRows,setImportRows]=useState([]),[importProgress,setImportProgress]=useState(0),[monthRange,setMonthRange]=useState({from:today().slice(0,7),to:today().slice(0,7)}),[reload,setReload]=useState(0);
 const [filters,setFilters]=useState({status:'pending',organizationId:'',stationName:'',sort:'asc',dateFrom:'',dateTo:'',search:''});
 const fileInput=useRef(null),listRequest=useRef(0),catalogRequest=useRef(0),writing=useRef(false),uncertain=useRef(null);
 const can=name=>session?.permissions.includes(`app.maintenance.${name}`);
 const cursor=cursors.at(-1),orgs=session?.organizations??[];
 async function call(name,payload,write=false){
  if(write&&(writing.current||uncertain.current))throw Error(uncertain.current?`写入 ${uncertain.current} 的结果待核对，请勿重复提交`:'正在保存，请稍候');
  if(write)writing.current=true;
  try{const response=await api.invoke(name,payload);if(!response.ok){const code=response.error?.code,definitive=response.error?.writeOutcome==='not_started';if(write&&!definitive)uncertain.current=payload.requestId;const ex=Error(messages[code]??(write?'写入结果未确认，请核对记录':'读取失败，请重试'));ex.definitive=definitive;throw ex;}return response.result;}
  catch(error){if(write&&!error.definitive)uncertain.current=payload.requestId;throw error;}
  finally{if(write)writing.current=false;}
 }
 useEffect(()=>{let alive=true;const timer=setInterval(async()=>{if(!sandbox.ready())return;clearInterval(timer);try{const result=await call('session',{});if(alive){setSession(result);setFilters(value=>({...value,organizationId:result.organizationId}));}}catch(error){if(alive)setError(error.message);}},25);return()=>{alive=false;clearInterval(timer);};},[]);
 useEffect(()=>{if(!session)return;void sandbox.invoke('platform.ui.theme',{}).then(value=>{if(['light','dark'].includes(value.theme))document.documentElement.dataset.theme=value.theme;}).catch(()=>{});},[session]);
 useEffect(()=>{if(!session)return;void sandbox.invoke('platform.ui.modal',{open:!!dialog}).catch(()=>{});},[session,!!dialog]);
 async function load(){if(!session)return;const token=++listRequest.current;setBusy(true);setError('');try{const result=await call('list',{...filters,pageSize:20,...(cursor?{after:cursor}:{})});if(token===listRequest.current){setRows(result.rows);setNext(result.nextCursor??null);}}catch(error){if(token===listRequest.current)setError(error.message);}finally{if(token===listRequest.current)setBusy(false);}}
 useEffect(()=>{void load();},[session,filters,cursor,reload]);
 useEffect(()=>{if(!session)return;const org=dialog?.kind==='create'||dialog?.kind==='edit'?form.organizationId:filters.organizationId||session.organizationId;if(!org)return;const token=++catalogRequest.current;const timer=setTimeout(async()=>{try{const result=await call('catalog',{organizationId:org,...(terms.person?{personSearch:terms.person}:{}),...(terms.station?{stationSearch:terms.station}:{}),...(terms.asset?{assetSearch:terms.asset}:{}),...(dialog&&assetMode==='number'&&form.stationId?{stationId:form.stationId}:{}),...(dialog&&assetMode==='number'&&form.deviceTypeName?{assetTypeName:form.deviceTypeName}:{})});if(token===catalogRequest.current)setCatalog(result);}catch(error){if(token===catalogRequest.current)setError(error.message);}},180);return()=>clearTimeout(timer);},[session,filters.organizationId,dialog?.kind,form.organizationId,form.stationId,form.deviceTypeName,terms,assetMode]);
 function filter(name,value){setCursors([null]);setFilters(current=>({...current,[name]:value}));}
 const groups=useMemo(()=>[{id:'status',title:'计划状态',options:[{id:'pending',label:'待执行'},{id:'completed',label:'已完成'},{id:'all',label:'全部'}],isMulti:false,allowAll:false},{id:'organization',title:'工班',options:orgs.map(item=>({id:item.id,label:item.name})),isMulti:false},{id:'station',title:'车站',options:catalog.stations.map(item=>({id:item.name,label:item.name})),isMulti:false},{id:'sort',title:'计划日期',options:[{id:'asc',label:'最早在前'},{id:'desc',label:'最新在前'}],isMulti:false,allowAll:false}],[orgs,catalog.stations]);
 const active=useMemo(()=>({startDate:filters.dateFrom,endDate:filters.dateTo,selectedOptions:{status:[filters.status],organization:filters.organizationId?[filters.organizationId]:[],station:filters.stationName?[filters.stationName]:[],sort:[filters.sort]}}),[filters]);
 function apply(value){setCursors([null]);setFilters(current=>({...current,dateFrom:value.startDate||'',dateTo:value.endDate||'',status:value.selectedOptions.status?.[0]||'all',organizationId:value.selectedOptions.organization?.[0]||'',stationName:value.selectedOptions.station?.[0]||'',sort:value.selectedOptions.sort?.[0]||'asc'}));}
 function reset(){setCursors([null]);setFilters(current=>({...current,dateFrom:'',dateTo:'',status:'all',organizationId:'',stationName:'',sort:'asc'}));}
 function open(kind,row=null){setError('');setTerms({person:'',station:'',asset:''});setForm(row?fromRow(row):blank(filters.organizationId||session.organizationId));setDialog({kind,row});}
 function close(){if(saving)return;setDialog(null);setTerms({person:'',station:'',asset:''});setError('');}
 function change(name,value){setForm(current=>({...current,[name]:value}));}
 function changeItem(index,patch){setForm(current=>({...current,items:current.items.map((item,i)=>i===index?{...item,...patch}:item)}));}
 function addDevices(){const numbers=splitDevices(batchDevices).slice(0,100);if(!numbers.length)return;setForm(current=>({...current,items:[...current.items.filter(item=>item.deviceNumber||item.operatorId),...numbers.map(deviceNumber=>({deviceNumber,operatorId:null,operatorName:'',secondaryOperatorId:null,secondaryOperatorName:'',operatorShare:0.5,status:'pending'}))].slice(0,100)}));setBatchDevices('');}
 async function save(){if(!dialog||saving)return;setError('');if(!validDate(form.scheduledDate)||!form.stationName.trim()||!form.deviceTypeName.trim()||!form.items.length||form.items.some(item=>!item.deviceNumber.trim()||item.status==='completed'&&!item.operatorId)){setError('请填写日期、车站、设备类型及编号；完成设备需指定主作业人');return;}const requestId=crypto.randomUUID();setSaving(true);try{await call(dialog.kind==='edit'?'update':'create',{requestId,id:dialog.row?.id??crypto.randomUUID(),...(dialog.row?{revision:dialog.row.revision}:{}),plan:form},true);setDialog(null);setReload(value=>value+1);}catch(error){setError(`${error.message}${uncertain.current?`（请求编号：${uncertain.current}）`:''}`);}finally{setSaving(false);}}
 async function remove(){if(!dialog?.row||saving)return;setSaving(true);setError('');const requestId=crypto.randomUUID();try{await call('delete',{requestId,id:dialog.row.id,revision:dialog.row.revision},true);setDialog(null);setReload(value=>value+1);}catch(error){setError(`${error.message}${uncertain.current?`（请求编号：${uncertain.current}）`:''}`);}finally{setSaving(false);}}
 function downloadTemplate(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{日期:today(),车站:'示例站',设备类型:'TVM',设备编号:'01/02',检修内容:'季度检修'}]),'检修计划');XLSX.writeFile(wb,'检修计划导入模板.xlsx');}
 async function parseImport(file){if(!file)return;if(file.size>2_000_000){setError('导入文件不能超过 2 MB');return;}setError('');try{const book=XLSX.read(await file.arrayBuffer(),{type:'array'}),sheet=book.Sheets[book.SheetNames[0]],raw=XLSX.utils.sheet_to_json(sheet,{defval:''});if(!raw.length||raw.length>200)throw Error('导入文件需包含 1–200 行计划');const parsed=raw.map((row,index)=>{const entry=Object.fromEntries(Object.entries(row).map(([key,value])=>[key.replace(/\s|[（(].*?[）)]/g,''),value]));const scheduledDate=normalizeDate(entry['日期']??entry['计划日期']??entry['检修日期']),stationName=String(entry['车站']??entry['站点']??'').trim(),deviceTypeName=String(entry['设备类型']??entry['类型']??'').trim(),deviceNumbers=splitDevices(entry['设备编号']??entry['设备号']??'');if(!validDate(scheduledDate)||!stationName||!deviceTypeName||!deviceNumbers.length||deviceNumbers.length>100)throw Error(`第 ${index+2} 行日期、车站、类型或设备编号不完整`);return {organizationId:filters.organizationId||session.organizationId,scheduledDate,stationId:null,stationName,deviceTypeName,content:String(entry['检修内容']??entry['内容']??'').slice(0,500),items:deviceNumbers.map(deviceNumber=>({deviceNumber,operatorId:null,secondaryOperatorId:null,status:'pending'}))};});setImportRows(parsed);setImportProgress(0);setDialog({kind:'import'});}catch(error){setError(error.message);}finally{fileInput.current.value='';}}
 async function importPlans(){if(saving)return;setSaving(true);setError('');let completed=importProgress;try{for(let i=completed;i<importRows.length;i++){await call('create',{requestId:crypto.randomUUID(),id:crypto.randomUUID(),plan:importRows[i]},true);completed=i+1;setImportProgress(completed);}setDialog(null);setImportRows([]);setReload(value=>value+1);}catch(error){setError(`${error.message}；已导入 ${completed} 组。请核对列表后再处理剩余行${uncertain.current?`（请求编号：${uncertain.current}）`:''}`);}finally{setSaving(false);}}
 async function exportPlans(){if(saving)return;const from=monthRange.from,to=monthRange.to;if(!/^\d{4}-\d{2}$/.test(from)||!/^\d{4}-\d{2}$/.test(to)||from>to){setError('请选择正确的月份范围');return;}setSaving(true);setError('');try{const dateFrom=from+'-01',dateTo=new Date(Number(to.slice(0,4)),Number(to.slice(5,7)),0).toLocaleDateString('sv-SE'),all=[];let after;do{const result=await call('export',{dateFrom,dateTo,sort:'asc',pageSize:50,...(filters.organizationId?{organizationId:filters.organizationId}:{}),...(after?{after}:{})});all.push(...result.rows);after=result.nextCursor;if(all.reduce((n,row)=>n+row.items.length,0)>5000)throw Error('超过 5000 台设备，请缩短月份范围');}while(after);if(!all.length)throw Error('所选月份没有可导出的检修记录');const flat=all.flatMap(row=>row.items.map(item=>({计划日期:row.scheduled_date,工班:orgs.find(org=>org.id===row.organization_id)?.name??'',车站:safe(row.station_name),设备类型:safe(row.device_type_name),设备编号:safe(item.deviceNumber),检修内容:safe(row.content),主作业人:safe(item.operatorName),副作业人:safe(item.secondaryOperatorName),主作业占比:item.operatorShare??'',状态:item.status==='completed'?'已完成':'待执行',完成时间:item.completedAt?.replace('T',' ').slice(0,19)??''})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(flat),'检修完成情况');XLSX.writeFile(wb,`检修完成情况_${from}_${to}.xlsx`);setDialog(null);}catch(error){setError(error.message);}finally{setSaving(false);}}
 const typeOptions=[...new Set(catalog.assets.map(item=>item.typeName).filter(Boolean))].map(name=>({id:name,label:name}));
 const assetOptions=catalog.assets.filter(item=>!form.stationId||item.locationId===form.stationId).map(item=>({id:item.id,label:item.assetCode||item.displayName,detail:item.displayName,typeName:item.typeName}));
 return <main className="maintenance"><h1>检修管理</h1><p className="maintenance-sub">设备检修计划、派工与完成情况</p>{error&&<p role="alert" className="maintenance-error">{error}</p>}{uncertain.current&&<p role="alert" className="maintenance-error">有写入结果待核对（请求编号：{uncertain.current}），当前页面已停止新的写入。</p>}
  <QueryList query={{searchValue:filters.search,onSearchChange:value=>filter('search',value),searchPlaceholder:'搜索计划、设备、车站或作业人',filterGroups:groups,activeFilters:active,onApplyFilters:apply,onResetFilters:reset,moreActions:[...(can('export')?[{id:'export',label:'按月份导出',icon:<ArrowLineDown size={17}/>,onClick:()=>open('export')}]:[]),...(can('create')?[{id:'template',label:'下载导入模板',onClick:downloadTemplate},{id:'import',label:'批量导入计划',icon:<ArrowLineUp size={17}/>,onClick:()=>fileInput.current?.click()}]:[])]}} actions={can('create')?<Button size="sm" leadingIcon={<Plus size={16}/>} onClick={()=>open('create')}>新增计划</Button>:null} emptyState={rows.length?undefined:busy?'加载中…':'暂无符合条件的检修计划'} pagination={<ListPagination page={cursors.length} hasNext={!!next} busy={busy} onPrevious={()=>setCursors(value=>value.slice(0,-1))} onNext={()=>setCursors(value=>[...value,next])}/> }>
   <TableHeader><TableRow>{['计划与设备','车站','计划日期','作业人员','完成进度','操作'].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(row=>{const done=row.items.filter(item=>item.status==='completed').length;return <TableRow key={row.id}><TableCell className="maintenance-cell"><b>{row.device_type_name} · {row.items.length} 台</b><small>{row.content||row.items.map(item=>item.deviceNumber).join('、')}</small></TableCell><TableCell>{row.station_name}</TableCell><TableCell>{row.scheduled_date}</TableCell><TableCell className="maintenance-cell">{[...new Set(row.items.flatMap(item=>[item.operatorName,item.secondaryOperatorName]).filter(Boolean))].join('、')||'待派工'}</TableCell><TableCell>{done}/{row.items.length}<div className="maintenance-progress"><span style={{width:`${done/row.items.length*100}%`}}/></div></TableCell><TableCell><TableActions><TableActionButton onClick={()=>open('view',row)}>查看</TableActionButton>{can('update')&&<TableActionButton icon={<PencilSimpleLine size={16}/>} onClick={()=>open('edit',row)}>编辑</TableActionButton>}{can('delete')&&!done&&<TableActionButton icon={<Trash size={16}/>} onClick={()=>open('delete',row)}>作废</TableActionButton>}</TableActions></TableCell></TableRow>;})}</TableBody>
  </QueryList>
  <input ref={fileInput} className="maintenance-file" type="file" accept=".xlsx,.xls,.csv" onChange={event=>void parseImport(event.target.files?.[0])}/>
  <Dialog open={['create','edit','view'].includes(dialog?.kind)} onClose={close} title={dialog?.kind==='create'?'新增检修计划':dialog?.kind==='edit'?'编辑检修计划':'检修计划详情'} description="计划与逐台设备派工" size="xl" footer={<div className="maintenance-footer"><Button variant="secondary" onClick={close}>关闭</Button>{dialog?.kind!=='view'&&<Button loading={saving} disabled={!!uncertain.current} onClick={()=>void save()}>保存计划</Button>}</div>}>
   {error&&<p role="alert" className="maintenance-error">{error}</p>}<div className="maintenance-form">
    {orgs.length>1&&<Field label="所属工班" htmlFor="maintenance-org"><DropdownSelect id="maintenance-org" value={form.organizationId} options={orgs.map(item=>({value:item.id,label:item.name}))} onChange={value=>setForm(current=>({...current,organizationId:value,stationId:null,stationName:'',items:current.items.map(item=>({...item,operatorId:null,operatorName:'',secondaryOperatorId:null,secondaryOperatorName:''}))}))} disabled={dialog?.kind!=='create'}/></Field>}
    <Field label="计划日期" htmlFor="maintenance-date" required><Input id="maintenance-date" type="date" value={form.scheduledDate} onChange={event=>change('scheduledDate',event.target.value)} disabled={dialog?.kind==='view'}/></Field>
    <Field label="车站" htmlFor="maintenance-station" required><SearchSelect id="maintenance-station" value={form.stationName} options={catalog.stations.map(item=>({id:item.id,label:item.name}))} placeholder="搜索或输入车站" disabled={dialog?.kind==='view'} onSearch={value=>setTerms(current=>({...current,station:value}))} onInput={value=>setForm(current=>({...current,stationId:null,stationName:value}))} onSelect={item=>setForm(current=>({...current,stationId:item.id,stationName:item.label}))}/></Field>
    <Field label="设备类型" htmlFor="maintenance-type" required><SearchSelect id="maintenance-type" value={form.deviceTypeName} options={typeOptions} placeholder="搜索或输入设备类型" disabled={dialog?.kind==='view'} onSearch={value=>{setAssetMode('type');setTerms(current=>({...current,asset:value}));}} onInput={value=>change('deviceTypeName',value)} onSelect={item=>change('deviceTypeName',item.label)}/></Field>
    <Field className="maintenance-wide" label="检修内容" htmlFor="maintenance-content"><textarea className="afc-control afc-control--textarea" id="maintenance-content" maxLength={500} value={form.content} onChange={event=>change('content',event.target.value)} disabled={dialog?.kind==='view'} rows={2}/></Field>
    <div className="maintenance-wide"><div className="maintenance-footer" style={{justifyContent:'space-between',alignItems:'center'}}><b>设备派工 · {form.items.length} 台</b></div>{dialog?.kind!=='view'&&<div className="maintenance-batch"><Input aria-label="批量设备编号" placeholder="批量粘贴编号，如 01/02/03" value={batchDevices} onChange={event=>setBatchDevices(event.target.value)}/><Button size="xs" variant="secondary" disabled={!batchDevices.trim()} onClick={addDevices}>批量加设备</Button></div>}<div className="maintenance-items">{form.items.map((item,index)=><section className="maintenance-item" key={item.id??index}><h3>设备 {index+1}{item.status==='completed'?' · 已完成':''}</h3><div className="maintenance-item-grid">
      <Field label="设备编号" htmlFor={`maintenance-device-${index}`} required><SearchSelect id={`maintenance-device-${index}`} value={item.deviceNumber} options={assetOptions} placeholder="搜索或输入设备编号" disabled={dialog?.kind==='view'} onSearch={value=>{setAssetMode('number');setTerms(current=>({...current,asset:value}));}} onInput={value=>changeItem(index,{deviceNumber:value})} onSelect={option=>{changeItem(index,{deviceNumber:option.label});if(option.typeName)change('deviceTypeName',option.typeName);}}/></Field>
      <Field label="状态" htmlFor={`maintenance-status-${index}`}><DropdownSelect value={item.status} options={[{value:'pending',label:'待执行'},{value:'completed',label:'已完成'}]} onChange={value=>changeItem(index,{status:value})} disabled={dialog?.kind==='view'||dialog?.row?.items.find(old=>old.id===item.id)?.status==='completed'}/></Field>
      <Field label="主作业人" htmlFor={`maintenance-main-${index}`} required={item.status==='completed'}><SearchSelect id={`maintenance-main-${index}`} value={item.operatorName||''} options={catalog.people.map(person=>({id:person.id,label:person.name,detail:person.employeeNo}))} placeholder="搜索工班人员" allowCustom={false} disabled={dialog?.kind==='view'} onSearch={value=>setTerms(current=>({...current,person:value}))} onInput={value=>changeItem(index,{operatorId:null,operatorName:value})} onSelect={person=>changeItem(index,{operatorId:person.id,operatorName:person.label})}/></Field>
      <Field label="副作业人" htmlFor={`maintenance-secondary-${index}`}><SearchSelect id={`maintenance-secondary-${index}`} value={item.secondaryOperatorName||''} options={catalog.people.map(person=>({id:person.id,label:person.name,detail:person.employeeNo}))} placeholder="选填" allowCustom={false} disabled={dialog?.kind==='view'} onSearch={value=>setTerms(current=>({...current,person:value}))} onInput={value=>changeItem(index,{secondaryOperatorId:null,secondaryOperatorName:value})} onSelect={person=>changeItem(index,{secondaryOperatorId:person.id,secondaryOperatorName:person.label})}/></Field>
      {item.secondaryOperatorId&&<Field label="主作业占比" htmlFor={`maintenance-share-${index}`}><Input id={`maintenance-share-${index}`} type="number" min="0.05" max="0.95" step="0.05" value={item.operatorShare??0.5} onChange={event=>changeItem(index,{operatorShare:Number(event.target.value)})} disabled={dialog?.kind==='view'}/></Field>}
     </div>{dialog?.kind!=='view'&&form.items.length>1&&dialog?.row?.items.find(old=>old.id===item.id)?.status!=='completed'&&<div className="maintenance-item-actions"><Button size="xs" variant="ghost" onClick={()=>setForm(current=>({...current,items:current.items.filter((_,i)=>i!==index)}))}>移除设备</Button></div>}</section>)}</div><Button size="sm" variant="secondary" leadingIcon={<Plus size={15}/>} onClick={()=>setForm(current=>({...current,items:[...current.items,{deviceNumber:'',operatorId:null,operatorName:'',secondaryOperatorId:null,secondaryOperatorName:'',operatorShare:0.5,status:'pending'}]}))} disabled={dialog?.kind==='view'||form.items.length>=100}>添加一台设备</Button></div>
   </div>
  </Dialog>
  <Dialog open={dialog?.kind==='delete'} onClose={close} title="作废检修计划" footer={<div className="maintenance-footer"><Button variant="secondary" onClick={close}>取消</Button><Button variant="danger" loading={saving} disabled={!!uncertain.current} onClick={()=>void remove()}>确认作废</Button></div>}>{error&&<p role="alert" className="maintenance-error">{error}</p>}<p>作废 {dialog?.row?.scheduled_date} · {dialog?.row?.station_name} 的计划？记录会保留审计信息，并从列表中隐藏。</p></Dialog>
  <Dialog open={dialog?.kind==='import'} onClose={close} title="批量导入检修计划" description="请核对日期、车站、类型和设备编号" footer={<div className="maintenance-footer"><Button variant="secondary" onClick={close}>关闭</Button><Button loading={saving} disabled={!!uncertain.current||!importRows.length} onClick={()=>void importPlans()}>导入 {importRows.length} 组</Button></div>}>{error&&<p role="alert" className="maintenance-error">{error}</p>}<p className="maintenance-note">导入后均为待执行，车站与设备类型按原文保存。已完成 {importProgress}/{importRows.length} 组。</p><div className="maintenance-import"><ul>{importRows.map((row,i)=><li key={i}>{row.scheduledDate} · {row.stationName} · {row.deviceTypeName} · {row.items.map(item=>item.deviceNumber).join('、')}</li>)}</ul></div></Dialog>
  <Dialog open={dialog?.kind==='export'} onClose={close} title="按月份导出检修完成情况" footer={<div className="maintenance-footer"><Button variant="secondary" onClick={close}>取消</Button><Button loading={saving} onClick={()=>void exportPlans()}>导出 Excel</Button></div>}>{error&&<p role="alert" className="maintenance-error">{error}</p>}<div className="maintenance-form"><Field label="起始月份" htmlFor="maintenance-from"><Input id="maintenance-from" type="month" value={monthRange.from} onChange={event=>setMonthRange(current=>({...current,from:event.target.value}))}/></Field><Field label="结束月份" htmlFor="maintenance-to"><Input id="maintenance-to" type="month" value={monthRange.to} onChange={event=>setMonthRange(current=>({...current,to:event.target.value}))}/></Field></div><p className="maintenance-note">包含授权范围内的已完成和待执行设备，单次最多 5000 台。</p></Dialog>
 </main>;
}
createRoot(document.getElementById('app')).render(<App/>);
window.addEventListener('pagehide',()=>sandbox.close(),{once:true});
