import {PencilSimpleLine,Pause,Play,Plus} from '@phosphor-icons/react';
import {useLocation,Navigate} from 'react-router-dom';
import {Button,Input,Select,Switch,DataList,TableActionButton,FilterBar,type FilterState} from '../../components/ui';
import React,{useEffect,useState} from 'react';
import {AdminDialog} from './AdminShell';
import {adminRequest} from './client';
type RecordRow=Record<string,unknown>;
type Field={key:string;label:string;type:string;required:boolean;options?:string[];resource?:string};
type Resource={key:string;label:string;fields:Field[];columns:string[];updateFields:string[];writable:boolean;reason?:string};
function useLoad<T>(path:string){const [value,setValue]=useState<T|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);useEffect(()=>{const abort=new AbortController();setValue(null);setError('');adminRequest<T>(path,{signal:abort.signal}).then(setValue).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'读取失败');});return()=>abort.abort();},[path,revision]);return {value,error,reload:()=>setRevision(v=>v+1)};}
function Failure({error}:{error:string}){return error?<p role="alert" className="afc-error">{error}</p>:null;}
const optionLabels:Record<string,string>={active:'启用',inactive:'停用',departed:'离职',company:'公司',center:'中心',operations_center:'运营中心',station_organization:'车站组织',department:'部室',workgroup:'工班',station_area:'站区',station:'车站'};
const text=(value:unknown)=>value===null||value===undefined?'—':typeof value==='object'?JSON.stringify(value):String(value);
function DataEditor({resource,row,onClose,onSaved}:{resource:Resource;row:RecordRow|null;onClose:()=>void;onSaved:()=>void}){
 const fields=resource.fields.filter(f=>!row||resource.updateFields.includes(f.key));
 const [draft,setDraft]=useState<Record<string,string>>(()=>Object.fromEntries(fields.map(f=>[f.key,row?.[f.key]==null?(f.key==='status'?'active':''):String(row[f.key])]))),[references,setReferences]=useState<Record<string,RecordRow[]>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();Promise.all([...new Set(fields.flatMap(f=>f.resource?[f.resource]:[]))].map(async key=>[key,(await adminRequest<{records:RecordRow[]}>(`/data/${key}`,{signal:abort.signal})).records] as const)).then(rows=>setReferences(Object.fromEntries(rows))).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[resource.key]);
 async function save(event:React.FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const body=Object.fromEntries(fields.filter(f=>row?draft[f.key]!==String(row[f.key]??''):draft[f.key]!==''||f.required).map(f=>[f.key,draft[f.key]===''?null:f.type==='number'?Number(draft[f.key]):draft[f.key]]));if(row&&!Object.keys(body).length){onClose();return;}await adminRequest(`/data/${resource.key}${row?`/${encodeURIComponent(String(row.id))}`:''}`,{method:row?'PATCH':'POST',body});onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:'保存未确认，请刷新核对。');}finally{setBusy(false);}}
 return <AdminDialog title={`${row?'编辑':'新增'}${resource.label}`} onClose={()=>{if(!busy)onClose();}}><form className="admin-form" onSubmit={save}>{fields.map(f=>f.key==='status'?<Switch key={f.key} label="启用" checked={draft[f.key]==='active'} disabled={busy} onChange={e=>setDraft({...draft,[f.key]:e.target.checked?'active':'inactive'})}/>:<label key={f.key}>{f.label}{f.required?' *':''}{f.type==='reference'||f.type==='select'?<Select required={f.required} disabled={busy} value={draft[f.key]} onChange={e=>setDraft({...draft,[f.key]:e.target.value})}><option value="">请选择</option>{f.resource?(references[f.resource]??[]).filter(r=>(f.resource!==resource.key||r.id!==row?.id)&&(r.status!=='inactive'||r.id===draft[f.key])).map(r=><option value={String(r.id)} key={String(r.id)}>{text(r.name??r.displayName??r.code)}</option>):f.options?.map(value=><option key={value} value={value}>{optionLabels[value]??value}</option>)}</Select>:<Input required={f.required} maxLength={200} type={f.type==='number'?'number':'text'} disabled={busy} value={draft[f.key]} onChange={e=>setDraft({...draft,[f.key]:e.target.value})}/>}</label>)}<Failure error={error}/><Button variant="primary" type="submit" disabled={busy}>{busy?'保存中…':'保存'}</Button></form></AdminDialog>;
}
function Directory({resource}:{resource:Resource}){
 const [search,setSearch]=useState(''),[filters,setFilters]=useState<FilterState>({selectedOptions:{}}),[editing,setEditing]=useState<{row:RecordRow|null}|null>(null);
 const [referenceNames,setReferenceNames]=useState<Record<string,Record<string,string>>>({}),[referenceError,setReferenceError]=useState('');
 useEffect(()=>{const c=new AbortController();setReferenceError('');const keys=[...new Set(resource.fields.flatMap(f=>f.resource&&resource.columns.includes(f.key)?[f.resource]:[]))];Promise.all(keys.map(async key=>[key,Object.fromEntries((await adminRequest<{records:RecordRow[]}>(`/data/${key}`,{signal:c.signal})).records.map(r=>[String(r.id),text(r.name??r.displayName)]))] as const)).then(v=>{if(!c.signal.aborted)setReferenceNames(Object.fromEntries(v));}).catch(()=>{if(!c.signal.aborted){setReferenceNames({});setReferenceError('关联名称读取失败，请重新打开页面。');}});return()=>c.abort();},[resource.key]);
 function cell(row:RecordRow,key:string){const field=resource.fields.find(f=>f.key===key);if(field?.resource)return text(resource.key==='people'&&key==='organizationUnitId'?row.organizationUnitName:resource.key==='people'&&key==='positionId'?row.positionName:referenceNames[field.resource]?.[String(row[key])]??'—');return field?.type==='select'?(optionLabels[String(row[key])]??text(row[key])):text(row[key]);}
 const statusField=resource.fields.find(field=>['status','employmentStatus','lifecycleState'].includes(field.key));
 const status=filters.selectedOptions.status?.[0]??'';
 const {value,error,reload}=useLoad<{records:RecordRow[]}>(`/data/${resource.key}?q=${encodeURIComponent(search)}&status=${encodeURIComponent(status)}`);
 return <><Failure error={error||referenceError}/>{resource.reason&&<p className="afc-muted">{resource.reason}</p>}<DataList toolbar={<FilterBar searchValue={search} onSearchChange={setSearch} searchPlaceholder={resource.key==='people'?'搜索姓名或工号':'搜索名称'} showDateRange={false} filterGroups={statusField?.options?[{id:'status',title:statusField.label,isMulti:false,options:statusField.options.map(id=>({id,label:({active:'启用',inactive:'停用',departed:'离职'} as Record<string,string>)[id]??id}))}]:[]} activeFilters={filters} onApplyFilters={setFilters} onResetFilters={()=>setFilters({selectedOptions:{}})} rightAction={<>{resource.writable&&<Button leadingIcon={<Plus size={18}/>} onClick={()=>setEditing({row:null})}>新增{resource.label}</Button>}</>}/>} emptyState={value?.records.length===0?"暂无记录":undefined}><thead><tr>{resource.columns.map(key=><th key={key}>{resource.fields.find(f=>f.key===key)?.label??({code:'编码',assetCode:'资产编码'} as Record<string,string>)[key]??key}</th>)}<th>操作</th></tr></thead><tbody>{value?.records.map(row=><tr key={String(row.id)}>{resource.columns.map(key=><td key={key}>{cell(row,key)}</td>)}<td>{resource.updateFields.length>0&&<TableActionButton icon={<PencilSimpleLine size={18}/>} onClick={()=>setEditing({row})}>编辑</TableActionButton>}</td></tr>)}</tbody></DataList>{!value&&!error&&<p role="status">正在读取…</p>}{editing&&<DataEditor resource={resource} row={editing.row} onClose={()=>setEditing(null)} onSaved={reload}/>}</>;}
export function DataPage(){
 const {pathname}=useLocation();const {value,error}=useLoad<{resources:Resource[]}>('/data/resources');
 const key=pathname.slice('/admin/data/'.length);const current=value?.resources.find(r=>r.key===key);
 if(pathname==='/admin/data')return <Navigate to="/admin/data/people" replace/>;
 return <><h1>{current?.label??'基础数据'}</h1><Failure error={error}/>{current?<Directory key={key} resource={current}/>:value?<p role="alert">目录不存在</p>:!error&&<p role="status">正在读取…</p>}</>;
}
type Account={id:string;username:string;displayName:string;status:string};
export function AccountsPage(){const {value,error,reload}=useLoad<{accounts:Account[]}>('/accounts');const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[failure,setFailure]=useState('');async function update(account:Account){if(busy)return;setBusy(true);setFailure('');try{await adminRequest(`/accounts/${account.id}`,{method:'PATCH',body:{status:account.status==='active'?'disabled':'active'}});reload();}catch(e){setFailure(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
return <><div className="admin-heading"><h1>管理员账号</h1></div><Failure error={error||failure}/><DataList toolbar={<div className="afc-list-toolbar-actions"><Button leadingIcon={<Plus size={18}/>} onClick={()=>setOpen(true)}>新增管理员</Button></div>}><thead><tr><th>用户名</th><th>显示名称</th><th>状态</th><th>操作</th></tr></thead><tbody>{value?.accounts.map(a=><tr key={a.id}><td>{a.username}</td><td>{a.displayName}</td><td>{a.status==='active'?'启用':'停用'}</td><td><TableActionButton icon={a.status==='active'?<Pause size={18}/>:<Play size={18}/>} disabled={busy} onClick={()=>void update(a)}>{a.status==='active'?'停用':'启用'}</TableActionButton></td></tr>)}</tbody></DataList>{open&&<CreateAccount onClose={()=>setOpen(false)} onSaved={reload}/>}</>;}
function CreateAccount({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [username,setUsername]=useState(''),[displayName,setDisplayName]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');return <AdminDialog title="新增管理员" onClose={()=>{if(!busy)onClose();}}><form className="admin-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await adminRequest('/accounts',{method:'POST',body:{username,displayName,password}});setPassword('');onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:'创建未确认');}finally{setBusy(false);}}}><label>用户名<Input required pattern="[A-Za-z0-9][A-Za-z0-9_.-]{2,63}" value={username} disabled={busy} onChange={e=>setUsername(e.target.value)}/></label><label>显示名称<Input required maxLength={80} value={displayName} disabled={busy} onChange={e=>setDisplayName(e.target.value)}/></label><label>初始密码<Input type="password" required minLength={12} maxLength={72} autoComplete="new-password" disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label><Failure error={error}/><Button variant="primary" type="submit" disabled={busy}>{busy?'创建中…':'创建管理员'}</Button></form></AdminDialog>;}
export function PasswordPanel({onChanged}:{onChanged:()=>void}){const [currentPassword,setCurrent]=useState(''),[newPassword,setNew]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');return <form className="admin-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await adminRequest('/auth/password',{method:'PATCH',body:{currentPassword,newPassword}});setCurrent('');setNew('');onChanged();}catch(e){setError(e instanceof Error?e.message:'修改失败');}finally{setBusy(false);}}}><label>当前密码<Input required type="password" autoComplete="current-password" disabled={busy} value={currentPassword} onChange={e=>setCurrent(e.target.value)}/></label><label>新密码<Input required type="password" minLength={12} maxLength={72} autoComplete="new-password" disabled={busy} value={newPassword} onChange={e=>setNew(e.target.value)}/></label><p className="afc-muted">修改后需要重新登录，该账号的其他会话也会失效。</p><Failure error={error}/><Button variant="primary" type="submit" disabled={busy}>{busy?'保存中…':'修改密码'}</Button></form>;}
export function AuditPanel(){const {value,error,reload}=useLoad<{entries:{id:string;action:string;targetId:string;createdAt:string}[]}>('/audit');return <><div className="admin-heading"><h2>管理操作记录</h2><Button variant="secondary"  onClick={reload}>刷新</Button></div><Failure error={error}/><DataList pinActions={false} emptyState={value?.entries.length===0?"暂无操作记录":undefined}><thead><tr><th>操作</th><th>对象</th><th>时间</th></tr></thead><tbody>{value?.entries.map(e=><tr key={e.id}><td>{e.action}</td><td>{e.targetId}</td><td>{new Date(e.createdAt).toLocaleString('zh-CN')}</td></tr>)}</tbody></DataList></>;}
