import metadata from '../../../package.json';
import {Button,Input} from '../../components/ui';
import React,{useCallback,useEffect,useState} from 'react';
import {Link,Navigate,useLocation,useNavigate} from 'react-router-dom';
import type {AppManifest} from '@metro/platform-sdk/app-manifest';
import {AdminShell,AdminDialog,type AdminUser,type AdminApplication} from './AdminShell';
import {AdminLogin} from './AdminLogin';
import {adminRequest,AdminRequestError} from './client';
import {DataPage,AccountsPage,PasswordPanel,AuditPanel} from './AdminPages';
import './admin.css';
import {AdminApplicationOutlet} from './AdminApplicationOutlet';
import {ApplicationStatusDialog} from './ApplicationStatusDialog';
import {AppGrantsDialog} from './AppGrantsDialog';
export interface Installation {id:string;appId:string;manifest:AppManifest;enabled:boolean;revision:number;grants:{grantId:string;permissionCode:string;mode:string;status:string;scope:{kind:string;targets:{type:string;id:string}[]}}[];lifecycle?:{action:string;status:string};}
function useRead<T>(path:string){const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[serial,setSerial]=useState(0);useEffect(()=>{const controller=new AbortController();setData(null);setError('');adminRequest<T>(path,{signal:controller.signal}).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'读取失败');});return()=>controller.abort();},[path,serial]);return {data,error,reload:()=>setSerial(v=>v+1)};}
function ErrorNotice({error,reload}:{error:string;reload?:()=>void}){return <div className="afc-error" role="alert">{error}{reload&&<Button variant="secondary"  onClick={reload}>刷新</Button>}</div>;}
function Overview(){const {data,error,reload}=useRead<{installed:number;enabled:number;attention:number;runtimeConfigured:boolean;installConfigured:boolean}>('/overview');return <><h1>系统总览</h1>{error?<ErrorNotice error={error} reload={reload}/>:!data?<p role="status">正在读取平台状态…</p>:<><div className="admin-metrics">{[['已注册应用',data.installed],['已启用应用',data.enabled],['需核对的操作',data.attention]].map(([label,value])=><section className="admin-card" key={label}><span>{label}</span><strong>{value}</strong></section>)}</div><section className="admin-card"><h2>平台服务</h2><dl className="afc-details"><dt>平台版本</dt><dd>{metadata.version}</dd><dt>应用安装服务</dt><dd>{data.installConfigured?'已接入':'尚未配置'}</dd><dt>应用运行宿主</dt><dd>{data.runtimeConfigured?'已接入':'尚未配置'}</dd></dl></section></>}<section className="admin-card"><h2>快捷管理</h2><div className="admin-links"><Link to="/admin/apps">应用安装与更新 →</Link><Link to="/admin/data">人员、车站与设备 →</Link><Link to="/admin/accounts">管理员账号 →</Link></div></section></>;}
function AppsPage({onChange}:{onChange:()=>void}){
 const {data,error,reload}=useRead<{applications:Installation[];runtimeConfigured:boolean;installConfigured:boolean}>('/apps');
 const [selected,setSelected]=useState<{app:Installation;action:'enable'|'disable'|'upgrade'}|null>(null),[grantApp,setGrantApp]=useState<string|null>(null),[install,setInstall]=useState(false),[file,setFile]=useState<File|null>(null),[statusApp,setStatusApp]=useState<string|null>(null),[result,setResult]=useState(''),[busy,setBusy]=useState(false),[failure,setFailure]=useState('');
 async function run(){if(busy)return;setBusy(true);setFailure('');try{
  if(install){if(!file||file.size>92*1024*1024)throw Error('请选择不超过 92MB 的签名安装 JSON 包。');const outcome=await adminRequest<{state:string}>('/install',{method:'POST',body:JSON.parse(await file.text())});setResult(outcome.state==='installed'?'应用已安装并启用。':`安装状态：${outcome.state}，请核对应用状态。`);}
  else if(selected){const {app,action}=selected;const path=`/apps/${encodeURIComponent(app.appId)}`;if(action==='upgrade'){if(!file||file.size>92*1024*1024)throw Error('请选择不超过 92MB 的签名安装 JSON 包。');const outcome=await adminRequest<{state:string}>(`${path}/upgrade`,{method:'POST',body:{revision:app.revision,package:JSON.parse(await file.text())}});setResult(outcome.state==='updated'?'应用已更新，请核对授权后启用。':'更新尚未确认完成，请查看应用状态。');}else{await adminRequest(`${path}/lifecycle`,{method:'POST',body:{revision:app.revision,action}});setResult(action==='enable'?'应用已启用。':'应用已停用。');}}
  setSelected(null);setInstall(false);onChange();
 }catch(e){setFailure(e instanceof Error?e.message:'操作未确认完成，请核对状态。');}finally{setBusy(false);reload();}}
 return <><div className="admin-heading"><h1>应用管理</h1><Button variant="primary" disabled={!data?.installConfigured} onClick={()=>{setInstall(true);setFile(null);setFailure('');setResult('');}}>安装应用</Button></div>{result&&<p role="status">{result}</p>}{error&&<ErrorNotice error={error} reload={reload}/>} {!data&&!error&&<p role="status">正在读取应用…</p>}{data&&<>{!data.installConfigured&&<p className="afc-muted">安装服务尚未配置，接入后可上传签名应用包。</p>}<div className="admin-app-grid">{data.applications.map(app=><section className="admin-card" key={app.id}><div className="admin-heading"><h2>{app.manifest.name}</h2><span className="admin-status">{app.enabled?'已启用':'已停用'}</span></div><p>{app.manifest.description}</p><p className="afc-muted">{app.appId} · v{app.manifest.version}</p>{app.lifecycle&&<p className="afc-muted">最近操作：{app.lifecycle.action} / {app.lifecycle.status}</p>}<div className="admin-actions"><Button variant="secondary" onClick={()=>setStatusApp(app.appId)}>状态</Button>{app.enabled&&app.manifest.ui.mode!=='none'&&<Link className="afc-button afc-button--secondary afc-button--md afc-button--pill" to={`/admin/app/${app.appId}`}>打开应用</Link>}{(['grant','upgrade',app.enabled?'disable':'enable'] as const).map(action=><Button variant="secondary"  key={action} disabled={action!=='grant'&&!data.runtimeConfigured} onClick={()=>{if(action==='grant'){setGrantApp(app.appId);return;}setSelected({app,action});setFailure('');setFile(null);setResult('');}}>{action==='grant'?'授权':action==='upgrade'?'更新':action==='enable'?'启用':'停用'}</Button>)}</div></section>)}</div>{!data.applications.length&&<section className="admin-card"><h2>尚未安装应用</h2><p className="afc-muted">安装经过校验的应用后，将在这里管理版本与权限。</p></section>}</>}
 {statusApp&&<ApplicationStatusDialog appId={statusApp} onClose={()=>setStatusApp(null)} onChange={()=>{reload();onChange();}}/>}
 {grantApp&&<AppGrantsDialog appId={grantApp} onClose={()=>setGrantApp(null)} onChange={()=>{reload();onChange();}}/>}
 {(selected||install)&&<AdminDialog title={install?'安装应用':`${selected!.app.manifest.name} · ${selected!.action==='upgrade'?'更新':selected!.action==='enable'?'启用':'停用'}`} onClose={()=>{if(!busy){setSelected(null);setInstall(false);}}}><div className="admin-form">{install||selected?.action==='upgrade'?<label>签名安装包<Input type="file" accept="application/json,.json" disabled={busy} onChange={e=>setFile(e.target.files?.[0]??null)}/></label>:<p>确认执行此应用操作？</p>}{failure&&<ErrorNotice error={failure}/>}<p className="afc-muted">操作失败或超时不会自动重试，请核对最新状态。</p><Button variant="primary" disabled={busy} onClick={()=>void run()}>{busy?'正在处理…':'确认'}</Button></div></AdminDialog>}
 </>;
}
function DeveloperPage(){const {data,error,reload}=useRead<{capabilities:{id:string;contractVersion:string;permissions:string[]}[]}>('/capabilities');return <><h1>开发者中心</h1><a className="afc-button afc-button--secondary afc-button--md afc-button--pill" href="https://github.com/ZhangPengQingdao/Metro_Operations_Platform/tree/main/docs" target="_blank" rel="noreferrer">查看 SDK 与接入文档</a>{error&&<ErrorNotice error={error} reload={reload}/>}<div className="admin-app-grid">{data?.capabilities.map(c=><section className="admin-card" key={c.id}><h2>{c.id}</h2><p>契约版本 {c.contractVersion}</p><p className="afc-muted">{c.permissions.join(' · ')||'由接入入口控制访问'}</p></section>)}</div></>;}
function NotificationsPanel(){const {data,error,reload}=useRead<{notifications:{id:string;title:string;description:string;path:string}[]}>('/notifications');return <><FailureNotifications error={error}/><Button variant="secondary"  onClick={reload}>刷新通知</Button>{data?.notifications.map(item=><section className="admin-card" key={item.id}><h3>{item.title}</h3><p>{item.description}</p><Link to="/admin/apps">查看应用</Link></section>)}{data?.notifications.length===0&&<p className="afc-muted">暂无需要处理的应用通知。</p>}</>;}
function FailureNotifications({error}:{error:string}){return error?<ErrorNotice error={error}/>:null;}
export default function AdminApp(){
 const location=useLocation(),navigate=useNavigate();const [user,setUser]=useState<AdminUser|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[applications,setApplications]=useState<AdminApplication[]>([]);
 useEffect(()=>{const expire=()=>{setUser(null);setApplications([]);};window.addEventListener('afc-admin-session-expired',expire);return()=>window.removeEventListener('afc-admin-session-expired',expire);},[]);
 const reloadApps=useCallback(()=>{adminRequest<{applications:Installation[]}>('/apps').then(({applications:rows})=>setApplications(rows.filter(a=>a.enabled&&a.manifest.ui.mode!=='none').map(a=>({id:a.appId,name:a.manifest.name,navigation:a.manifest.navigation.flatMap(n=>{const route=a.manifest.routes.find(r=>r.id===n.routeId);return route?[{id:n.id,label:n.label,path:`/admin/app/${a.appId}${route.path==='/'?'':route.path}`}]:[]})})))).catch(()=>setApplications([]));},[]);
 useEffect(()=>{let active=true;adminRequest<AdminUser>('/auth/me').then(value=>{if(active)setUser(value);}).catch(e=>{if(active&&!(e instanceof AdminRequestError&&e.status===401))setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 useEffect(()=>{if(user)reloadApps();},[user,reloadApps]);
 async function logout(){await adminRequest('/auth/logout',{method:'POST'});setUser(null);setApplications([]);navigate('/admin/login');}
 if(loading)return <div className="afc-admin"><p role="status">正在检查管理员会话…</p></div>;
 if(!user)return <>{error&&<div className="afc-admin"><ErrorNotice error={error}/></div>}<AdminLogin onLogin={async(username,password)=>{setUser(await adminRequest<AdminUser>('/auth/login',{method:'POST',body:{username,password}}));setError('');navigate('/admin');}}/></>;
 if(location.pathname==='/admin/login')return <Navigate to="/admin" replace/>;
 const path=location.pathname;const content=path==='/admin'?<Overview/>:path==='/admin/apps'?<AppsPage onChange={reloadApps}/>:(path==='/admin/data'||path.startsWith('/admin/data/'))?<DataPage/>:path==='/admin/accounts'?<AccountsPage/>:path==='/admin/audit'?<AuditPanel/>:path==='/admin/developer'?<DeveloperPage/>:path.startsWith('/admin/app/')?<AdminApplicationOutlet/>:<section className="admin-card"><h1>页面不存在</h1><Link to="/admin">返回系统总览</Link></section>;
 return <AdminShell user={user} applications={applications} onLogout={logout} profileContent={<PasswordPanel onChanged={()=>{setUser(null);navigate('/admin/login');}}/>} notificationsContent={<NotificationsPanel/>}>{content}</AdminShell>;
}
