import {InstallPackageReview} from './InstallPackageReview';
import {PublisherPolicyDialog} from './PublisherPolicyDialog';
import {SystemUpdates} from './SystemUpdates';
import {EmployeeAccounts} from './EmployeeAccounts';
import metadata from '../../../package.json';
import {Button,Input} from '../../components/ui';
import React,{useCallback,useEffect,useState} from 'react';
import {Link,Navigate,useLocation,useNavigate} from 'react-router-dom';
import type {AppManifest} from '@metro/platform-sdk/app-manifest';
import {AdminShell,AdminDialog,type AdminUser,type AdminApplication} from './AdminShell';
import {AdminLogin} from './AdminLogin';
import {adminRequest,AdminRequestError} from './client';
import {DataPage,AccountsPage,PasswordPanel,AuditPanel} from './AdminPages';
import './admin.css';
import {AdminApplicationOutlet} from './AdminApplicationOutlet';
import {ApplicationStatusDialog} from './ApplicationStatusDialog';
import {AppGrantsDialog} from './AppGrantsDialog';
export interface Installation {serviceIdentityId?:string|null;id:string;appId:string;manifest:AppManifest;enabled:boolean;revision:number;grants:{grantId:string;permissionCode:string;mode:string;status:string;scope:{kind:string;targets:{type:string;id:string}[]}}[];lifecycle?:{action:string;status:string};}
function useRead<T>(path:string){const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[serial,setSerial]=useState(0);useEffect(()=>{const controller=new AbortController();setData(null);setError('');adminRequest<T>(path,{signal:controller.signal}).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'读取失败');});return()=>controller.abort();},[path,serial]);return {data,error,reload:()=>setSerial(v=>v+1)};}
function ErrorNotice({error,reload}:{error:string;reload?:()=>void}){return <div className="afc-error" role="alert">{error}{reload&&<Button variant="secondary"  onClick={reload}>刷新</Button>}</div>;}
function Overview(){const {data,error,reload}=useRead<{installed:number;enabled:number;attention:number;runtimeConfigured:boolean;installConfigured:boolean}>('/overview');return <><h1>系统总览</h1>{error?<ErrorNotice error={error} reload={reload}/>:!data?<p role="status">正在读取平台状态…</p>:<><div className="admin-metrics">{[['已注册应用',data.installed],['已启用应用',data.enabled],['需核对的操作',data.attention]].map(([label,value])=><section className="admin-card" key={label}><span>{label}</span><strong>{value}</strong></section>)}</div><section className="admin-card"><h2>平台服务</h2><dl className="afc-details"><dt>平台版本</dt><dd>{metadata.version}</dd><dt>应用安装服务</dt><dd>{data.installConfigured?'已接入':'尚未配置'}</dd><dt>应用运行宿主</dt><dd>{data.runtimeConfigured?'已接入':'尚未配置'}</dd></dl></section></>}<section className="admin-card"><h2>快捷管理</h2><div className="admin-links"><Link to="/admin/apps">应用安装与更新 →</Link><Link to="/admin/data">人员、车站与设备 →</Link><Link to="/admin/accounts">管理员账号 →</Link></div></section></>;}
function AppsPage({onChange}:{onChange:()=>void}){
 const {data,error,reload}=useRead<{applications:Installation[];runtimeConfigured:boolean;installConfigured:boolean}>('/apps');
 const [selected,setSelected]=useState<{app:Installation;action:'enable'|'disable'|'upgrade'}|null>(null),[grantApp,setGrantApp]=useState<string|null>(null),[install,setInstall]=useState(false),[policyOpen,setPolicyOpen]=useState(false),[statusApp,setStatusApp]=useState<string|null>(null),[result,setResult]=useState(''),[busy,setBusy]=useState(false),[failure,setFailure]=useState('');
 async function run(){if(busy||!selected||selected.action==='upgrade')return;setBusy(true);setFailure('');try{
  await adminRequest(`/apps/${encodeURIComponent(selected.app.appId)}/lifecycle`,{method:'POST',body:{revision:selected.app.revision,action:selected.action}});
  setResult(selected.action==='enable'?'应用已启用。':'应用已停用。');setSelected(null);onChange();
 }catch(e){setFailure(e instanceof Error?e.message:'操作未确认，请核对状态。');}finally{setBusy(false);reload();}}

 return <><div className="admin-heading"><h1>应用管理</h1><Button variant="secondary" disabled={!data?.installConfigured} onClick={()=>setPolicyOpen(true)}>发布者与审批</Button><Button variant="primary" disabled={!data?.installConfigured} onClick={()=>{setInstall(true);setFailure('');setResult('');}}>安装应用</Button></div>{result&&<p role="status">{result}</p>}{error&&<ErrorNotice error={error} reload={reload}/>} {!data&&!error&&<p role="status">正在读取应用…</p>}{data&&<>{!data.installConfigured&&<p className="afc-muted">安装服务尚未配置，接入后可上传签名应用包。</p>}<div className="admin-app-grid">{data.applications.map(app=><section className="admin-card" key={app.id}><div className="admin-heading"><h2>{app.manifest.name}</h2><span className="admin-status">{app.enabled?'已启用':'已停用'}</span></div><p>{app.manifest.description}</p><p className="afc-muted">{app.appId} · v{app.manifest.version}</p>{app.lifecycle&&<p className="afc-muted">最近操作：{app.lifecycle.action} / {app.lifecycle.status}</p>}<div className="admin-actions"><Button variant="secondary" onClick={()=>setStatusApp(app.appId)}>状态</Button>{app.enabled&&app.manifest.ui.mode!=='none'&&<Link className="afc-button afc-button--secondary afc-button--md afc-button--pill" to={`/admin/app/${app.appId}`}>打开应用</Link>}{(['grant','upgrade',app.enabled?'disable':'enable'] as const).map(action=><Button variant="secondary"  key={action} disabled={action!=='grant'&&!data.runtimeConfigured} onClick={()=>{if(action==='grant'){setGrantApp(app.appId);return;}setSelected({app,action});setFailure('');setResult('');}}>{action==='grant'?'授权':action==='upgrade'?'更新':action==='enable'?'启用':'停用'}</Button>)}</div></section>)}</div>{!data.applications.length&&<section className="admin-card"><h2>尚未安装应用</h2><p className="afc-muted">安装经过校验的应用后，将在这里管理版本与权限。</p></section>}</>}
 {policyOpen&&<PublisherPolicyDialog onClose={()=>setPolicyOpen(false)}/>}
 {statusApp&&<ApplicationStatusDialog appId={statusApp} onClose={()=>setStatusApp(null)} onChange={()=>{reload();onChange();}}/>}
 {grantApp&&<AppGrantsDialog appId={grantApp} onClose={()=>setGrantApp(null)} onChange={()=>{reload();onChange();}}/>}
 {(selected||install)&&<AdminDialog title={install?'安装应用':`${selected!.app.manifest.name} · ${selected!.action==='upgrade'?'更新':selected!.action==='enable'?'启用':'停用'}`} onClose={()=>{if(!busy){setSelected(null);setInstall(false);}}}>{install||selected?.action==='upgrade'?<InstallPackageReview target={selected?{appId:selected.app.appId,revision:selected.app.revision}:undefined} onBusy={setBusy} onDone={message=>{setResult(message);setSelected(null);setInstall(false);reload();onChange();}}/>:<div className="admin-form"><p>确认执行此应用操作？</p>{failure&&<ErrorNotice error={failure}/>}<Button disabled={busy} onClick={()=>void run()}>{busy?'正在处理…':'确认'}</Button></div>}</AdminDialog>}
 </>;
}
function DeveloperPage(){const {data,error,reload}=useRead<{capabilities:{id:string;contractVersion:string;permissions:string[]}[]}>('/capabilities');return <><h1>开发者中心</h1><a className="afc-button afc-button--secondary afc-button--md afc-button--pill" href="https://github.com/ZhangPengQingdao/Metro_Operations_Platform/tree/main/docs" target="_blank" rel="noreferrer">查看 SDK 与接入文档</a>{error&&<ErrorNotice error={error} reload={reload}/>}<div className="admin-app-grid">{data?.capabilities.map(c=><section className="admin-card" key={c.id}><h2>{c.id}</h2><p>契约版本 {c.contractVersion}</p><p className="afc-muted">{c.permissions.join(' · ')||'由接入入口控制访问'}</p></section>)}</div></>;}
function NotificationsPanel(){const {data,error,reload}=useRead<{notifications:{id:string;title:string;description:string;path:string}[]}>('/notifications');return <><FailureNotifications error={error}/><Button variant="secondary"  onClick={reload}>刷新通知</Button>{data?.notifications.map(item=><section className="admin-card" key={item.id}><h3>{item.title}</h3><p>{item.description}</p><Link to="/admin/apps">查看应用</Link></section>)}{data?.notifications.length===0&&<p className="afc-muted">暂无需要处理的应用通知。</p>}</>;}
function FailureNotifications({error}:{error:string}){return error?<ErrorNotice error={error}/>:null;}
export default function AdminApp(){
 const location=useLocation(),navigate=useNavigate();const [user,setUser]=useState<AdminUser|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[applications,setApplications]=useState<AdminApplication[]>([]);
 useEffect(()=>{const expire=()=>{setUser(null);setApplications([]);};window.addEventListener('afc-admin-session-expired',expire);return()=>window.removeEventListener('afc-admin-session-expired',expire);},[]);
 const reloadApps=useCallback(()=>{adminRequest<{applications:Installation[]}>('/apps').then(({applications:rows})=>setApplications(rows.filter(a=>a.enabled&&a.manifest.ui.mode!=='none').map(a=>({id:a.appId,name:a.manifest.name,navigation:a.manifest.navigation.flatMap(n=>{const route=a.manifest.routes.find(r=>r.id===n.routeId);return route?[{id:n.id,label:n.label,path:`/admin/app/${a.appId}${route.path==='/'?'':route.path}`}]:[]})})))).catch(()=>setApplications([]));},[]);
 useEffect(()=>{let active=true;adminRequest<AdminUser>('/auth/me').then(value=>{if(active)setUser(value);}).catch(e=>{if(active&&!(e instanceof AdminRequestError&&e.status===401))setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 useEffect(()=>{if(user)reloadApps();},[user,reloadApps]);
 async function logout(){await adminRequest('/auth/logout',{method:'POST'});setUser(null);setApplications([]);navigate('/admin/login');}
 if(loading)return <div className="afc-admin"><p role="status">正在检查管理员会话…</p></div>;
 if(!user)return <>{error&&<div className="afc-admin"><ErrorNotice error={error}/></div>}<AdminLogin onLogin={async(username,password)=>{setUser(await adminRequest<AdminUser>('/auth/login',{method:'POST',body:{username,password}}));setError('');navigate('/admin');}}/></>;
 if(location.pathname==='/admin/login')return <Navigate to="/admin" replace/>;
 const path=location.pathname;const content=path==='/admin'?<Overview/>:path==='/admin/apps'?<AppsPage onChange={reloadApps}/>:(path==='/admin/data'||path.startsWith('/admin/data/'))?<DataPage/>:path==='/admin/accounts/employees'?<EmployeeAccounts/>:path==='/admin/accounts'?<AccountsPage/>:path==='/admin/updates'?<SystemUpdates/>:path==='/admin/audit'?<AuditPanel/>:path==='/admin/developer'?<DeveloperPage/>:path.startsWith('/admin/app/')?<AdminApplicationOutlet/>:<section className="admin-card"><h1>页面不存在</h1><Link to="/admin">返回系统总览</Link></section>;
 return <AdminShell user={user} applications={applications} onLogout={logout} profileContent={<PasswordPanel onChanged={()=>{setUser(null);navigate('/admin/login');}}/>} notificationsContent={<NotificationsPanel/>}>{content}</AdminShell>;
}
