import {MagnifyingGlass} from '@phosphor-icons/react';
import React,{useEffect,useState} from 'react';
import {Button,DataList,TableActionButton} from '../../components/ui';
import {adminRequest} from './client';
type Attempt={id:string;sequence:number;migrationId:string;status:string};
type History={revision:number;enabled:boolean;attempts:Attempt[];nextSequence:number|string|null};
const labels:Record<string,string>={running:'待核对',uncertain:'结果未知',applied:'已完成',rolled_back:'已回滚',dispatched:'结果待确认',completed:'已提交'};
export function AppMigrationStatus({appId,onChange,onBusy,kind='migrations'}:{appId:string;onChange:()=>void;onBusy?:(busy:boolean)=>void;kind?:'migrations'|'writes'}){
 const [data,setData]=useState<History|null>(null),[after,setAfter]=useState<number|string>(0),[previous,setPrevious]=useState<(number|string)[]>([]),[serial,setSerial]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const path=`/apps/${encodeURIComponent(appId)}/storage/${kind}`;
 useEffect(()=>{const c=new AbortController();setData(null);setError('');adminRequest<History&{writes?:{requestId:string;status:string}[];nextCursor?:string|null}>(`${path}${kind==='migrations'?`?afterSequence=${after}`:after?`?after=${after}`:''}`,{signal:c.signal}).then(v=>{if(!c.signal.aborted)setData(kind==='migrations'?v:{...v,attempts:(v.writes??[]).map(w=>({id:w.requestId,sequence:0,migrationId:w.requestId,status:w.status})),nextSequence:v.nextCursor??null});}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[path,after,serial]);
 async function reconcile(attemptId:string){if(!data||busy)return;setBusy(true);onBusy?.(true);setError('');try{await adminRequest(`${path}/reconcile`,{method:'POST',body:{revision:data.revision,...(kind==='migrations'?{attemptId}:{requestId:attemptId})}});setSerial(v=>v+1);onChange();}catch(e){setError(e instanceof Error?e.message:'核对结果未确认，请刷新。');setData(null);}finally{setBusy(false);onBusy?.(false);}}
 return <section>{error&&<p role="alert" className="afc-error">{error}</p>}<DataList emptyState={data?.attempts.length===0?(kind==='migrations'?'暂无迁移记录':'暂无写入记录'):undefined}><thead><tr><th>{kind==='migrations'?'迁移':'请求编号'}</th><th>状态</th><th>操作</th></tr></thead><tbody>{data?.attempts.map(a=><tr key={a.id}><td>{a.migrationId}</td><td>{labels[a.status]??a.status}</td><td>{['running','uncertain','dispatched'].includes(a.status)&&<TableActionButton icon={<MagnifyingGlass size={18}/>} disabled={busy||data.enabled} onClick={()=>void reconcile(a.id)}>核对原事务</TableActionButton>}</td></tr>)}</tbody></DataList>{data?.attempts.some(a=>['running','uncertain','dispatched'].includes(a.status))&&<p className="afc-muted">核对原事务证据，不重放操作。证据不足时继续阻断。</p>}{(previous.length>0||!!data?.nextSequence)&&<div className="admin-actions"><Button variant="secondary" disabled={busy||!previous.length} onClick={()=>{setAfter(previous[previous.length-1]);setPrevious(v=>v.slice(0,-1));}}>上一页</Button><Button variant="secondary" disabled={busy||!data?.nextSequence} onClick={()=>{setPrevious(v=>[...v,after]);setAfter(data!.nextSequence!);}}>下一页</Button></div>}</section>;
}
