import React,{useEffect,useState} from 'react';
import {Button,Select,Table} from '../../components/ui';
import {adminRequest} from './client';
type State={revision:string;permissions:{code:string;description:string}[];roles:{id:string;name:string;status:string;grants:{code:string;scope:{kind:string}}[]}[]};
export function EmployeeAppRoles({appId}:{appId:string}){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[role,setRole]=useState('');
 const [people,setPeople]=useState<{personId:string;name:string;employeeNo:string}[]>([]),[person,setPerson]=useState(''),[assignment,setAssignment]=useState<{id:string;roleId:string}|null|undefined>(undefined),[assignedRole,setAssignedRole]=useState('');
 const path=`/apps/${encodeURIComponent(appId)}/employee-roles`;
 async function load(){try{setError('');setState(await adminRequest<State>(path));const result=await adminRequest<{grants:typeof people}>(`/apps/${encodeURIComponent(appId)}/employee-access`);setPeople(result.grants);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[appId]);
 useEffect(()=>{setAssignment(undefined);if(!person)return;const c=new AbortController();adminRequest<{assignment:{id:string;roleId:string}|null}>(`/employee-roles/${person}`,{signal:c.signal}).then(result=>{setAssignment(result.assignment);setAssignedRole(result.assignment?.roleId??'');}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[person]);
 async function toggle(code:string,enabled:boolean){if(!state||busy)return;setBusy(true);try{setState(await adminRequest<State>(path,{method:'PUT',body:{revision:state.revision,roleId:role,permissionCode:code,enabled}}));}catch(e){setError((e as Error).message);setState(null);}finally{setBusy(false);}}
 async function assign(){if(assignment===undefined||busy)return;setBusy(true);try{const result=await adminRequest<{assignment:{id:string;roleId:string}}>('/employee-roles',{method:'PUT',body:{personId:person,roleId:assignedRole,revision:assignment?.id??null}});setAssignment(result.assignment);setError('');}catch(e){setError((e as Error).message);setAssignment(undefined);}finally{setBusy(false);}}
 return <section><h3>员工角色与应用权限</h3>{error&&<p role="alert" className="afc-error">{error}</p>}<Button variant="secondary" disabled={busy} onClick={()=>void load()}>刷新角色与权限</Button>
 <label>角色<Select value={role} disabled={busy} onChange={e=>setRole(e.target.value)}><option value="">请选择</option>{state?.roles.filter(r=>r.status==='active').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</Select></label>
 {role&&state&&<Table variant="directory"><thead><tr><th>应用权限</th><th>状态</th><th>操作</th></tr></thead><tbody>{state.permissions.map(p=>{const grant=state.roles.find(r=>r.id===role)?.grants.find(g=>g.code===p.code);return <tr key={p.code}><td>{p.description}</td><td>{grant?'已授权':'未授权'}</td><td><Button variant="secondary" disabled={busy} onClick={()=>void toggle(p.code,!grant)}>{grant?'撤销':'授权'}</Button></td></tr>;})}</tbody></Table>}
 <form className="admin-form" onSubmit={e=>{e.preventDefault();void assign();}}><label>已分配应用的员工<Select required value={person} disabled={busy} onChange={e=>setPerson(e.target.value)}><option value="">请选择</option>{people.map(p=><option key={p.personId} value={p.personId}>{p.name} · {p.employeeNo}</option>)}</Select></label><label>员工角色<Select required disabled={busy||assignment===undefined} value={assignedRole} onChange={e=>setAssignedRole(e.target.value)}><option value="">请选择</option>{state?.roles.filter(r=>r.status==='active').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</Select></label><p className="afc-muted">员工只有一个生效角色，变更会影响其所有应用。</p><Button type="submit" disabled={busy||assignment===undefined||!assignedRole||assignment?.roleId===assignedRole}>保存员工角色</Button></form></section>;
}
