import React,{useEffect,useState} from 'react';
import {PencilSimpleLine,Plus,X} from '@phosphor-icons/react';
import {Button,DataList,FilterBar,Input,ListPagination,Select,Switch,TabContent,TabList,Tabs,TabTrigger,TableActionButton,type FilterState} from '../../components/ui';
import {AdminDialog} from './AdminShell';
import {adminRequest} from './client';

type Line={id:string;name:string;shortName:string|null;status:'active'|'inactive';nextSortOrder:number};
type Membership={lineId:string;lineName:string;lineStatus:'active'|'inactive';sortOrder:number;status:'active'|'inactive'};
type Station={id:string;name:string;shortName:string|null;status:'active'|'inactive';lines:Membership[];revision:string};
type Directory={lines:Line[];stations:Station[];page:number;total:number;hasNext:boolean};
type Selection={lineId:string;sortOrder:string};

export function LineStationsPage({linesContent}:{linesContent:React.ReactNode}){
 const [section,setSection]=useState('stations');
 return <Tabs value={section} onChange={setSection}><TabList><TabTrigger value="stations">车站</TabTrigger><TabTrigger value="lines">线路</TabTrigger></TabList><TabContent value="stations"><StationList/></TabContent><TabContent value="lines">{linesContent}</TabContent></Tabs>;
}

function StationList(){
 const [data,setData]=useState<Directory|null>(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[filters,setFilters]=useState<FilterState>({selectedOptions:{}}),[page,setPage]=useState(1),[serial,setSerial]=useState(0),[loading,setLoading]=useState(true),[editing,setEditing]=useState<{station:Station|null}|null>(null);
 const status=filters.selectedOptions.status?.[0]??'',lineId=filters.selectedOptions.line?.[0]??'';
 useEffect(()=>{
  const controller=new AbortController();setLoading(true);setError('');
  const query=new URLSearchParams({q:search,status,page:String(page)});if(lineId)query.set('lineId',lineId);
  adminRequest<Directory>(`/data/line-stations?${query}`,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setData(value);}).catch(cause=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:'车站读取失败');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  return()=>controller.abort();
 },[search,status,lineId,page,serial]);
 return <>{error&&<p role="alert" className="afc-error">{error}</p>}<DataList toolbar={<FilterBar searchValue={search} onSearchChange={value=>{setSearch(value);setPage(1);}} searchPlaceholder="搜索车站或线路" showDateRange={false} filterGroups={[{id:'line',title:'所属线路',isMulti:false,options:(data?.lines??[]).map(line=>({id:line.id,label:line.name+(line.status==='inactive'?'（停用）':'')}))},{id:'status',title:'状态',isMulti:false,options:[{id:'active',label:'启用'},{id:'inactive',label:'停用'}]}]} activeFilters={filters} onApplyFilters={value=>{setFilters(value);setPage(1);}} onResetFilters={()=>{setFilters({selectedOptions:{}});setPage(1);}} rightAction={<Button leadingIcon={<Plus size={18}/>} disabled={loading||!!error} onClick={()=>setEditing({station:null})}>新增车站</Button>}/>} emptyState={!loading&&data?.stations.length===0?'暂无车站':undefined} pagination={data&&data.total>50?<ListPagination page={data.page} total={data.total} hasNext={data.hasNext} busy={loading} onPrevious={()=>setPage(value=>value-1)} onNext={()=>setPage(value=>value+1)}/>:undefined}><thead><tr><th>车站名称</th><th>简称</th><th>所属线路 · 站序</th><th>状态</th><th>操作</th></tr></thead><tbody>{data?.stations.map(station=><tr key={station.id}><td>{station.name}{station.lines.filter(line=>line.status==='active'&&line.lineStatus==='active').length>1&&<span className="afc-muted station-interchange">换乘站</span>}</td><td>{station.shortName||'—'}</td><td><div className="station-line-labels">{station.lines.filter(line=>line.status==='active').map(line=><span key={line.lineId}>{line.lineName} · {line.sortOrder}{line.lineStatus==='inactive'?'（线路停用）':''}</span>)}{!station.lines.some(line=>line.status==='active')&&<span className="afc-muted">未关联线路</span>}</div></td><td>{station.status==='active'?'启用':'停用'}</td><td><TableActionButton icon={<PencilSimpleLine size={18}/>} disabled={loading||!!error} onClick={()=>setEditing({station})}>编辑</TableActionButton></td></tr>)}</tbody></DataList>{loading&&<p role="status">正在读取车站…</p>}{editing&&data&&<StationEditor station={editing.station} lines={data.lines} onClose={()=>setEditing(null)} onSaved={()=>setSerial(value=>value+1)}/>}</>;
}

function StationEditor({station,lines,onClose,onSaved}:{station:Station|null;lines:Line[];onClose:()=>void;onSaved:()=>void}){
 const [name,setName]=useState(station?.name??''),[shortName,setShortName]=useState(station?.shortName??''),[active,setActive]=useState(station?.status!=='inactive'),[selected,setSelected]=useState<Selection[]>(()=>station?.lines.filter(line=>line.status==='active').map(line=>({lineId:line.lineId,sortOrder:String(line.sortOrder)}))??[{lineId:'',sortOrder:''}]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const canAdd=selected.length<50&&selected.every(item=>item.lineId)&&lines.some(line=>line.status==='active'&&!selected.some(item=>item.lineId===line.id));
 function changeLine(index:number,lineId:string){setSelected(current=>current.map((item,i)=>i===index?{lineId,sortOrder:String(station?.lines.find(line=>line.lineId===lineId)?.sortOrder??lines.find(line=>line.id===lineId)?.nextSortOrder??'')}:item));}
 async function save(event:React.FormEvent){
  event.preventDefault();if(busy)return;setBusy(true);setError('');
  try{const body={name,shortName:shortName||null,status:active?'active':'inactive',lines:selected.map(item=>({lineId:item.lineId,sortOrder:Number(item.sortOrder)})),...(station?{revision:station.revision}:{})};await adminRequest(`/data/stations${station?`/${station.id}`:''}`,{method:station?'PUT':'POST',body});onSaved();onClose();}catch(cause){setError(cause instanceof Error?cause.message:'保存结果未确认，请刷新核对。');}finally{setBusy(false);}
 }
 return <AdminDialog title={station?'编辑车站':'新增车站'} className="admin-station-editor" onClose={()=>{if(!busy)onClose();}}><form className="admin-form" onSubmit={save}><label>车站名称 *<Input required maxLength={200} value={name} disabled={busy} onChange={event=>setName(event.target.value)}/></label><label>简称<Input maxLength={100} value={shortName} disabled={busy} onChange={event=>setShortName(event.target.value)}/></label><Switch label="启用" checked={active} disabled={busy} onChange={event=>setActive(event.target.checked)}/><fieldset className="station-memberships"><legend>所属线路 *</legend><p className="afc-muted">换乘站添加多条线路，共用同一份车站资料。站序按各线路分别填写。</p>{selected.map((item,index)=>{const inactive=lines.find(line=>line.id===item.lineId)?.status==='inactive';return <div className="station-membership" key={index}><label>线路 {index+1}<Select required disabled={busy} value={item.lineId} onChange={event=>changeLine(index,event.target.value)}><option value="">请选择线路</option>{lines.filter(line=>line.id===item.lineId||line.status==='active'&&!selected.some(row=>row.lineId===line.id)).map(line=><option key={line.id} value={line.id}>{line.name}{line.status==='inactive'?'（停用）':''}</option>)}</Select></label><label>站序<Input type="number" min={1} max={100000} step={1} required disabled={busy||inactive} value={item.sortOrder} onChange={event=>setSelected(current=>current.map((row,i)=>i===index?{...row,sortOrder:event.target.value}:row))}/></label><Button type="button" variant="secondary" disabled={busy||selected.length===1} aria-label={`移除线路 ${index+1}`} onClick={()=>setSelected(current=>current.filter((_,i)=>i!==index))}><X size={18}/></Button></div>;})}<Button type="button" variant="secondary" leadingIcon={<Plus size={18}/>} disabled={busy||!canAdd} onClick={()=>setSelected(current=>[...current,{lineId:'',sortOrder:''}])}>添加线路</Button>{!lines.some(line=>line.status==='active')&&<p className="afc-muted">请先在“线路”标签中新增或启用线路。</p>}</fieldset>{error&&<p role="alert" className="afc-error">{error}</p>}<div className="admin-station-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>取消</Button><Button type="submit" disabled={busy||!selected.length||selected.some(item=>!item.lineId)}>{busy?'保存中…':'保存车站'}</Button></div></form></AdminDialog>;
}
