import React,{useEffect,useState} from 'react';
import {Button,Input,Table} from '../../components/ui';
import {AdminDialog} from './AdminShell';
import {adminRequest} from './client';
type Key={keyId:string;publisherId:string;publicKeyPem:string;revoked:boolean;appIds:string[];validFrom:string;validUntil:string};
type Policy={revision:number;policy:{keys:Key[]};approvedManifestDigests:string[]};
export function PublisherPolicyDialog({onClose}:{onClose:()=>void}){
 const [data,setData]=useState<Policy|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[serial,setSerial]=useState(0);
 const [publisher,setPublisher]=useState(''),[keyId,setKeyId]=useState(''),[pem,setPem]=useState(''),[apps,setApps]=useState(''),[until,setUntil]=useState('');
 useEffect(()=>{const c=new AbortController();setData(null);adminRequest<Policy>('/publisher-policy',{signal:c.signal}).then(v=>{if(!c.signal.aborted)setData(v);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[serial]);
 async function save(keys:Key[]){if(!data||busy)return;setBusy(true);setError('');try{setData(await adminRequest<Policy>('/publisher-policy',{method:'PUT',body:{revision:data.revision,keys}}));setPem('');}catch(e){setData(null);setError(e instanceof Error?e.message:'操作未确认，请刷新核对');}finally{setBusy(false);}}
 async function revoke(digest:string){if(!data||busy)return;setBusy(true);setError('');try{setData(await adminRequest<Policy>('/version-approval/revoke',{method:'POST',body:{revision:data.revision,digest}}));}catch(e){setData(null);setError(e instanceof Error?e.message:'操作未确认');}finally{setBusy(false);}}
 return <AdminDialog title="发布者信任与版本审批" onClose={()=>{if(!busy)onClose();}}>{error&&<p role="alert" className="afc-error">{error}</p>}<Button variant="secondary" disabled={busy} onClick={()=>{setError('');setSerial(v=>v+1);}}>刷新</Button><Table variant="directory"><thead><tr><th>发布者 / 密钥</th><th>应用范围</th><th>有效期</th><th>操作</th></tr></thead><tbody>{data?.policy.keys.map((k,i)=><tr key={`${k.publisherId}/${k.keyId}`}><td>{k.publisherId} / {k.keyId}{k.revoked?'（已撤销）':''}</td><td>{k.appIds.join('、')}</td><td>{k.validUntil}</td><td><Button variant="secondary" disabled={busy} onClick={()=>void save(data.policy.keys.map((v,index)=>index===i?{...v,revoked:!v.revoked}:v))}>{k.revoked?'恢复信任':'撤销信任'}</Button></td></tr>)}</tbody></Table><form className="admin-form" onSubmit={e=>{e.preventDefault();if(!data)return;void save([...data.policy.keys,{publisherId:publisher,keyId,publicKeyPem:pem.trim(),appIds:apps.split(',').map(v=>v.trim()).filter(Boolean),revoked:false,validFrom:new Date().toISOString(),validUntil:new Date(until).toISOString()}]);}}><h3>新增发布者公钥</h3><label>发布者 ID<Input required value={publisher} onChange={e=>setPublisher(e.target.value)} disabled={busy}/></label><label>密钥 ID<Input required value={keyId} onChange={e=>setKeyId(e.target.value)} disabled={busy}/></label><label>允许的应用 ID<Input required value={apps} placeholder="多个 ID 用英文逗号分隔" onChange={e=>setApps(e.target.value)} disabled={busy}/></label><label>有效期至<Input required type="datetime-local" value={until} onChange={e=>setUntil(e.target.value)} disabled={busy}/></label><label>Ed25519 公钥（PEM）<textarea required rows={4} value={pem} onChange={e=>setPem(e.target.value)} disabled={busy}/></label><Button disabled={busy||!data} type="submit">保存公钥信任</Button></form><h3>已批准版本摘要</h3>{data?.approvedManifestDigests.map(d=><div className="admin-actions" key={d}><code style={{overflowWrap:'anywhere'}}>{d}</code><Button variant="secondary" disabled={busy} onClick={()=>void revoke(d)}>撤销审批</Button></div>)}</AdminDialog>;
}
