import React,{useEffect,useState} from 'react';
import {Check,X} from '@phosphor-icons/react';
import {Button,Select,OrganizationPicker,type OrganizationOption,DataList,TableActions,TableActionButton,ListPagination} from '../../components/ui';
import {adminRequest} from './client';
import {AdminDialog} from './AdminShell';
type Application={id:string;employeeNo:string;name:string;phone:string|null;wecomUserId:string|null;organizationId:string;organization:string};
export function RegistrationReview(){
 const [data,setData]=useState<{applications:Application[];total:number}|null>(null),[page,setPage]=useState(1),[serial,setSerial]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [edit,setEdit]=useState<{row:Application;decision:'approve'|'reject'}|null>(null),[organizationId,setOrganizationId]=useState(''),[positionId,setPositionId]=useState(''),[organizations,setOrganizations]=useState<OrganizationOption[]>([]),[positions,setPositions]=useState<{id:string;name:string}[]>([]);
 useEffect(()=>{let live=true;adminRequest<typeof data>(`/registrations?page=${page}`).then(v=>{if(live)setData(v);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[page,serial]);
 useEffect(()=>{if(edit?.decision!=='approve')return;let live=true;Promise.all([adminRequest<{records:typeof organizations}>('/data/organizations?status=active'),adminRequest<{records:typeof positions}>('/data/positions?status=active')]).then(([o,p])=>{if(live){setOrganizations(o.records);setPositions(p.records);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[edit]);
 async function save(e:React.FormEvent){e.preventDefault();if(!edit||busy)return;setBusy(true);setError('');try{await adminRequest(`/registrations/${edit.row.id}/review`,{method:'POST',body:edit.decision==='reject'?{decision:'reject'}:{decision:'approve',organizationId,positionId}});setEdit(null);setSerial(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="afc-registration-review"><h1>注册审核</h1>{error&&<p role="alert" className="afc-error">{error}</p>}<DataList emptyState={data?.applications.length===0?'暂无待审核申请':undefined} pagination={data&&data.total>20?<ListPagination page={page} total={data.total} hasNext={page*20<data.total} onPrevious={()=>setPage(v=>v-1)} onNext={()=>setPage(v=>v+1)}/>:undefined}><thead><tr><th>姓名</th><th>工号</th><th>所属组织</th><th>手机号</th><th>企业微信 UserID</th><th>操作</th></tr></thead><tbody>{data?.applications.map(row=><tr key={row.id}><td>{row.name}</td><td>{row.employeeNo}</td><td>{row.organization}</td><td>{row.phone||'—'}</td><td>{row.wecomUserId||'—'}</td><td><TableActions><TableActionButton icon={<Check size={18}/>} onClick={()=>{setError('');setOrganizationId(row.organizationId);setPositionId('');setEdit({row,decision:'approve'});}}>通过</TableActionButton><TableActionButton icon={<X size={18}/>} onClick={()=>{setError('');setEdit({row,decision:'reject'});}}>拒绝</TableActionButton></TableActions></td></tr>)}</tbody></DataList>{edit&&<AdminDialog title={`${edit.decision==='approve'?'审核通过':'拒绝申请'} · ${edit.row.name}`} onClose={()=>{if(!busy)setEdit(null);}}><form className="admin-form" onSubmit={save}>{edit.decision==='approve'?<><label>所属组织<OrganizationPicker options={organizations} value={organizationId} onChange={setOrganizationId} required disabled={busy}/></label><label>岗位<Select required disabled={busy} value={positionId} onChange={e=>setPositionId(e.target.value)}><option value="">请选择</option>{positions.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></label></>:<p>拒绝后不会创建员工账号，申请人可以重新提交。</p>}{error&&<p role="alert" className="afc-error">{error}</p>}<Button type="submit" disabled={busy}>{busy?'处理中…':'确认'}</Button></form></AdminDialog>}</section>;
}
