import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {initializePlatformDatabase} from '../src/setup/schema.ts';
import {AppBusinessAuthorization} from '../src/app-platform/business-authorization/service.ts';
import {EmployeeAppAccess} from '../src/app-platform/employee/access.ts';
import {AppRegistryService,PostgresAppRegistryRepository} from '../src/app-platform/registry/index.ts';
import {createPostgresAuthorizationRepository} from '../src/platform/authorization/index.ts';
import {demoManifest} from '../../src/app-platform/samples/host-demo/manifest.ts';
import type {PlatformAdministratorContext} from '../src/platform/context/index.ts';
import {allowsAppResource} from '@metro/platform-sdk/app-backend';

test('application owner, role isolation, per-operation scopes, hierarchy and revocation',async()=>{
 const pg=new PGlite(),db={query:async(sql:string,args?:readonly unknown[])=>args?pg.query(sql,[...args]):(await pg.exec(sql)).at(-1)!,release(){}},pool={...db,connect:async()=>db};
 try{
  await initializePlatformDatabase(db);
  const context:PlatformAdministratorContext={actorType:'administrator',administrator:{id:randomUUID(),username:'admin',displayName:'Admin'},execution:{type:'platform'},request:{requestId:'t',traceId:'t',startedAt:new Date().toISOString()},authorize:async permissionCode=>({id:'t',allowed:true,reasonCode:'allowed',permissionCode,subjectType:'administrator',effectiveScopes:[],decidedAt:new Date().toISOString()})};
  const dept=randomUUID(),team=randomUUID(),sibling=randomUUID(),outside=randomUUID(),position=randomUUID(),owner=randomUUID(),member=randomUUID(),other=randomUUID();
  for(const [id,type,parent] of [[dept,'department',null],[team,'workgroup',dept],[sibling,'workgroup',dept],[outside,'workgroup',null]] as const)await pg.query("INSERT INTO platform_organization_units(id,code,name,unit_type,parent_id,status,created_at,updated_at) VALUES($1::uuid,$1::text,$1::text,$2,$3,'active',now(),now())",[id,type,parent]);
  await pg.query("INSERT INTO platform_positions(id,code,name,status,created_at,updated_at) VALUES($1,'fixed','Fixed job','active',now(),now())",[position]);
  for(const [id,org] of [[owner,dept],[member,team],[other,outside]])await pg.query("INSERT INTO platform_people(id,employee_no,name,organization_unit_id,position_id,employment_status,created_at,updated_at) VALUES($1::uuid,$1::text,$1::text,$2,$3,'active',now(),now())",[id,org,position]);
  const registry=new AppRegistryService(new PostgresAppRegistryRepository(db),{authorization:createPostgresAuthorizationRepository(db),host:()=>({platformVersion:'0.6.0',capabilities:[],applications:[]})});
  const manifest=structuredClone(demoManifest);manifest.permissions.defined[0].scopeKinds=['self','workgroup','department','organizations','all'];const code=manifest.permissions.defined[0].code;
  let app=await registry.register(context,manifest);app=await registry.setEnabled(context,app.appId,app.revision,true);
  const second=JSON.parse(JSON.stringify(manifest).replaceAll(manifest.id,'other-app'));let secondApp=await registry.register(context,second);secondApp=await registry.setEnabled(context,secondApp.appId,secondApp.revision,true);
  const service=new AppBusinessAuthorization(pool),access=new EmployeeAppAccess(pool);
  await assert.rejects(service.setOwner({...context,authorize:async p=>({...await context.authorize(p,{}),allowed:false})},app.appId,{personId:owner,revision:null}),/EMPLOYEE_MANAGEMENT_DENIED/);
  await service.setOwner(context,app.appId,{personId:owner,revision:null});
  await service.setOwner(context,secondApp.appId,{personId:owner,revision:null});
  assert.equal(await service.resolve(app.appId,member),null);
  await assert.rejects(service.snapshot(app.appId,member),/APP_OWNER_REQUIRED/);
  let state=await service.snapshot(app.appId,owner);
  const initial=state.revision;
  state=await service.change(app.appId,owner,{action:'role',revision:state.revision,name:'Group reader',status:'active',rules:[{permission:code,scope:'workgroup',organizationIds:[]}]});
  const role=(state.roles[0] as {id:string}).id;
  await assert.rejects(service.change(app.appId,owner,{action:'member',revision:initial,personId:member,roleId:role,enabled:true}),/STALE_REVISION/);
  state=await service.change(app.appId,owner,{action:'member',revision:state.revision,personId:member,roleId:role,enabled:true});
  state=await service.change(app.appId,owner,{action:'activate',revision:state.revision,confirm:true});
  let resolved=await service.resolve(app.appId,member);assert.deepEqual(resolved!.grants[0].organizationIds,[team]);
  assert.deepEqual((await service.resolve(app.appId,owner))!.grants,[]);
  assert.equal(await service.resolve(secondApp.appId,member),null);
  assert.ok(await access.assert(app.appId,member));await assert.rejects(access.assert(app.appId,owner),/EMPLOYEE_APP_ACCESS_DENIED/);
  const secondState=await service.snapshot(secondApp.appId,owner);
  await assert.rejects(service.change(secondApp.appId,owner,{action:'member',revision:secondState.revision,personId:member,roleId:role,enabled:true}),/APP_ROLE_NOT_FOUND/);
  await assert.rejects(service.change(app.appId,owner,{action:'role',revision:state.revision,name:'Escape',status:'active',rules:[{permission:'platform.authorization.manage',scope:'all',organizationIds:[]}]}),/APP_SCOPE_UNSUPPORTED/);
  state=await service.change(app.appId,owner,{action:'role',revision:state.revision,id:role,name:'Department reader',status:'active',rules:[{permission:code,scope:'department',organizationIds:[]}]});
  resolved=await service.resolve(app.appId,member);assert.deepEqual(new Set(resolved!.grants[0].organizationIds),new Set([dept,team,sibling]));
  state=await service.change(app.appId,owner,{action:'role',revision:state.revision,id:role,name:'Assigned organizations',status:'active',rules:[{permission:code,scope:'organizations',organizationIds:[outside]}]});
  resolved=await service.resolve(app.appId,member);assert.deepEqual(resolved!.grants[0].organizationIds,[outside]);
  state=await service.change(app.appId,owner,{action:'role',revision:state.revision,id:role,name:'Own records',status:'active',rules:[{permission:code,scope:'self',organizationIds:[]}]});
  resolved=await service.resolve(app.appId,member);
  state=await service.change(app.appId,owner,{action:'role',revision:state.revision,name:'Additional group access',status:'active',rules:[{permission:code,scope:'workgroup',organizationIds:[]}]});
  const additional=(state.roles as {id:string;name:string}[]).find(r=>r.name==='Additional group access')!.id;
  state=await service.change(app.appId,owner,{action:'member',revision:state.revision,personId:member,roleId:additional,enabled:true});
  resolved=await service.resolve(app.appId,member);assert.equal(resolved!.grants[0].self,true);assert.deepEqual(resolved!.grants[0].organizationIds,[team]);
  state=await service.change(app.appId,owner,{action:'role',revision:state.revision,id:additional,name:'Additional group access',status:'inactive',rules:[{permission:code,scope:'all',organizationIds:[]}]});
  resolved=await service.resolve(app.appId,member);assert.equal(resolved!.grants[0].all,false);assert.equal(resolved!.grants[0].self,true);assert.deepEqual(resolved!.grants[0].organizationIds,[]);
  const employee={version:'1.0' as const,personId:member,organizationUnitId:team,requestId:'r',traceId:'t',businessAuthorization:resolved!};
  assert.equal(allowsAppResource(employee,code,{organizationUnitId:team,ownerPersonId:member}),true);
  assert.equal(allowsAppResource(employee,code,{organizationUnitId:team,ownerPersonId:owner}),false);
  state=await service.change(app.appId,owner,{action:'member',revision:state.revision,personId:member,roleId:role,enabled:false});
  assert.deepEqual((await service.resolve(app.appId,member))!.grants,[]);await assert.rejects(access.assert(app.appId,member),/EMPLOYEE_APP_ACCESS_DENIED/);
  const ownerState=await service.administratorState(context,app.appId);await service.setOwner(context,app.appId,{personId:other,revision:ownerState.revision});
  await assert.rejects(service.snapshot(app.appId,owner),/APP_OWNER_REQUIRED/);assert.ok(await service.snapshot(app.appId,other));
  await pg.query("UPDATE platform_people SET employment_status='departed' WHERE id=$1",[other]);await assert.rejects(service.snapshot(app.appId,other),/EMPLOYEE_PERSON_INACTIVE/);
  assert.ok((await pg.query("SELECT id FROM platform_admin_audit WHERE action='app.business.role'")).rows.length);
 }finally{await pg.close();}
});
