import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {initializePlatformDatabase} from '../src/setup/schema.ts';
import {AppCapabilityPublication} from '../src/app-platform/capabilities/publication.ts';
import {AppBusinessAuthorization} from '../src/app-platform/business-authorization/service.ts';
import {AppRegistryService,PostgresAppRegistryRepository} from '../src/app-platform/registry/index.ts';
import {createPostgresAuthorizationRepository} from '../src/platform/authorization/index.ts';
import type {AppManifest} from '../src/app-platform/manifest/index.ts';
import type {PlatformAdministratorContext} from '../src/platform/context/index.ts';

test('only owner can publish signed candidates; withdrawal and upgrades fail closed',async()=>{
 const pg=new PGlite(),db={query:async(sql:string,args?:readonly unknown[])=>args?pg.query(sql,[...args]):(await pg.exec(sql)).at(-1)!,release(){}},pool={...db,connect:async()=>db};
 try{
  await initializePlatformDatabase(db);
  const org=randomUUID(),position=randomUUID(),owner=randomUUID(),other=randomUUID();
  await pg.query("INSERT INTO platform_organization_units(id,code,name,unit_type,status,created_at,updated_at) VALUES($1,'group','Group','workgroup','active',now(),now())",[org]);
  await pg.query("INSERT INTO platform_positions(id,code,name,status,created_at,updated_at) VALUES($1,'worker','Worker','active',now(),now())",[position]);
  for(const person of [owner,other])await pg.query("INSERT INTO platform_people(id,employee_no,name,organization_unit_id,position_id,employment_status,created_at,updated_at) VALUES($1::uuid,$1::text,$1::text,$2,$3,'active',now(),now())",[person,org,position]);
  const context:PlatformAdministratorContext={actorType:'administrator',administrator:{id:randomUUID(),username:'admin',displayName:'Admin'},execution:{type:'platform'},request:{requestId:'test',traceId:'test',startedAt:new Date().toISOString()},authorize:async permissionCode=>({id:'test',allowed:true,reasonCode:'allowed',permissionCode,subjectType:'administrator',effectiveScopes:[],decidedAt:new Date().toISOString()})};
  const manifest:AppManifest={manifestVersion:'1.0',id:'provider',version:'1.0.0',name:'Provider',description:'Test',publisherId:'test',compatibility:{platform:{minInclusive:'0.0.1',maxExclusive:'2.0.0'},capabilities:[],applications:[]},permissions:{requested:[],defined:[{code:'app.provider.create',description:'创建记录',scopeKinds:['workgroup']}]},ui:{mode:'none'},backend:{mode:'isolated',runtime:'node',entryArtifactId:'backend',limits:{memoryMiB:128,cpuMillis:500,timeoutSeconds:30}},storage:{mode:'none'},routes:[],api:[{id:'create',method:'POST',path:'/create',handler:'create',permission:'app.provider.create',businessPermission:'app.provider.create',expose:{contractVersion:'1.0',mode:'write'}},{id:'internal',method:'POST',path:'/internal',handler:'internal',permission:'app.provider.create',businessPermission:'app.provider.create'}],navigation:[],events:{publish:[],subscribe:[]},tools:[],jobs:[],resources:[],artifacts:[{id:'backend',kind:'backend',path:'entry.cjs',bytes:1,sha256:'0'.repeat(64)}],network:{frontendOrigins:[],backendOrigins:[]}};
  const registry=new AppRegistryService(new PostgresAppRegistryRepository(db),{authorization:createPostgresAuthorizationRepository(db),host:()=>({platformVersion:'1.0.0',capabilities:[],applications:[]})});
  let installation=await registry.register(context,manifest);installation=await registry.setEnabled(context,manifest.id,installation.revision,true);
  const authorization=new AppBusinessAuthorization(pool);
  await authorization.setOwner(context,manifest.id,{personId:owner,revision:null});
  const publication=new AppCapabilityPublication(pool);
  assert.equal((await publication.state(manifest.id,owner)).capabilities[0].enabled,false);
  assert.equal(await publication.isPublished(installation,'create'),false);
  await assert.rejects(publication.state(manifest.id,other),/APP_OWNER_REQUIRED/);
  await assert.rejects(publication.set(manifest.id,other,{apiId:'create',enabled:true,revision:null}),/APP_OWNER_REQUIRED/);
  await assert.rejects(publication.set(manifest.id,owner,{apiId:'internal',enabled:true,revision:null}),/APP_CAPABILITY_NOT_DECLARED/);
  let state=await publication.set(manifest.id,owner,{apiId:'create',enabled:true,revision:null});
  assert.equal(state.capabilities[0].enabled,true);assert.equal(await publication.isPublished(installation,'create'),true);
  assert.deepEqual((await publication.catalog()).publications,[{appId:'provider',apiId:'create'}]);
  await assert.rejects(publication.set(manifest.id,owner,{apiId:'create',enabled:false,revision:null}),/STALE_REVISION/);
  state=await publication.set(manifest.id,owner,{apiId:'create',enabled:false,revision:state.capabilities[0].revision});
  assert.equal(await publication.isPublished(installation,'create'),false);
  state=await publication.set(manifest.id,owner,{apiId:'create',enabled:true,revision:state.capabilities[0].revision});
  await pg.query("UPDATE platform_app_installations SET record=jsonb_set(record,'{manifest,version}',to_jsonb('1.0.1'::text)) WHERE app_id='provider'");
  const updated={...installation,manifest:{...installation.manifest,version:'1.0.1'}};
  assert.equal(await publication.isPublished(updated,'create'),false);
  assert.deepEqual((await publication.catalog()).publications,[]);
  assert.deepEqual((await publication.state(manifest.id,owner)).capabilities.map(cap=>({enabled:cap.enabled,revision:cap.revision})),[{enabled:false,revision:null}]);
  state=await publication.set(manifest.id,owner,{apiId:'create',enabled:true,revision:null});
  assert.equal(state.capabilities[0].enabled,true);assert.equal(await publication.isPublished(updated,'create'),true);
  const ownerState=await authorization.administratorState(context,manifest.id);
  await authorization.setOwner(context,manifest.id,{personId:other,revision:ownerState.revision});
  assert.equal(await publication.isPublished(updated,'create'),false);
  assert.deepEqual((await publication.catalog()).publications,[]);
  assert.deepEqual((await publication.state(manifest.id,other)).capabilities.map(cap=>({enabled:cap.enabled,revision:cap.revision})),[{enabled:false,revision:null}]);
  await assert.rejects(publication.state(manifest.id,owner),/APP_OWNER_REQUIRED/);
  state=await publication.set(manifest.id,other,{apiId:'create',enabled:true,revision:null});
  assert.equal(state.capabilities[0].enabled,true);assert.equal(await publication.isPublished(updated,'create'),true);
  await pg.query("UPDATE platform_people SET employment_status='inactive' WHERE id=$1",[other]);
  assert.equal(await publication.isPublished(updated,'create'),false);
  assert.deepEqual((await publication.catalog()).publications,[]);
 }finally{await pg.close();}
});
