import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import {initializePlatformDatabase} from '../src/setup/schema.ts';
import {EmployeeIdentityService,EMPLOYEE_SESSION_COOKIE} from '../src/platform/employee-identity/index.ts';
import {AdminIdentityError} from '../src/core/admin-identity/index.ts';
import {registerEmployeeRoutes} from '../src/app-platform/employee/routes.ts';
import {createManagementGateway,createManagementApiAuthorization} from '../src/app-platform/management/gateway.ts';
import {AppRegistryService,PostgresAppRegistryRepository} from '../src/app-platform/registry/index.ts';
import {createAuthorizationService,createPostgresAuthorizationRepository,AUTHORIZATION_ROLE_SEEDS} from '../src/platform/authorization/index.ts';
import {createPostgresPeopleDirectoryRepository} from '../src/platform/people/index.ts';
import type {PlatformAdministratorContext} from '../src/platform/context/index.ts';
import type {AppManifest} from '../src/app-platform/manifest/index.ts';
import type {AppManagement} from '../src/app-platform/management/service.ts';
import {AppStdioApiError} from '../src/app-platform/runtime/stdio-api.ts';
import {EmployeeAppAccess} from '../src/app-platform/employee/access.ts';

const org='51000000-0000-4000-8000-000000000001',person='51000000-0000-4000-8000-000000000002',position='51000000-0000-4000-8000-000000000003',place='51000000-0000-4000-8000-000000000004',otherPlace='51000000-0000-4000-8000-000000000005';
const actor:PlatformAdministratorContext={actorType:'administrator',administrator:{id:'51000000-0000-4000-8000-000000000006',username:'admin',displayName:'Admin'},execution:{type:'platform'},request:{requestId:'test',traceId:'test',startedAt:new Date().toISOString()},authorize:async permissionCode=>({id:'test',allowed:true,reasonCode:'allowed',permissionCode,subjectType:'administrator',effectiveScopes:[],decidedAt:new Date().toISOString()})};
test('employee login → real Gateway directory data; role/app intersection, service identity and revocation',async()=>{
 const pg=new PGlite();
 const db={query:async(sql:string,args?:readonly unknown[])=>args?pg.query(sql,[...args]):(await pg.exec(sql)).at(-1)!,release(){}};
 const pool={...db,connect:async()=>db};const app=Fastify();
 try{
  await initializePlatformDatabase(db);
  await pg.query("INSERT INTO platform_organization_units(id,code,name,unit_type,status,created_at,updated_at) VALUES($1,'team','Team','workgroup','active',now(),now())",[org]);
  await pg.query("INSERT INTO platform_positions(id,code,name,status,created_at,updated_at) VALUES($1,'worker','Worker','active',now(),now())",[position]);
  await pg.query("INSERT INTO platform_people(id,employee_no,name,organization_unit_id,position_id,employment_status,created_at,updated_at) VALUES($1,'001','Employee',$2,$3,'active',now(),now())",[person,org,position]);
  for(const [id,code]of [[place,'station-one'],[otherPlace,'station-two']])await pg.query("INSERT INTO platform_locations(id,code,name,location_type,status,created_at,updated_at) VALUES($1,$2,$2,'station','active',now(),now())",[id,code]);
  const people=createPostgresPeopleDirectoryRepository(db),authorization=createAuthorizationService(createPostgresAuthorizationRepository(db),{findPerson:id=>people.findPersonById(id)});
  const registry=new AppRegistryService(new PostgresAppRegistryRepository(db),{authorization,host:()=>({platformVersion:'0.1.0',capabilities:[],applications:[]})});
  const manifest:AppManifest={manifestVersion:'1.0',id:'directory-reader',version:'1.0.0',name:'Reader',description:'Test',publisherId:'test',compatibility:{platform:{minInclusive:'0.0.1',maxExclusive:'2.0.0'},capabilities:[],applications:[]},permissions:{requested:['platform.locations.read','platform.assets.read'],defined:[]},ui:{mode:'none'},backend:{mode:'none'},storage:{mode:'none'},routes:[],api:[],navigation:[],events:{publish:[],subscribe:[]},tools:[],jobs:[],resources:[],artifacts:[],network:{frontendOrigins:[],backendOrigins:[]}};
  let installation=await registry.register(actor,manifest);installation=await registry.setEnabled(actor,manifest.id,installation.revision,true);
  const assetSys='51000000-0000-4000-8000-000000000010',assetCat='51000000-0000-4000-8000-000000000011',assetTyp='51000000-0000-4000-8000-000000000012',assetOne='51000000-0000-4000-8000-000000000013',assetTwo='51000000-0000-4000-8000-000000000014';
  await pg.query("INSERT INTO platform_asset_systems(id,code,name,status,created_at,updated_at) VALUES($1,'sys','Sys','active',now(),now())",[assetSys]);
  await pg.query("INSERT INTO platform_asset_categories(id,system_id,code,name,status,created_at,updated_at) VALUES($1,$2,'cat','Cat','active',now(),now())",[assetCat,assetSys]);
  await pg.query("INSERT INTO platform_asset_types(id,system_id,category_id,code,name,status,created_at,updated_at) VALUES($1,$2,$3,'typ','Typ','active',now(),now())",[assetTyp,assetSys,assetCat]);
  await pg.query("INSERT INTO platform_assets(id,system_id,category_id,type_id,location_id,display_name,asset_code,lifecycle_state,data_quality_status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,'Device 1','D1','active','verified',now(),now())",[assetOne,assetSys,assetCat,assetTyp,place]);
  await pg.query("INSERT INTO platform_assets(id,system_id,category_id,type_id,location_id,display_name,asset_code,lifecycle_state,data_quality_status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,'Device 2','D2','active','verified',now(),now())",[assetTwo,assetSys,assetCat,assetTyp,otherPlace]);
  const service=new EmployeeIdentityService(pool),account=await service.create(actor,{personId:person,username:'employee',password:'employee-test-password'});
  const access=new EmployeeAppAccess(pool);
  const denied={...actor,authorize:async(code:string)=>({...await actor.authorize(code,{}),allowed:false})};
  await assert.rejects(service.list(denied,{}),/EMPLOYEE_MANAGEMENT_DENIED/);
  const listed=await service.list(actor,{search:'001',page:1,pageSize:1});assert.equal(listed.total,1);assert.equal(listed.accounts[0].personName,'Employee');assert.equal('password_hash' in listed.accounts[0],false);
  assert.equal((await service.list(actor,{search:'%',page:1})).total,0);
  await assert.rejects(service.list(actor,{pageSize:101}));
  await assert.rejects(access.assert(manifest.id,person),/EMPLOYEE_APP_ACCESS_DENIED/);
  await assert.rejects(access.set(denied,manifest.id,{personId:person,enabled:true,revision:null}),/EMPLOYEE_MANAGEMENT_DENIED/);
  const grant=await access.set(actor,manifest.id,{personId:person,enabled:true,revision:null});
  assert.equal((await access.assert(manifest.id,person)).revision,grant.revision);
  assert.deepEqual(await access.candidates(person),[{appId:manifest.id}]);
  await assert.rejects(access.set(actor,manifest.id,{personId:person,enabled:false,revision:null}),/STALE_REVISION/);
  assert.equal((await pg.query("SELECT target_id FROM platform_admin_audit WHERE action='employee.app_access.grant'")).rows[0].target_id,`${installation.id}:${person}`);
  const revoked=await access.set(actor,manifest.id,{personId:person,enabled:false,revision:grant.revision});
  await assert.rejects(access.assert(manifest.id,person),/EMPLOYEE_APP_ACCESS_DENIED/);
  assert.deepEqual(await access.candidates(person),[]);
  await access.set(actor,manifest.id,{personId:person,enabled:true,revision:revoked.revision});
  await assert.rejects(service.login({username:'employee',password:'x'.repeat(73)}));
  const gateway=createManagementGateway(pool),origin='http://127.0.0.1:3102';
  let apiCalls=0,apiFailure=false;
  await app.register(cookie);registerEmployeeRoutes(app,{origin,service,resolveAdmin:async()=>{throw new AdminIdentityError(401,'ADMIN_AUTH_REQUIRED');},management:{invokeEmployee:(id,resolve,request)=>gateway.invokeDelegatedFromSession(id,resolve,request),invokeEmployeeApi:async(id,resolve,request,binding)=>{apiCalls++;assert.equal(id,manifest.id);assert.equal(binding,'test-host-binding');assert.equal((await resolve()).userId,person);if(apiFailure)throw new AppStdioApiError('ACCESS_DENIED','unknown');return {ok:true};}} as AppManagement});await app.ready();
  const deniedAdmin=await app.inject({method:'POST',url:'/api/admin/employee-accounts',headers:{origin},payload:{personId:person,username:'test',password:'employee-test-password'}});
  assert.equal(deniedAdmin.statusCode,401);assert.equal(deniedAdmin.json().error,'ADMIN_AUTH_REQUIRED');
  await assert.rejects(service.create({...actor,authorize:async code=>({...await actor.authorize(code,{}),allowed:false})},{personId:person,username:'test',password:'employee-test-password'}),/EMPLOYEE_MANAGEMENT_DENIED/);
  const login=await app.inject({method:'POST',url:'/api/employee/auth/login',headers:{origin},payload:{username:'employee',password:'employee-test-password'}});assert.equal(login.statusCode,200,login.body);
  const session=login.cookies.find(c=>c.name===EMPLOYEE_SESSION_COOKIE)!;assert.ok(session);assert.equal(session.path,'/api/employee');
  const headers={origin,'x-mop-employee-admission':'test-host-binding',cookie:`${EMPLOYEE_SESSION_COOKIE}=${session.value}`};
  const apiPayload={apiId:'create',method:'POST',path:'/records',payload:{quantity:1}};
  const apiCall=(body:unknown=apiPayload,override:Record<string,string>=headers)=>app.inject({method:'POST',url:'/api/employee/apps/directory-reader/api',headers:override,payload:body as object});
  assert.equal((await apiCall()).statusCode,200);assert.equal(apiCalls,1);
  assert.equal((await apiCall({...apiPayload,employee:{personId:person}})).statusCode,400);
  assert.equal((await apiCall({apiId:'create',method:'POST',path:'/records'})).statusCode,400);
  assert.equal((await apiCall(apiPayload,{origin,cookie:headers.cookie})).statusCode,400);
  assert.equal((await apiCall(apiPayload,{...headers,origin:'https://evil.example'})).statusCode,403);
  assert.equal((await apiCall(apiPayload,{origin,'x-mop-employee-admission':'test-host-binding',cookie:`afc_admin_session=${session.value}`})).statusCode,401);assert.equal(apiCalls,1);
  apiFailure=true;const failedApi=await apiCall();assert.equal(failedApi.statusCode,403);assert.equal(failedApi.json().error.writeOutcome,'unknown');apiFailure=false;
  const payload={version:'1.0',operation:'platform.locations.get',params:{id:place}};
  const call=(body:unknown=payload)=>app.inject({method:'POST',url:'/api/employee/apps/directory-reader/gateway',headers,payload:body as object});
  assert.equal((await app.inject({method:'POST',url:'/api/employee/apps/directory-reader/gateway',headers:{origin,cookie:headers.cookie},payload})).statusCode,400);
  assert.equal((await app.inject({method:'GET',url:'/api/admin/employee-accounts',headers:{cookie:headers.cookie}})).statusCode,401);
  assert.equal((await call()).statusCode,403);
  const permission=(await authorization.listPermissions()).find(p=>p.code==='platform.locations.read')!;
  await authorization.assignRole({personId:person,roleId:AUTHORIZATION_ROLE_SEEDS[2].id});
  await authorization.grantRolePermission({roleId:AUTHORIZATION_ROLE_SEEDS[2].id,permissionId:permission.id,scope:{kind:'explicit',targets:[{type:'location',id:place}]}});
  assert.equal((await call()).statusCode,403);
  installation=await registry.approveGrant(actor,manifest.id,installation.revision,{mode:'delegated_user',permissionCode:permission.code,scope:{kind:'all',targets:[]}});
  const result=await call();assert.equal(result.statusCode,200,result.body);assert.equal(result.json().result.id,place);
  const apiAuthorization=createManagementApiAuthorization(pool);
  const apiActor=await apiAuthorization.contextResolver.resolve({actorType:'person',trustedIdentity:{source:'session',userId:person},execution:{type:'application',appId:manifest.id},requestId:'api-test',traceId:'api-test'});
  // No resource adapter: a scoped role cannot become unrestricted through a payload claim.
  assert.equal(await apiAuthorization.authorize(apiActor,permission.code),false);
  await authorization.grantRolePermission({roleId:AUTHORIZATION_ROLE_SEEDS[2].id,permissionId:permission.id,scope:{kind:'all',targets:[]}});
  assert.equal(await apiAuthorization.authorize(apiActor,permission.code),true);
  const listRequest={version:'1.0',operation:'platform.locations.list',params:{pageSize:1}};
  const firstPage=await call(listRequest);assert.equal(firstPage.statusCode,200,firstPage.body);
  assert.equal(firstPage.json().result.rows.length,1);assert.equal(firstPage.json().result.nextCursor,place);
  const secondPage=await call({...listRequest,params:{pageSize:1,afterId:place}});assert.equal(secondPage.json().result.rows[0].id,otherPlace);assert.equal(secondPage.json().result.nextCursor,null);
  const emptyPage=await call({...listRequest,params:{afterId:otherPlace}});assert.deepEqual(emptyPage.json().result.rows,[]);
  assert.deepEqual((await call({...listRequest,params:{search:'%'}})).json().result.rows,[]);
  assert.equal((await call({...listRequest,params:{pageSize:51}})).statusCode,400);
  await pg.query('UPDATE platform_locations SET organization_unit_id=$1 WHERE id=$2',[org,place]);
  await authorization.grantRolePermission({roleId:AUTHORIZATION_ROLE_SEEDS[2].id,permissionId:permission.id,scope:{kind:'organization',targets:[]}});
  const scopedPage=await call({...listRequest,params:{organizationUnitId:org}});assert.equal(scopedPage.statusCode,200,scopedPage.body);assert.deepEqual(scopedPage.json().result.rows.map((r:{id:string})=>r.id),[place]);
  assert.equal((await call({...listRequest,params:{organizationUnitId:org,afterId:place}})).statusCode,200);
  assert.equal((await call({...listRequest,params:{organizationUnitId:otherPlace}})).statusCode,403);
  assert.equal((await call(listRequest)).statusCode,403);
  await pg.query('UPDATE platform_locations SET organization_unit_id=NULL WHERE id=$1',[place]);

  const assetPerm=(await authorization.listPermissions()).find(p=>p.code==='platform.assets.read')!;
  installation=await registry.approveGrant(actor,manifest.id,installation.revision,{mode:'delegated_user',permissionCode:assetPerm.code,scope:{kind:'all',targets:[]}});
  await authorization.grantRolePermission({roleId:AUTHORIZATION_ROLE_SEEDS[2].id,permissionId:assetPerm.id,scope:{kind:'all',targets:[]}});
  const assetListReq={version:'1.0',operation:'platform.assets.list',params:{pageSize:1}};
  const assetPage1=await call(assetListReq);assert.equal(assetPage1.statusCode,200,assetPage1.body);
  assert.equal(assetPage1.json().result.rows.length,1);assert.equal(assetPage1.json().result.nextCursor,assetOne);
  const assetPage2=await call({...assetListReq,params:{pageSize:1,afterId:assetOne}});
  assert.equal(assetPage2.json().result.rows[0].id,assetTwo);assert.equal(assetPage2.json().result.nextCursor,null);
  assert.deepEqual(Object.keys(assetPage1.json().result.rows[0]).sort(),['assetCode','displayName','id','lifecycleState','locationId','organizationUnitId','typeId']);
  assert.deepEqual((await call({...assetListReq,params:{search:'Device 1'}})).json().result.rows.map((r:{id:string})=>r.id),[assetOne]);


  await authorization.grantRolePermission({roleId:AUTHORIZATION_ROLE_SEEDS[2].id,permissionId:permission.id,scope:{kind:'explicit',targets:[{type:'location',id:place}]}});
  assert.equal(await apiAuthorization.authorize(apiActor,permission.code),false);
  assert.equal((await call({version:'1.0',operation:'platform.locations.list',params:{}})).statusCode,403);

  assert.deepEqual(Object.keys(result.json().result).sort(),['code','id','locationType','name','organizationUnitId','status']);
  assert.equal((await call({...payload,params:{id:otherPlace}})).statusCode,403);
  assert.equal((await call({...payload,params:{id:place,organizationUnitId:org}})).statusCode,400);
  assert.equal((await app.inject({method:'POST',url:'/api/employee/apps/directory-reader/gateway',headers:{origin,cookie:`afc_admin_session=${session.value}`},payload})).statusCode,401);
  assert.equal((await app.inject({method:'POST',url:'/api/employee/apps/directory-reader/gateway',headers:{...headers,origin:'https://evil.example'},payload})).statusCode,403);
  const issued=await registry.issueServiceCredential(actor,manifest.id,installation.revision);installation=issued.installation;
  await assert.rejects(gateway.invokeService(manifest.id,issued.credential,payload));
  installation=await registry.approveGrant(actor,manifest.id,installation.revision,{mode:'service',serviceIdentityId:installation.serviceIdentityId!,permissionCode:permission.code,scope:{kind:'explicit',targets:[{type:'location',id:place}]}});
  assert.equal((await gateway.invokeService(manifest.id,issued.credential,payload)).result.id,place);
  await assert.rejects(gateway.invokeService(manifest.id,issued.credential,{...payload,params:{id:otherPlace}}));
  await authorization.revokeRolePermission(AUTHORIZATION_ROLE_SEEDS[2].id,permission.id);assert.equal((await call()).statusCode,403);
  assert.equal((await gateway.invokeService(manifest.id,issued.credential,payload)).result.id,place);
  await service.update(actor,account.id,{status:'disabled'});assert.equal((await apiCall()).statusCode,401);assert.equal(await service.authenticate(session.value),null);assert.equal((await call()).statusCode,401);
  await service.update(actor,account.id,{status:'active'});
  assert.equal(await service.authenticate(session.value),null);
  const newLogin=await service.login({username:'employee',password:'employee-test-password'});
  const profile=await service.profile(newLogin.token);assert.equal(profile.name,'Employee');assert.equal(profile.employeeNo,'001');assert.equal('password_hash' in profile,false);
  assert.deepEqual(await service.notifications(newLogin.token),{notifications:[]});
  await assert.rejects(service.profile('invalid'),/EMPLOYEE_AUTH_REQUIRED/);await assert.rejects(service.notifications('invalid'),/EMPLOYEE_AUTH_REQUIRED/);
  await service.logout(newLogin.token);assert.equal(await service.authenticate(newLogin.token),null);
  const resetLogin=await service.login({username:'employee',password:'employee-test-password'});
  await service.update(actor,account.id,{password:'changed-employee-password'});
  assert.equal(await service.authenticate(resetLogin.token),null);
  await assert.rejects(service.login({username:'employee',password:'employee-test-password'}),/EMPLOYEE_LOGIN_FAILED/);
  const activeLogin=await service.login({username:'employee',password:'changed-employee-password'});
  await pg.query("UPDATE platform_people SET employment_status='departed' WHERE id=$1",[person]);
  await assert.rejects(access.assert(manifest.id,person),/EMPLOYEE_APP_ACCESS_DENIED/);
  assert.equal(await service.authenticate(activeLogin.token),null);
  await assert.rejects(service.login({username:'employee',password:'changed-employee-password'}),/EMPLOYEE_LOGIN_FAILED/);
  installation=await registry.setEnabled(actor,manifest.id,installation.revision,false);await assert.rejects(gateway.invokeService(manifest.id,issued.credential,payload));
  assert.ok((await pg.query('SELECT id FROM core_technical_audit')).rows.length>0);
 }finally{await app.close();await pg.close();}
});
