import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import Fastify from 'fastify';
import {initializePlatformDatabase} from '../src/setup/schema.ts';import {RegistrationService,registerRegistrationRoutes} from '../src/platform/employee-identity/registration.ts';import {EmployeeIdentityService} from '../src/platform/employee-identity/index.ts';import type {PlatformAdministratorContext} from '../src/platform/context/index.ts';
const org='51000000-0000-4000-8000-000000000001',position='51000000-0000-4000-8000-000000000002';
const actor:PlatformAdministratorContext={actorType:'administrator',administrator:{id:'51000000-0000-4000-8000-000000000003',username:'admin',displayName:'Admin'},execution:{type:'platform'},request:{requestId:'test',traceId:'test',startedAt:new Date().toISOString()},authorize:async permissionCode=>({id:'test',allowed:true,reasonCode:'allowed',permissionCode,subjectType:'administrator',effectiveScopes:[],decidedAt:new Date().toISOString()})};
test('registration requires fresh single-use challenge and atomic native administrator approval',async()=>{
 const pg=new PGlite();const db={query:async(sql:string,args?:readonly unknown[])=>args?pg.query(sql,[...args]):(await pg.exec(sql)).at(-1)!,release(){}};const pool={...db,connect:async()=>db};const service=new RegistrationService(pool),identity=new EmployeeIdentityService(pool);
 try{await initializePlatformDatabase(db);assert.deepEqual(await initializePlatformDatabase(db),[]);
 await pg.query("INSERT INTO platform_organization_units(id,code,name,unit_type,status,created_at,updated_at) VALUES($1,'test','Team','workgroup','active',now(),now())",[org]);await pg.query("INSERT INTO platform_positions(id,code,name,status,created_at,updated_at) VALUES($1,'test','Worker','active',now(),now())",[position]);
 const input={employeeNo:'Worker-001',name:'测试员工',phone:'13800000000',wecomUserId:'worker001',organizationId:org,password:'test-register-password'};
 const challenge=async()=>{const c=await service.challenge();await pg.query("UPDATE platform_registration_challenges SET created_at=now()-interval '1 second' WHERE id=$1",[c.id]);return {challengeId:c.id,slider:c.target};};
 const c=await challenge();await assert.rejects(service.submit({...input,...c,slider:0}),/REGISTRATION_CHALLENGE_FAILED/);await assert.rejects(service.submit({...input,...c}),/REGISTRATION_CHALLENGE_FAILED/);
 const expired=await challenge();await pg.query("UPDATE platform_registration_challenges SET expires_at=now()-interval '1 second' WHERE id=$1",[expired.challengeId]);await assert.rejects(service.submit({...input,...expired}),/REGISTRATION_CHALLENGE_FAILED/);
 assert.deepEqual(await service.submit({...input,...await challenge()}),{status:'pending'});await assert.rejects(identity.login({username:'worker-001',password:input.password}),/EMPLOYEE_LOGIN_FAILED/);await assert.rejects(service.submit({...input,...await challenge()}),/REGISTRATION_CONFLICT/);
 const list=await service.list(actor,1);assert.equal(list.total,1);assert.ok(!JSON.stringify(list).includes('password'));const id=list.applications[0].id as string;
 const denied={...actor,authorize:async(permission:string)=>({...await actor.authorize(permission,{}),allowed:false})};await assert.rejects(service.list(denied,1),/REGISTRATION_DENIED/);await assert.rejects(service.review(denied,id,{decision:'reject'}),/REGISTRATION_DENIED/);
 await pg.query("UPDATE platform_positions SET status='inactive' WHERE id=$1",[position]);await assert.rejects(service.review(actor,id,{decision:'approve',organizationId:org,positionId:position}),/REGISTRATION_ASSIGNMENT_INACTIVE/);assert.equal((await service.list(actor,1)).total,1);await pg.query("UPDATE platform_positions SET status='active' WHERE id=$1",[position]);
 await service.review(actor,id,{decision:'approve',organizationId:org,positionId:position});await assert.rejects(service.review(actor,id,{decision:'reject'}),/REGISTRATION_ALREADY_REVIEWED/);assert.equal((await identity.login({username:'worker-001',password:input.password})).account.status,'active');
 assert.equal((await pg.query('SELECT password_hash FROM platform_employee_registrations WHERE id=$1',[id])).rows[0].password_hash,null);assert.equal((await pg.query('SELECT verified_at FROM platform_external_identities')).rows[0].verified_at,null);
 await service.submit({...input,employeeNo:'worker-002',wecomUserId:'',...await challenge()});const second=(await service.list(actor,1)).applications[0].id as string;await service.review(actor,second,{decision:'reject'});await assert.rejects(identity.login({username:'worker-002',password:input.password}),/EMPLOYEE_LOGIN_FAILED/);await service.submit({...input,employeeNo:'worker-002',wecomUserId:'',...await challenge()});
 const app=Fastify();await registerRegistrationRoutes(app,{pool,origin:'https://platform.test',resolveAdmin:async()=>denied});await app.ready();assert.equal((await app.inject({method:'POST',url:'/api/auth/registration/challenge',headers:{origin:'https://other.test'},payload:{}})).statusCode,403);assert.equal((await app.inject('/api/admin/registrations')).statusCode,403);assert.equal((await app.inject('/api/auth/registration/organizations')).statusCode,200);await app.close();
 }finally{await pg.close();}
});
