import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import {initializePlatformDatabase} from '../src/setup/schema.ts';
import {EmployeeIdentityService,EMPLOYEE_SESSION_COOKIE} from '../src/platform/employee-identity/index.ts';
import {AdminIdentityError} from '../src/core/admin-identity/index.ts';
import {registerEmployeeRoutes} from '../src/app-platform/employee/routes.ts';
import {createManagementGateway} from '../src/app-platform/management/gateway.ts';
import {AppRegistryService,PostgresAppRegistryRepository} from '../src/app-platform/registry/index.ts';
import {createAuthorizationService,createPostgresAuthorizationRepository,AUTHORIZATION_ROLE_SEEDS} from '../src/platform/authorization/index.ts';
import {createPostgresPeopleDirectoryRepository} from '../src/platform/people/index.ts';
import type {PlatformAdministratorContext} from '../src/platform/context/index.ts';
import type {AppManifest} from '../src/app-platform/manifest/index.ts';
import type {AppManagement} from '../src/app-platform/management/service.ts';

const org='51000000-0000-4000-8000-000000000001',person='51000000-0000-4000-8000-000000000002',position='51000000-0000-4000-8000-000000000003',place='51000000-0000-4000-8000-000000000004',otherPlace='51000000-0000-4000-8000-000000000005';
const actor:PlatformAdministratorContext={actorType:'administrator',administrator:{id:'51000000-0000-4000-8000-000000000006',username:'admin',displayName:'Admin'},execution:{type:'platform'},request:{requestId:'test',traceId:'test',startedAt:new Date().toISOString()},authorize:async permissionCode=>({id:'test',allowed:true,reasonCode:'allowed',permissionCode,subjectType:'administrator',effectiveScopes:[],decidedAt:new Date().toISOString()})};
test('employee login → real Gateway directory data; role/app intersection, service identity and revocation',async()=>{
 const pg=new PGlite();
 const db={query:async(sql:string,args?:readonly unknown[])=>args?pg.query(sql,[...args]):(await pg.exec(sql)).at(-1)!,release(){}};
 const pool={...db,connect:async()=>db};const app=Fastify();
 try{
  await initializePlatformDatabase(db);
  await pg.query("INSERT INTO platform_organization_units(id,code,name,unit_type,status,created_at,updated_at) VALUES($1,'team','Team','workgroup','active',now(),now())",[org]);
  await pg.query("INSERT INTO platform_positions(id,code,name,status,created_at,updated_at) VALUES($1,'worker','Worker','active',now(),now())",[position]);
  await pg.query("INSERT INTO platform_people(id,employee_no,name,organization_unit_id,position_id,employment_status,created_at,updated_at) VALUES($1,'001','Employee',$2,$3,'active',now(),now())",[person,org,position]);
  for(const [id,code]of [[place,'station-one'],[otherPlace,'station-two']])await pg.query("INSERT INTO platform_locations(id,code,name,location_type,status,created_at,updated_at) VALUES($1,$2,$2,'station','active',now(),now())",[id,code]);
  const people=createPostgresPeopleDirectoryRepository(db),authorization=createAuthorizationService(createPostgresAuthorizationRepository(db),{findPerson:id=>people.findPersonById(id)});
  const registry=new AppRegistryService(new PostgresAppRegistryRepository(db),{authorization,host:()=>({platformVersion:'0.1.0',capabilities:[],applications:[]})});
  const manifest:AppManifest={manifestVersion:'1.0',id:'directory-reader',version:'1.0.0',name:'Reader',description:'Test',publisherId:'test',compatibility:{platform:{minInclusive:'0.0.1',maxExclusive:'2.0.0'},capabilities:[],applications:[]},permissions:{requested:['platform.locations.read'],defined:[]},ui:{mode:'none'},backend:{mode:'none'},storage:{mode:'none'},routes:[],api:[],navigation:[],events:{publish:[],subscribe:[]},tools:[],jobs:[],resources:[],artifacts:[],network:{frontendOrigins:[],backendOrigins:[]}};
  let installation=await registry.register(actor,manifest);installation=await registry.setEnabled(actor,manifest.id,installation.revision,true);
  const service=new EmployeeIdentityService(pool),account=await service.create(actor,{personId:person,username:'employee',password:'employee-test-password'});
  await assert.rejects(service.login({username:'employee',password:'x'.repeat(73)}));
  const gateway=createManagementGateway(pool),origin='http://127.0.0.1:3102';
  await app.register(cookie);registerEmployeeRoutes(app,{origin,service,resolveAdmin:async()=>{throw new AdminIdentityError(401,'ADMIN_AUTH_REQUIRED');},management:{invokeEmployee:(id,resolve,request)=>gateway.invokeDelegatedFromSession(id,resolve,request)} as AppManagement});await app.ready();
  const deniedAdmin=await app.inject({method:'POST',url:'/api/admin/employee-accounts',headers:{origin},payload:{personId:person,username:'test',password:'employee-test-password'}});
  assert.equal(deniedAdmin.statusCode,401);assert.equal(deniedAdmin.json().error,'ADMIN_AUTH_REQUIRED');
  await assert.rejects(service.create({...actor,authorize:async code=>({...await actor.authorize(code,{}),allowed:false})},{personId:person,username:'test',password:'employee-test-password'}),/EMPLOYEE_MANAGEMENT_DENIED/);
  const login=await app.inject({method:'POST',url:'/api/employee/auth/login',headers:{origin},payload:{username:'employee',password:'employee-test-password'}});assert.equal(login.statusCode,200,login.body);
  const session=login.cookies.find(c=>c.name===EMPLOYEE_SESSION_COOKIE)!;assert.ok(session);assert.equal(session.path,'/api/employee');
  const headers={origin,cookie:`${EMPLOYEE_SESSION_COOKIE}=${session.value}`};
  const payload={version:'1.0',operation:'platform.locations.get',params:{id:place}};
  const call=(body:unknown=payload)=>app.inject({method:'POST',url:'/api/employee/apps/directory-reader/gateway',headers,payload:body as object});
  assert.equal((await call()).statusCode,403);
  const permission=(await authorization.listPermissions()).find(p=>p.code==='platform.locations.read')!;
  await authorization.assignRole({personId:person,roleId:AUTHORIZATION_ROLE_SEEDS[2].id});
  await authorization.grantRolePermission({roleId:AUTHORIZATION_ROLE_SEEDS[2].id,permissionId:permission.id,scope:{kind:'explicit',targets:[{type:'location',id:place}]}});
  assert.equal((await call()).statusCode,403);
  installation=await registry.approveGrant(actor,manifest.id,installation.revision,{mode:'delegated_user',permissionCode:permission.code,scope:{kind:'all',targets:[]}});
  const result=await call();assert.equal(result.statusCode,200,result.body);assert.equal(result.json().result.id,place);
  assert.deepEqual(Object.keys(result.json().result).sort(),['code','id','locationType','name','organizationUnitId','status']);
  assert.equal((await call({...payload,params:{id:otherPlace}})).statusCode,403);
  assert.equal((await call({...payload,params:{id:place,organizationUnitId:org}})).statusCode,400);
  assert.equal((await app.inject({method:'POST',url:'/api/employee/apps/directory-reader/gateway',headers:{origin,cookie:`afc_admin_session=${session.value}`},payload})).statusCode,401);
  assert.equal((await app.inject({method:'POST',url:'/api/employee/apps/directory-reader/gateway',headers:{...headers,origin:'https://evil.example'},payload})).statusCode,403);
  const issued=await registry.issueServiceCredential(actor,manifest.id,installation.revision);installation=issued.installation;
  await assert.rejects(gateway.invokeService(manifest.id,issued.credential,payload));
  installation=await registry.approveGrant(actor,manifest.id,installation.revision,{mode:'service',serviceIdentityId:installation.serviceIdentityId!,permissionCode:permission.code,scope:{kind:'explicit',targets:[{type:'location',id:place}]}});
  assert.equal((await gateway.invokeService(manifest.id,issued.credential,payload)).result.id,place);
  await assert.rejects(gateway.invokeService(manifest.id,issued.credential,{...payload,params:{id:otherPlace}}));
  await authorization.revokeRolePermission(AUTHORIZATION_ROLE_SEEDS[2].id,permission.id);assert.equal((await call()).statusCode,403);
  assert.equal((await gateway.invokeService(manifest.id,issued.credential,payload)).result.id,place);
  await service.update(actor,account.id,{status:'disabled'});assert.equal(await service.authenticate(session.value),null);assert.equal((await call()).statusCode,401);
  await service.update(actor,account.id,{status:'active'});
  assert.equal(await service.authenticate(session.value),null);
  const newLogin=await service.login({username:'employee',password:'employee-test-password'});
  await service.logout(newLogin.token);assert.equal(await service.authenticate(newLogin.token),null);
  const resetLogin=await service.login({username:'employee',password:'employee-test-password'});
  await service.update(actor,account.id,{password:'changed-employee-password'});
  assert.equal(await service.authenticate(resetLogin.token),null);
  await assert.rejects(service.login({username:'employee',password:'employee-test-password'}),/EMPLOYEE_LOGIN_FAILED/);
  const activeLogin=await service.login({username:'employee',password:'changed-employee-password'});
  await pg.query("UPDATE platform_people SET employment_status='departed' WHERE id=$1",[person]);
  assert.equal(await service.authenticate(activeLogin.token),null);
  await assert.rejects(service.login({username:'employee',password:'changed-employee-password'}),/EMPLOYEE_LOGIN_FAILED/);
  installation=await registry.setEnabled(actor,manifest.id,installation.revision,false);await assert.rejects(gateway.invokeService(manifest.id,issued.credential,payload));
  assert.ok((await pg.query('SELECT id FROM core_technical_audit')).rows.length>0);
 }finally{await app.close();await pg.close();}
});
