import assert from 'node:assert/strict';import test from 'node:test';import{PGlite}from'@electric-sql/pglite';
import{PLATFORM_PEOPLE_DIRECTORY_MIGRATIONS,createPostgresPeopleDirectoryRepository}from'../src/platform/people/index.ts';
import{PLATFORM_LOCATION_DIRECTORY_MIGRATIONS,createPostgresLocationDirectoryRepository}from'../src/platform/locations/index.ts';
import{PLATFORM_ASSET_DIRECTORY_MIGRATIONS,createPostgresAssetDirectoryRepository}from'../src/platform/assets/index.ts';
import{PLATFORM_RESPONSIBILITY_MIGRATIONS,PLATFORM_RESPONSIBILITY_SQL,RESPONSIBILITY_AREA_SEEDS,ResponsibilityError,createMemoryResponsibilityRepository,createPostgresResponsibilityRepository,createResponsibilityService,reconcileLegacyResponsibilities}from'../src/platform/responsibility/index.ts';

const I={org:'30000000-0000-4000-8000-000000000010',org2:'30000000-0000-4000-8000-000000000011',person:'30000000-0000-4000-8000-000000000012',person2:'30000000-0000-4000-8000-000000000013',backup:'30000000-0000-4000-8000-000000000014',location:'30000000-0000-4000-8000-000000000015',child:'30000000-0000-4000-8000-000000000016',type:'30000000-0000-4000-8000-000000000017',asset:'30000000-0000-4000-8000-000000000018',scope:'30000000-0000-4000-8000-000000000019',scope2:'30000000-0000-4000-8000-00000000001a',primary:'30000000-0000-4000-8000-00000000001b',temporary:'30000000-0000-4000-8000-00000000001c'}as const;
const now='2026-08-31T02:00:00.000Z';
function memory(){const areas=RESPONSIBILITY_AREA_SEEDS.map(x=>({...x,description:null,status:'active'as const,createdAt:now,updatedAt:now}));const repository=createMemoryResponsibilityRepository({areas});let n=100;const service=createResponsibilityService(repository,{clock:()=>new Date(now),createId:()=>`30000000-0000-4000-8000-${String(n++).padStart(12,'0')}`,findOrganizationUnit:async id=>[I.org,I.org2].includes(id as any)?{status:'active'}:null,findPerson:async id=>id===I.person||id===I.backup?{organizationUnitId:I.org,employmentStatus:'active'}:id===I.person2?{organizationUnitId:I.org2,employmentStatus:'active'}:null,findLocation:async id=>id===I.location?{id,parentId:null,status:'active'}:id===I.child?{id,parentId:I.location,status:'active'}:null,findAssetType:async id=>id===I.type?{status:'active'}:null,findAsset:async id=>id===I.asset?{lifecycleState:'active'}:null});return{repository,service};}

test('four approved team responsibility areas are stable',async()=>{const{service}=memory();assert.deepEqual((await service.listAreas()).map(x=>x.code).sort(),['general_affairs_management','production_management','safety_management','training_management']);});
test('same target can be owned by several organizations but not duplicated within one organization',async()=>{const{service}=memory();await service.createScope({id:I.scope,organizationUnitId:I.org,target:{type:'location',id:I.location}});await service.createScope({id:I.scope2,organizationUnitId:I.org2,target:{type:'location',id:I.location}});await assert.rejects(service.createScope({organizationUnitId:I.org,target:{type:'location',id:I.location}}),(e:unknown)=>e instanceof ResponsibilityError&&e.code==='DUPLICATE_RESPONSIBILITY_SCOPE');});
test('scope supports area, location tree, asset type, and asset targets',async()=>{const{repository,service}=memory();await service.createScope({organizationUnitId:I.org,target:{type:'responsibility_area',id:RESPONSIBILITY_AREA_SEEDS[0].id}});await service.createScope({organizationUnitId:I.org,target:{type:'location',id:I.location,includeDescendants:true}});await service.createScope({organizationUnitId:I.org,target:{type:'asset_type',id:I.type}});await service.createScope({organizationUnitId:I.org,target:{type:'asset',id:I.asset}});assert.equal(repository.records().scopes.length,4);});
test('primary, backups, and temporary agent obey overlap and same-organization rules',async()=>{const{repository,service}=memory();await service.createScope({id:I.scope,organizationUnitId:I.org,target:{type:'responsibility_area',id:RESPONSIBILITY_AREA_SEEDS[0].id}});await service.assignPerson({id:I.primary,scopeId:I.scope,personId:I.person,assignmentRole:'primary_owner'});await service.assignPerson({scopeId:I.scope,personId:I.backup,assignmentRole:'backup_owner'});await assert.rejects(service.assignPerson({scopeId:I.scope,personId:I.person2,assignmentRole:'backup_owner'}),(e:unknown)=>e instanceof ResponsibilityError&&e.code==='PERSON_ORGANIZATION_MISMATCH');await assert.rejects(service.assignPerson({scopeId:I.scope,personId:I.backup,assignmentRole:'primary_owner'}),(e:unknown)=>e instanceof ResponsibilityError&&e.code==='PRIMARY_OWNER_OVERLAP');assert.equal(repository.records().assignments.length,2);});
test('temporary agent overrides primary only during its effective period',async()=>{const{service}=memory();await service.createScope({id:I.scope,organizationUnitId:I.org,target:{type:'responsibility_area',id:RESPONSIBILITY_AREA_SEEDS[0].id}});await service.assignPerson({id:I.primary,scopeId:I.scope,personId:I.person,assignmentRole:'primary_owner',effectiveFrom:new Date('2026-01-01')});await service.assignPerson({id:I.temporary,scopeId:I.scope,personId:I.backup,assignmentRole:'temporary_agent',effectiveFrom:new Date('2026-09-01'),effectiveTo:new Date('2026-09-10')});assert.equal((await service.resolve(I.scope,new Date('2026-08-31'))).effectiveHandler?.personId,I.person);assert.equal((await service.resolve(I.scope,new Date('2026-09-05'))).effectiveHandler?.personId,I.backup);assert.equal((await service.resolve(I.scope,new Date('2026-09-10'))).effectiveHandler?.personId,I.person);await assert.rejects(service.assignPerson({scopeId:I.scope,personId:I.person,assignmentRole:'temporary_agent',effectiveFrom:new Date('2026-09-05'),effectiveTo:new Date('2026-09-08')}),(e:unknown)=>e instanceof ResponsibilityError&&e.code==='TEMPORARY_AGENT_OVERLAP');});
test('location descendant coverage follows the Location Directory parent chain',async()=>{const{service}=memory();await service.createScope({id:I.scope,organizationUnitId:I.org,target:{type:'location',id:I.location,includeDescendants:true}});assert.equal(await service.scopeCoversLocation(I.scope,I.child),true);});
test('legacy station responsibility reconciliation preserves assignments and finds invalid rows',()=>{const report=reconcileLegacyResponsibilities({organizationUnitIds:[I.org],locationIds:[I.location],people:[{id:I.person,organizationUnitId:I.org,employmentStatus:'active'},{id:I.person2,organizationUnitId:I.org2,employmentStatus:'inactive'}],rows:[{id:I.primary,organizationUnitId:I.org,locationId:I.location,personId:I.person},{id:I.temporary,organizationUnitId:I.org,locationId:I.location,personId:I.person2}]});assert.deepEqual(report.preservedAssignmentIds,[I.primary,I.temporary]);assert.deepEqual(report.issues.map(x=>x.code),['PERSON_ORGANIZATION_MISMATCH','PERSON_NOT_ACTIVE','DUPLICATE_ORGANIZATION_LOCATION']);});
test('responsibility migration seeds four areas and depends on three directories',()=>{const m=PLATFORM_RESPONSIBILITY_MIGRATIONS[0];assert.deepEqual(m.dependsOn,['platform-people-directory-expand','platform-location-directory-expand','platform-asset-directory-expand']);assert.match(PLATFORM_RESPONSIBILITY_SQL,/safety_management/);assert.match(PLATFORM_RESPONSIBILITY_SQL,/temporary_agent/);assert.doesNotMatch(PLATFORM_RESPONSIBILITY_SQL,/(permission|data_scope|app_grant)/i);});
test('responsibility migration and PostgreSQL repository run twice in isolated PGlite',async()=>{const db=new PGlite();const client={query(text:string,values?:readonly unknown[]){if(!values&&text.includes(';'))return db.exec(text);return db.query(text,values?[...values]:undefined);}};try{await PLATFORM_PEOPLE_DIRECTORY_MIGRATIONS[0].run({client});await PLATFORM_LOCATION_DIRECTORY_MIGRATIONS[0].run({client});await PLATFORM_ASSET_DIRECTORY_MIGRATIONS[0].run({client});await db.query(`INSERT INTO platform_organization_units(id,parent_id,code,name,short_name,unit_type,status,sort_order,created_at,updated_at)VALUES($1,NULL,'org','工班',NULL,'workgroup','active',0,NOW(),NOW())`,[I.org]);await db.query(`INSERT INTO platform_positions(id,code,name,description,status,created_at,updated_at)VALUES($1,'MAINTAINER','检修工',NULL,'active',NOW(),NOW())`,[I.type]);await db.query(`INSERT INTO platform_people(id,employee_no,name,phone,organization_unit_id,position_id,employment_status,avatar_url,created_at,updated_at)VALUES($1,'001','张三',NULL,$2,$3,'active',NULL,NOW(),NOW())`,[I.person,I.org,I.type]);await db.query(`INSERT INTO platform_locations(id,parent_id,organization_unit_id,code,name,short_name,location_type,status,sort_order,created_at,updated_at)VALUES($1,NULL,NULL,'station:a','车站',NULL,'station','active',0,NOW(),NOW())`,[I.location]);await PLATFORM_RESPONSIBILITY_MIGRATIONS[0].run({client});await PLATFORM_RESPONSIBILITY_MIGRATIONS[0].run({client});const repo=createPostgresResponsibilityRepository(client),people=createPostgresPeopleDirectoryRepository(client),locations=createPostgresLocationDirectoryRepository(client),assets=createPostgresAssetDirectoryRepository(client);const service=createResponsibilityService(repo,{findOrganizationUnit:id=>people.findOrganizationUnitById(id),findPerson:id=>people.findPersonById(id),findLocation:id=>locations.findLocationById(id),findAssetType:id=>assets.findTypeById(id),findAsset:id=>assets.findAssetById(id)});await service.createScope({id:I.scope,organizationUnitId:I.org,target:{type:'location',id:I.location}});await service.assignPerson({id:I.primary,scopeId:I.scope,personId:I.person,assignmentRole:'primary_owner'});assert.equal((await service.resolve(I.scope)).effectiveHandler?.personId,I.person);assert.equal((await repo.listAreas()).length,4);}finally{await db.close();}});
