/** Public application integration reference. Internal platform modules are deliberately excluded.
 * This describes the version's supported surface, not live grants or instance readiness. */
export interface AppOperationReference {
  id:string; title:string; group:string; entrypoint:string; call:string;
  permission:string; execution:'backend'|'employee-backend'|'sandbox'|'local'|'build';
  mode:'read'|'write'|'ui'; input:string; output:string; constraints:string;
  example:Record<string,unknown>;
}
const reference=(id:string,title:string,group:string,entrypoint:string,call:string,permission:string,execution:AppOperationReference['execution'],mode:AppOperationReference['mode'],input:string,output:string,constraints:string,example:Record<string,unknown>):AppOperationReference=>({id,title,group,entrypoint,call,permission,execution,mode,input,output,constraints,example});
const uuid='00000000-0000-4000-8000-000000000001';
const directory='@metro/platform-sdk/app-directory';
const gateway='@metro/platform-sdk/app-gateway';
export const PLATFORM_APP_OPERATIONS:readonly AppOperationReference[]=[
  reference('platform.people.members','工班人员','基础目录',directory,'createPlatformDirectoryClient(gateway).members(params)','platform.people.read','backend','read','organizationUnitId: UUID（必填）；personId?: UUID；personIds?: UUID[1..50]；search?: string（≤100）','{organizationUnitId, rows: {id,name,employeeNo,organizationUnitId}[]}','只返回在职、启用工班与岗位的人员；最多 50 人，无分页游标，不提供手机号或全员导出。personIds 优先于 personId。',{organizationUnitId:uuid}),
  reference('platform.people.organization_context','组织上下文','基础目录',directory,'createPlatformDirectoryClient(gateway).organizationContext(organizationUnitId)','platform.people.read','backend','read','organizationUnitId: UUID','{organizations: {id,name,unitType}[]}','从指定启用组织向上追溯，最多 32 级；不是全组织树查询。',{organizationUnitId:uuid}),
  reference('platform.locations.list','位置列表','基础目录',directory,'createPlatformDirectoryClient(gateway).locations(params)','platform.locations.read','backend','read','organizationUnitId?: UUID；pageSize?: 1..50（默认20）；afterId?: UUID；search?: string（≤100）；status?: active|inactive','{organizationUnitId, rows: {id,code,name,locationType,status,organizationUnitId}[], nextCursor: UUID|null}','使用 nextCursor 作为下一次 afterId；有范围授权时必须传入允许的组织。',{organizationUnitId:uuid,pageSize:20}),
  reference('platform.locations.get','位置详情','基础目录',directory,'createPlatformDirectoryClient(gateway).location(id)','platform.locations.read','backend','read','id: UUID','{id,code,name,locationType,status,organizationUnitId}','资源和返回结果均检查授权范围。',{id:uuid}),
  reference('platform.locations.responsible_stations','工班管辖线路与车站','基础目录',directory,'createPlatformDirectoryClient(gateway).responsibleStations(params)','platform.locations.read','backend','read','organizationUnitId: UUID；lineName?: string（≤100）；stationId?: UUID；search?: string（≤100）','{organizationUnitId, lines: {id,name}[], stations: {id,name,lineId,lineName}[]}','查询已配置的工班管辖关系；线路、车站各最多 50 条，不是全平台基础数据管理接口。',{organizationUnitId:uuid}),
  reference('platform.assets.list','设备列表','基础目录',directory,'createPlatformDirectoryClient(gateway).assets(params)','platform.assets.read','backend','read','organizationUnitId?: UUID；pageSize?: 1..50；afterId?: UUID；search?: string；locationId?: UUID；typeId?: UUID；typeName?: string；lifecycleState?: planned|active|suspended|retired','{organizationUnitId, rows: {id,displayName,assetCode,locationId,typeId,typeName,lifecycleState,organizationUnitId}[], nextCursor: UUID|null}','默认每页20条；搜索和类型名称≤100字符；返回前再次检查资源范围。',{organizationUnitId:uuid,pageSize:20}),
  reference('platform.assets.get','设备详情','基础目录',directory,'createPlatformDirectoryClient(gateway).asset(id)','platform.assets.read','backend','read','id: UUID','{id,displayName,assetCode,locationId,typeId,lifecycleState,organizationUnitId}','详情没有 typeName；位置、设备和设备类型一起参与范围校验。',{id:uuid}),
  reference('platform.app_data.list','托管数据查询','应用存储',gateway,'createAppDataClient(gateway).list(table, options)','platform.app_data.read','backend','read','table: string；options: AppDataListOptions（筛选、排序、游标、分页）','{rows, nextCursor}；字段由本应用迁移定义','须启用托管存储，service/all 授权；只访问本应用私有表。业务范围由应用过滤后再分页。',{table:'records',pageSize:20}),
  reference('platform.app_data.get','托管记录详情','应用存储',gateway,'createAppDataClient(gateway).get(table, id)','platform.app_data.read','backend','read','table: string；id: string','{row: 记录对象|null}','先校验员工对业务资源的访问范围。',{table:'records',id:uuid}),
  reference('platform.app_data.read_batch','批量读取','应用存储',gateway,'createAppDataClient(gateway).readBatch(operations)','platform.app_data.read','backend','read','operations: AppDataRead[]（get、ids 或分页列表）','{results: ({row}|{rows,nextCursor?})[]}','具体边界见托管数据指南；结果超过上限需缩小批次，不能截断成成功结果。',{operations:[{table:'records',id:uuid}]}),
  reference('platform.app_data.write','单项数据写入','应用存储',gateway,'createAppDataClient(gateway).insert(table, id, requestId, values)','platform.app_data.write','backend','write','table、id、requestId；action: insert|update|delete；values: JSON对象（删除除外）','{row: 记录对象|null}','update/delete 同一客户端也提供；并发修改优先使用带 expected 的 transaction。未知结果不自动重试。',{table:'records',id:uuid,requestId:uuid,action:'insert',values:{title:'示例'}}),
  reference('platform.app_data.transaction','原子多项写入','应用存储',gateway,'createAppDataClient(gateway).transaction(requestId, operations)','platform.app_data.write','backend','write','requestId: string；operations: AppDataMutation[]；update/delete 必须有 expected','{results: {row}[]}','同应用同事务；按员工业务范围授权；读写大小、数量上限见存储指南。',{requestId:uuid,operations:[{action:'insert',table:'records',id:uuid,values:{title:'示例'}}]}),
  reference('platform.signatures.associate','关联记录签字','签字与提醒',gateway,'createPlatformSignaturesClient(gateway).associate(params)','platform.signatures.create','employee-backend','write','entityId: UUID；title: string（1..200）；organizationUnitId: UUID；personIds: UUID[1..100]','{associated, signers: {personId,name,status,signedAt}[]}','记录签字能力，不是任意 PDF 电子签章；应用核对记录及签字人范围。',{entityId:uuid,title:'记录签字',organizationUnitId:uuid,personIds:[uuid]}),
  reference('platform.signatures.get','查询记录签字','签字与提醒',gateway,'createPlatformSignaturesClient(gateway).get(entityId, signal, evidencePersonId)','platform.signatures.read','employee-backend','read','entityId: UUID；evidencePersonId?: UUID','{associated,signers,image?}','image 仅请求指定证据时返回；签字人不存在或未签可能为 null。',{entityId:uuid}),
  reference('platform.signatures.sign','本人签字','签字与提醒',gateway,'createPlatformSignaturesClient(gateway).sign(entityId, image)','platform.signatures.sign','employee-backend','write','entityId: UUID；image: PNG data URL','{associated,signers}','签字身份来自宿主；PNG ≤32KiB、宽≤2048、高≤1024；不能传人员ID代签。',{entityId:uuid,image:'<员工选择并确认的 PNG data URL>'}),
  reference('platform.notifications.publish','发送应用站内通知','通知',gateway,'createPlatformNotificationsClient(gateway).publish(params)','platform.notifications.create','employee-backend','write','id、entityId: UUID；entityType: 1..64字符标识；personIds: UUID[1..50]（去重）；title: 1..160字符；body: 1..1000字符；routeId?: 本应用路由ID','{id}','来源应用由宿主绑定；仅站内通知；接收人须在职且组织启用。跳转只接受本应用清单中的路由，不能传任意URL。应用负责业务通知对象授权；写入未知不重试。',{id:uuid,entityType:'record',entityId:uuid,personIds:[uuid],title:'记录已更新',body:'请查看应用中的记录',routeId:'home'}),
  reference('platform.notifications.create','签字站内提醒','签字与提醒',gateway,'createPlatformNotificationsClient(gateway).create(params)','platform.notifications.create','employee-backend','write','id、entityId、personId: UUID；title: 1..160字符；body: 1..1000字符','{id}','当前固定为签字提醒，跳转本应用 /sign?task=entityId；不是通用通知模板接口。',{id:uuid,entityId:uuid,personId:uuid,title:'待签字',body:'请查看记录'}),
  reference('platform.notifications.cancel','撤销本应用通知','通知',gateway,'createPlatformNotificationsClient(gateway).cancel(id)','platform.notifications.manage','employee-backend','write','id: UUID','{cancelled:true}','撤销本应用创建的通用站内通知或兼容签字提醒；不能撤销其他应用通知。',{id:uuid}),
  reference('platform.webhook.send','机器人消息','集成',gateway,'createPlatformWebhookClient(gateway).send(params)','platform.notifications.create','backend','write','url: string（≤2048）；message: 1..12000字符；messageType?: text|markdown','{sent:true}','仅平台允许的企业微信/钉钉机器人地址；钉钉仅 text；Webhook URL 含密钥，不能放示例、日志或安装包。',{url:'<管理员提供的机器人地址>',message:'经用户确认的通知',messageType:'text'}),
  reference('platform.ai.complete','文本生成','集成',gateway,'createPlatformAiClient(gateway).complete(params)','platform.ai.complete','backend','read','system: 1..3000字符；prompt: 1..12000字符','{content:string}','管理员须配置模型；不提供模型密钥；不代表结构化输出、工具调用或任意模型选择。',{system:'概括内容，保留事实。',prompt:'需要概括的业务文本'}),
  reference('platform.apps.invoke','调用应用开放接口','应用互通',gateway,'createAppCapabilityClient(gateway).call(appId, apiId, params)','platform.apps.invoke + 目标业务权限','employee-backend','write','appId、apiId、params（以提供方契约为准）','提供方业务 API 返回值','读写性质以提供方为准；须声明应用版本依赖，负责人开放、员工目标角色和数据范围仍独立校验；不支持外部系统和无人值守任务。',{appId:'provider-app',apiId:'list',params:{}}),
  reference('application.api.<apiId>','调用本应用后端','宿主交互','@metro/platform-sdk/app-sandbox','createAppApiClient(sandbox).invoke(apiId, params)','本应用 API 的业务权限','sandbox','write','apiId、params（以本应用清单和 handler 为准）','返回本应用 handler 定义的 JSON；推荐 {ok:true,result} / {ok:false,error:{code,writeOutcome}}','读写性质由本应用定义；需处理业务错误和通道错误，不使用管理员会话或直接 fetch 平台内部路由。',{apiId:'list',params:{}}),
  reference('platform.ui.theme','宿主主题','宿主交互','@metro/platform-sdk/app-sandbox',"sandbox.invoke('platform.ui.theme', {})",'宿主准入','sandbox','ui','{}','{theme: light|dark}','主题由宿主同步；使用共享 CSS 变量。',{}),
  reference('platform.ui.modal','弹窗宿主同步','宿主交互','@metro/platform-sdk/app-sandbox',"sandbox.invoke('platform.ui.modal', {open:true})",'宿主准入','sandbox','ui','open: boolean','宿主确认结果','打开/关闭共享弹窗时通知宿主；无业务授权作用。',{open:true}),
  reference('platform.ui.navigation','导航可见性','宿主交互','@metro/platform-sdk/app-sandbox',"sandbox.invoke('platform.ui.navigation', {ids})",'宿主准入及路由权限','sandbox','ui','ids: 本应用 navigation 中的 ID[]','宿主确认结果','只能收窄清单中的导航；不能授予未授权路由。安装侧栏由 routes/navigation 声明生成。',{ids:['home']}),
  reference("readSandboxFile","本地文件读取（二进制）","文件读取与下载","@metro/platform-sdk/app-files","await readSandboxFile(file, {maxBytes: 5 * 1024 * 1024, extensions: [\".xlsx\", \".xls\"]})","无需服务授权；用户选择文件","local","read","file: 用户选择的 File；options.maxBytes: 1..50MiB；extensions?: 后缀数组","Uint8Array","仅在应用本地读取，不上传、不存放、不解析业务内容；后缀检查不等于内容格式验证。",{"maxBytes": 5242880, "extensions": [".xlsx", ".xls"]}),
  reference("readSandboxTextFile","文本与 CSV 文件读取","文件读取与下载","@metro/platform-sdk/app-files","await readSandboxTextFile(file, {maxBytes: 2000000, extensions: [\".csv\", \".txt\"]})","无需服务授权","local","read","file: File；options 与 readSandboxFile 相同","string（严格 UTF-8，去除 BOM）","CSV 返回文本，分隔符和字段规则由应用处理；非法 UTF-8 抛 INVALID_TEXT。不会自动上传。",{"maxBytes": 2000000, "extensions": [".csv", ".txt"]}),
  reference("downloadSandboxFile","生成内容下载（Blob／字节）","文件读取与下载","@metro/platform-sdk/app-files","downloadSandboxFile(\"result.json\", new Blob([JSON.stringify(result)], {type: \"application/json\"}), \"application/json\")","清单 ui.downloads: true","local","ui","name: 安全文件名≤180字符；contents: Blob|Uint8Array|ArrayBuffer；contentType?: MIME","void（触发浏览器下载）","内容须由应用生成；1字节～50MiB，不上传、不长期存储。不提供 Word/PDF 自动生成器。",{"name": "result.json", "contentType": "application/json"}),
  reference("createSandboxAttachmentClient.upload","文件原件上传与存放","原件附件","@metro/platform-sdk/app-files","const attachments = createSandboxAttachmentClient(sandbox);\nawait attachments.upload(file, {entityType: \"record\", entityId, intentId});","platform.attachments.create + 记录业务权限","sandbox","write","file: File；entityType: 小写标识≤64；entityId、intentId: UUID","{attachmentId,fileName,sizeBytes,contentType}","支持 .doc/.docx/.xls/.xlsx/.pdf/.zip；单文件≤50MiB，每记录≤500个。宿主二进制通道私有存放，须实现 authorize-attachment；不解压或解析正文。未知结果通过列表 intentId 核对，禁止自动重传。",{"entityType": "record", "entityId": "00000000-0000-4000-8000-000000000001", "intentId": "00000000-0000-4000-8000-000000000001"}),
  reference("createSandboxAttachmentClient.list","查询记录附件","原件附件","@metro/platform-sdk/app-files","await createSandboxAttachmentClient(sandbox).list({entityType: \"record\", entityId, afterId})","platform.attachments.read + 记录业务权限","sandbox","read","entityType、entityId；afterId?: UUID","{attachments:[{attachmentId,intentId,fileName,contentType,sizeBytes,createdAt}],nextCursor}","每页最多50条，nextCursor 作为下一次 afterId；核对记录可见范围。",{"entityType": "record", "entityId": "00000000-0000-4000-8000-000000000001"}),
  reference("createSandboxAttachmentClient.read","读取文件原件","原件附件","@metro/platform-sdk/app-files","const {blob, fileName} = await createSandboxAttachmentClient(sandbox).read(attachmentId);","platform.attachments.read + 记录业务权限","sandbox","read","attachmentId: UUID","{blob: Blob,fileName: string}","宿主重新检查应用、员工和记录绑定；不暴露存储直链。可将 Excel Blob 交给公开解析工具；读取本身不解析内容。",{"attachmentId": "00000000-0000-4000-8000-000000000001"}),
  reference("createSandboxAttachmentClient.download","下载已存放的原件","原件附件","@metro/platform-sdk/app-files","await createSandboxAttachmentClient(sandbox).download(attachmentId);","platform.attachments.read + 记录业务权限；ui.downloads: true","sandbox","ui","attachmentId: UUID","void（下载原文件）","通过 read 验证并取回原件后下载；保留原文件名。没有通用删除附件接口。",{"attachmentId": "00000000-0000-4000-8000-000000000001"}),
  reference("createAppAttachmentAuthorizationHandler","附件业务授权处理器","原件附件","@metro/platform-sdk/app-files-backend","const authorizeAttachment = createAppAttachmentAuthorizationHandler({authorizeUpload, authorizeRead});\n// 注册为本应用 authorize-attachment API 的 handler","本应用业务权限，应用负责校验记录与范围","employee-backend","read","回调 authorizeUpload(employee,{entityType,entityId},signal)；authorizeRead(employee,{entityType,entityId,attachmentId?},signal)","handler(input,employee,signal) → {organizationId}","清单声明 POST authorize-attachment；permission 与 businessPermission 相同。平台独立检查附件绑定，回调不能无条件放行。",{"apiId": "authorize-attachment"}),
  reference("prepareSandboxImage","图片压缩与规范化","图片与留证","@metro/platform-sdk/app-files","const jpegBytes = await prepareSandboxImage(file);","无需服务授权","local","read","用户选择 JPEG/PNG/WebP File","Uint8Array（JPEG）","原图≤8MiB，最长边≤1400px，输出≤220000字节；透明背景转白色，不保存原图。超限拒绝。",{"extensions": [".jpg", ".jpeg", ".png", ".webp"]}),
  reference("createSandboxImageClient.upload","图片上传（压缩／分块）","图片与留证","@metro/platform-sdk/app-files","const images = createSandboxImageClient(invoke, {begin: \"photo-begin\", part: \"photo-part\", finish: \"photo-finish\", read: \"photo-read\"});\nconst photoId = await images.upload(file, {organizationId, kind: \"evidence\"});\n// 已压缩 JPEG 可调用 images.uploadPrepared(bytes, input)","本应用图片 API 业务权限；后端 platform.app_data.read/write","sandbox","write","invoke: 应用 API 适配器；operations: 应用自定义 API ID；file；organizationId: UUID；kind: 标识","photoId: UUID","invoke 须解包业务成功结果、失败抛错。每块11000字节，最多20块；通过应用后端托管表存放；不自动重试，不是公共图片直链仓库。",{"organizationId": "00000000-0000-4000-8000-000000000001", "kind": "evidence"}),
  reference("createSandboxImageClient.read","图片读取与完整性校验","图片与留证","@metro/platform-sdk/app-files","const blob = await images.read({recordId, photoId});\nconst url = URL.createObjectURL(blob);\n// 预览结束后 URL.revokeObjectURL(url)","本应用图片读取权限与记录可见范围","sandbox","read","recordId、photoId: UUID","Blob（image/jpeg）","逐块读取并核对大小、分块数和 SHA-256；须先关联业务记录。预览使用 Blob URL，不泄露存储位置。",{"recordId": "00000000-0000-4000-8000-000000000001", "photoId": "00000000-0000-4000-8000-000000000001"}),
  reference("createAppImageMigrationOperations","图片存储表结构","图片与留证","@metro/platform-sdk/app-files-backend","const operations = createAppImageMigrationOperations();\n// 合并到本应用声明式迁移 operations","storage.mode: managed","build","ui","无参数","创建 photos、photo_parts 和索引的迁移操作数组","只生成迁移声明；由应用安装流程执行。表名固定，应用需检查已有迁移冲突。",{}),
  reference("createManagedAppImageStore","图片后端存储与业务关联","图片与留证","@metro/platform-sdk/app-files-backend","const images = createManagedAppImageStore(gateway, {authorizeWrite, resolveRead});\n// 将 begin/part/finish/read 注册到本应用 API\nconst photo = await images.requireReady(photoId, kind, employee, organizationId, recordId);\nawait data.transaction(requestId, [...recordMutations, images.link(photo, recordId)]);","platform.app_data.read/write + 应用业务范围","employee-backend","write","authorizeWrite(employee,organizationId,signal)；resolveRead(employee,recordId,photoId,signal) → {organizationId}","begin/part/finish/read/requireReady/link 方法集合","requireReady 核对上传者、组织、类型和关联状态；link 返回写入操作，须和业务记录同事务提交。不是通用对象存储，不保留原图。",{"kind": "evidence"}),
  reference("parseExcelFile","Excel 导入解析（首个工作表）","表格解析与生成","@metro/platform-sdk/app-spreadsheets","const rows = await parseExcelFile(file);","无需服务授权；业务导入另行授权","local","read","File|Blob|ArrayBuffer（Excel 工作簿）","T[]（首个工作表，首行作为字段名）","解析在本地执行，不自动上传或写入业务记录。先用 readSandboxFile 限制文件体积，再预览、校验列和行数、确认导入；不是 Word/PDF 解析器。",{"file": "用户选择的 .xlsx/.xls"}),
  reference("parseExcelWorkbook","Excel 多工作表解析与预览数据","表格解析与生成","@metro/platform-sdk/app-spreadsheets","const workbook = await parseExcelWorkbook(file, file.name);","无需服务授权","local","read","File|Blob|ArrayBuffer；fileName?: string","{fileName,sheetNames,sheets:{[name]:{name,data,jsonData,headers,rowCount,colCount}}}","返回网格和 JSON 数据，预览 UI 由应用选择；解析器不执行宏或公式计算。请控制文件、行列数及浏览器内存。",{"fileName": "records.xlsx"}),
  reference("jsonToExcelBlob","生成 Excel 文件","表格解析与生成","@metro/platform-sdk/app-spreadsheets","const blob = jsonToExcelBlob({data: rows, sheetName: \"记录\", columns: [{key: \"title\", header: \"标题\", width: 24}]});\ndownloadSandboxFile(\"records.xlsx\", blob, blob.type);","生成无需服务授权；下载需 ui.downloads: true","local","read","{data: 对象数组,sheetName?,columns?:[{key,header,width?,formatter?}]}","Blob（标准 .xlsx）","只生成文件，不上传存储；formatter 是应用代码中的函数，不能放入 JSON 请求。生成前控制行数、列数和内容。",{"data": [{"title": "示例记录"}], "sheetName": "记录", "columns": [{"key": "title", "header": "标题", "width": 24}]}),
  reference("exportToExcel","生成并下载 Excel","表格解析与生成","@metro/platform-sdk/app-spreadsheets","exportToExcel({data: rows, filename: \"records.xlsx\", sheetName: \"记录\"});","清单 ui.downloads: true","local","ui","与 jsonToExcelBlob 相同，另支持 filename?: string","void（生成并触发下载）","默认 export.xlsx，自动补 .xlsx 后缀；复用 downloadSandboxFile 文件名与50MiB限制。",{"data": [{"title": "示例记录"}], "filename": "records.xlsx"}),
  reference("QueryList / FilterBar","L2 筛选查找与列表组合","共享 UI","@metro/platform-sdk/ui","<QueryList query={{searchValue, onSearchChange, showDateRange: false, filterGroups, activeFilters, onApplyFilters, moreActions}}>{tableContent}</QueryList>","无需额外服务授权；数据权限由业务处理","local","ui","受控搜索、筛选组、确认/重置回调、功能菜单；列表子节点","React 组件","搜索默认收起；FilterBar 可独立配合卡片目录使用。共享 UI 还提供表格、分页、表单、人员/组织选择、日期时间、弹窗和签字板；CSS 从 ui-styles 导入。",{"showDateRange": false}),
];
export const APP_INTEGRATION_ERRORS=[
  {code:'ACCESS_DENIED',description:'核对平台服务授权和资源范围；不能用管理员身份代替员工。'},
  {code:'INVALID_PARAMS',description:'参数不符合契约；修正请求后由用户重新发起。'},
  {code:'AI_NOT_CONFIGURED',description:'当前实例尚未配置 AI，联系平台管理员。'},
  {code:'APP_CAPABILITY_NOT_PUBLISHED',description:'提供方接口未开放或开放已失效。'},
  {code:'TARGET_APP_ACCESS_DENIED',description:'员工缺少目标应用准入、角色权限或数据范围。'},
  {code:'TIMEOUT / TRANSPORT_FAILED',description:'读取可由用户重试；写入结果 unknown 时先查记录或人工核对，禁止自动重放。'},
] as const;

/** Every published entrypoint, including compatibility-only metadata. */
export const PLATFORM_SDK_MODULES = [
 {path:'.',description:'兼容基础入口：能力元数据、事件与资源引用，不是运行接口目录。'},
 {path:'./capabilities',description:'兼容能力元数据含内部模块路径；应用不能导入内部源码或据此推断可调用能力。'},
 {path:'./events',description:'事件契约类型与声明状态，不代表已有应用订阅/发布通道。'},
 {path:'./references',description:'人员、组织、位置等资源引用类型，不执行查询。'},
 {path:'./app-manifest',description:'清单、权限、路由、存储迁移和安装产物类型。'},
 {path:'./app-gateway',description:'后端通道、托管数据、签字、通知、AI、机器人、应用互通客户端。'},
 {path:'./app-directory',description:'人员、组织上下文、位置、车站、设备的类型与查询客户端。'},
 {path:'./app-sandbox',description:'沙箱握手、宿主交互、路由事件、本应用 API 和附件二进制通道。'},
 {path:'./app-backend',description:'隔离后端运行时、传输、可信 employee 上下文与 allowsAppResource 资源校验。'},
 {path:'./app-files',description:'本地文件读取和下载、原件附件、图片压缩与分块传输。'},
 {path:'./app-files-backend',description:'附件业务授权、照片迁移和存储处理器。'},
 {path:'./app-spreadsheets',description:'Excel 首表/工作簿解析、生成 Blob 和下载，与平台共用实现。'},
 {path:'./ui',description:'L2 筛选查找、列表分页、表单选择、弹窗和签字板；props 见类型与界面指南。'},
 {path:'./ui-styles',description:'platformUiCss，共享样式，使用宿主 nonce 注入并遵循主题。'},
 {path:'./app-test-kit',description:'createAppTestHost 本地模拟操作、请求记录与 drain，不替代真实授权验收。'},
 {path:'./app-contracts',description:'版本能力参考数据，不是实例配置或运行授权状态。'},
 {path:'./app-api-documentation',description:'有界输入输出结构、示例校验；不替代 handler 输入及权限检查。'},
] as const;
