import {build} from 'esbuild';
import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('.',import.meta.url)),out=root+'dist/';await mkdir(out,{recursive:true});
for(const [entry,file,platform,format] of [['entry.mjs','entry.cjs','node','cjs'],['ui.jsx','ui.js','browser','iife']]){
 const result=await build({entryPoints:[root+entry],outfile:out+file,bundle:true,platform,format,target:platform==='node'?'node22':'es2022',metafile:true,minify:true,define:{'process.env.NODE_ENV':'"production"'}});
 if(Object.keys(result.metafile.inputs).some(p=>p.includes('server/')||p.includes('src/app-platform/')))throw Error('PLATFORM_INTERNAL_IMPORT');
}
await copyFile(root+'migration-001.json',out+'migration-001.json');
const artifacts=[];for(const [id,kind,path] of [['backend','backend','entry.cjs'],['frontend','frontend','ui.js'],['schema','migration','migration-001.json']]){const bytes=await readFile(out+path);artifacts.push({id,kind,path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}
const pkg=JSON.parse(await readFile(root+'package.json','utf8'));
const permissions=[['read','查看台账',['self','workgroup','department','organizations','all']],['submit','填写台账',['workgroup','department','organizations','all']],['config','应用设置',['workgroup','department','organizations','all']],['sign','本人签署',['self']]].map(([name,description,scopeKinds])=>({code:'app.shifts.'+name,description,scopeKinds}));
const pages=[['handover','/','交接班','submit'],['handover-records','/handover-records','交接班记录','read'],['meeting','/meeting','晨会','submit'],['meeting-records','/meeting-records','晨会记录','read'],['settings','/settings','设置','config']];
const apis=['save-draft','load-draft','session','members','previous','template','bootstrap','settings','configure','test-webhook','list','detail','signature-image','save','sign'];
const manifest={manifestVersion:'1.0',id:'shifts',version:pkg.version,name:'晨会交接',icon:JSON.parse(await readFile(root+'icon.json','utf8')),description:'交接班台账、晨会记录与本人签署',publisherId:'metro-apps',compatibility:{platform:{minInclusive:'0.10.6',maxExclusive:'2.0.0'},capabilities:[],applications:[]},permissions:{requested:['platform.app_data.read','platform.app_data.write','platform.people.read','platform.notifications.create','platform.signatures.create','platform.signatures.read','platform.signatures.sign'],defined:permissions},ui:{mode:'sandbox',entryArtifactId:'frontend',clientRouting:true},backend:{mode:'isolated',runtime:'node',entryArtifactId:'backend',limits:{memoryMiB:128,cpuMillis:500,timeoutSeconds:30}},health:{path:'/health',timeoutSeconds:1},storage:{mode:'managed',migrations:[{id:'initial',artifactId:'schema'}]},routes:pages.map(([id,path,_label,p])=>({id,path,permission:'app.shifts.'+p})),navigation:pages.map(([id,_path,label],order)=>({id,routeId:id,label,order})),api:apis.map(id=>({id,method:'POST',path:`/${id}`,handler:id,permission:'app.shifts.'+({settings:'config',configure:'config','test-webhook':'config',save:'submit','save-draft':'submit','load-draft':'submit',template:'submit',bootstrap:'submit',sign:'sign'}[id]??'read'),...(['session','members','detail','signature-image','previous'].includes(id)?{businessEntry:true}:{businessPermission:'app.shifts.'+({settings:'config',configure:'config','test-webhook':'config',save:'submit','save-draft':'submit','load-draft':'submit',template:'submit',bootstrap:'submit',sign:'sign'}[id]??'read')})})),events:{publish:[],subscribe:[]},jobs:[],tools:[],resources:[],network:{frontendOrigins:[],backendOrigins:[]},artifacts};
await writeFile(out+'manifest.json',JSON.stringify(manifest,null,2)+'\n');
