import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createShiftsHandlers} from './handlers.mjs';
import {defaults} from './modules.mjs';
const org='61000000-0000-4000-8000-000000000001',other='61000000-0000-4000-8000-000000000002',person='61000000-0000-4000-8000-000000000003',second='61000000-0000-4000-8000-000000000004';
function fixture(){
 const tables={records:new Map(),configs:new Map(),drafts:new Map()},calls=[];let failPush=false;
 const employee={personId:person,organizationUnitId:org,businessAuthorization:{revision:randomUUID(),organizations:[{id:org,name:'测试工班'}],grants:['read','submit','config','sign'].map(p=>({permission:'app.shifts.'+p,self:p==='sign',all:p==='config',organizationIds:p==='sign'?[]:[org]}))}};
 const gateway={async invoke(op,p){calls.push({op,p});if(op==='platform.app_data.get')return {row:structuredClone(tables[p.table].get(p.id)??null)};
  if(op==='platform.app_data.transaction'){for(const m of p.operations){const current=tables[m.table].get(m.id);if(m.action==='insert'&&current||m.expected&&Object.entries(m.expected).some(([k,v])=>current?.[k]!==v))throw Error('STORAGE_CONFLICT');}for(const m of p.operations)tables[m.table].set(m.id,{id:m.id,...m.values});return {results:p.operations.map(m=>({row:tables[m.table].get(m.id)}))};}
  if(op==='platform.app_data.list'){const match=(r,f)=>f.contains?f.contains.every(w=>r[f.column].some(v=>Object.entries(w).every(([k,x])=>v[k]===x))):r[f.column]===f.value;let rows=[...tables[p.table].values()].filter(r=>(p.filters??[]).every(f=>match(r,f))&&(!p.anyOf||p.anyOf.some(g=>g.every(f=>match(r,f)))));if(p.search)rows=rows.filter(r=>String(r[p.search.column]).toLowerCase().includes(p.search.text.toLowerCase()));if(p.range)rows=rows.filter(r=>(!p.range.from||r[p.range.column]>=p.range.from)&&(!p.range.to||r[p.range.column]<=p.range.to));return {rows:rows.slice(0,p.pageSize??20),nextCursor:null};}
  if(op==='platform.people.organization_context')return {organizations:[{id:p.organizationUnitId,name:'工班',unitType:'workgroup'}]};
  if(op==='platform.people.members')return {rows:[person,second].filter(id=>!p.personId||p.personId===id).filter(id=>!p.personIds||p.personIds.includes(id)).map(id=>({id,name:id===person?'甲':'乙',organizationUnitId:org}))};
  if(op==='platform.signatures.associate')return {associated:true,signers:p.personIds.map(personId=>({personId,status:'unsigned'}))};
  if(op==='platform.signatures.get')return {associated:true,signers:[]};
  if(op==='platform.signatures.sign')return {associated:true,signers:[{personId:person,status:'signed'}]};
  if(op==='platform.webhook.send'){if(failPush)throw Error('WEBHOOK_TIMEOUT');return {sent:true};}
  throw Error('unexpected '+op);
 }};
 const handlers=createShiftsHandlers(gateway);const call=(name,p,e=employee)=>handlers.get(name).execute(p,new AbortController().signal,e);
 const form=(kind='meeting')=>({kind,id:randomUUID(),requestId:randomUUID(),organizationId:org,date:'2026-09-20',time:'08:30',shiftType:'night',hostId:person,participantIds:[second],handoverIds:[],takeoverIds:[person],form:{}});
 return {call,form,employee,tables,calls,setFailPush:()=>{failPush=true;}};
}
test('same day meetings and same shift handovers remain independent; repeated intent saves once',async()=>{const h=fixture();for(const kind of ['meeting','handover'])for(let i=0;i<2;i++){const p=h.form(kind);assert.equal((await h.call('save',p)).ok,true);assert.equal((await h.call('save',p)).ok,true);}assert.equal(h.tables.records.size,4);assert.equal(h.calls.filter(c=>c.op==='platform.app_data.transaction').length,4);});
test('scope is applied before pagination and cross-organization detail and writes are denied',async()=>{const h=fixture();const p=h.form();assert.equal((await h.call('save',{...p,organizationId:other})).error.code,'ACCESS_DENIED');h.tables.records.set(p.id,{id:p.id,kind:'meeting',organization_id:other,created_by:second,people:[]});assert.equal((await h.call('detail',{id:p.id})).error.code,'ACCESS_DENIED');const page=await h.call('list',{kind:'meeting'});assert.deepEqual(page.result.rows,[]);assert.ok(h.calls.find(c=>c.op==='platform.app_data.list').p.anyOf);});
test('global template inherits, local override changes only local future snapshots, disabled webhook stops fallback',async()=>{const h=fixture();const global=structuredClone(defaults.meeting);global[0].label='全局学习';assert.equal((await h.call('configure',{organizationId:null,type:'meeting',value:{mode:'override',modules:global},revision:0,requestId:randomUUID()})).ok,true);assert.equal((await h.call('template',{kind:'meeting',organizationId:org})).result.modules[0].label,'全局学习');const p=h.form();await h.call('save',p);global[0].label='本班学习';await h.call('configure',{organizationId:org,type:'meeting',value:{mode:'override',modules:global},revision:0,requestId:randomUUID()});assert.equal(h.tables.records.get(p.id).module_snapshot[0].label,'全局学习');const webhook={mode:'override',url:'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=example',meeting:true,handover:true};await h.call('configure',{organizationId:null,type:'webhook',value:webhook,revision:0,requestId:randomUUID()});await h.call('configure',{organizationId:org,type:'webhook',value:{...webhook,mode:'disabled'},revision:0,requestId:randomUUID()});const result=await h.call('save',h.form());assert.equal(result.result.notification,'disabled');assert.equal(h.calls.some(c=>c.op==='platform.webhook.send'),false);const settings=await h.call('settings',{organizationId:org});assert.equal('url' in settings.result.webhook.value,false);});
test('saved meeting survives notification failure and is available to sign later as current employee',async()=>{const h=fixture();await h.call('configure',{organizationId:org,type:'webhook',value:{mode:'override',url:'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=test',meeting:true},revision:0,requestId:randomUUID()});h.setFailPush();const p=h.form();const saved=await h.call('save',p);assert.equal(saved.ok,true);assert.equal(saved.result.notification,'unconfirmed');assert.ok(h.tables.records.has(p.id));assert.equal((await h.call('sign',{id:p.id,image:'data:image/png;base64,test'})).ok,true);assert.equal((await h.call('sign',{id:p.id,image:'x',personId:second})).error.code,'INVALID_INPUT');const outsider={...h.employee,personId:randomUUID()};assert.equal((await h.call('sign',{id:p.id,image:'x'},outsider)).error.code,'ACCESS_DENIED');});
test('concurrent settings revisions and malformed dates fail before writes',async()=>{const h=fixture();const p={organizationId:org,type:'meeting',value:{mode:'override',modules:defaults.meeting},revision:0,requestId:randomUUID()};assert.equal((await h.call('configure',p)).ok,true);assert.equal((await h.call('configure',{...p,requestId:randomUUID()})).error.code,'CONFLICT');assert.equal((await h.call('save',{...h.form(),date:'2026-99-90'})).error.code,'INVALID_INPUT');});
test('self read includes meetings attended, but cannot edit another author or replay their intent',async()=>{const h=fixture(),p=h.form();await h.call('save',p);const employee={...h.employee,personId:second,businessAuthorization:{...h.employee.businessAuthorization,grants:[{permission:'app.shifts.read',self:true,all:false,organizationIds:[]}]}};assert.equal((await h.call('list',{kind:'meeting'},employee)).result.rows.length,1);assert.equal((await h.call('detail',{id:p.id},employee)).ok,true);const writer={...h.employee,personId:second,businessAuthorization:{...h.employee.businessAuthorization,grants:h.employee.businessAuthorization.grants.filter(g=>g.permission!=='app.shifts.config')}};assert.equal((await h.call('save',p,writer)).error.code,'ACCESS_DENIED');});
test('drafts are isolated by person and organization and use optimistic revisions',async()=>{const h=fixture(),value=h.form(),payload={organizationId:org,kind:'meeting',value,revision:0,requestId:randomUUID()};assert.equal((await h.call('save-draft',payload)).result.revision,1);assert.equal((await h.call('load-draft',{organizationId:org,kind:'meeting'})).result.draft.id,value.id);assert.equal((await h.call('load-draft',{organizationId:org,kind:'meeting'},{...h.employee,personId:second})).result.draft,null);assert.equal((await h.call('save-draft',{...payload,requestId:randomUUID()})).error.code,'CONFLICT');assert.equal((await h.call('save-draft',{...payload,revision:1,requestId:randomUUID()})).result.revision,2);});
test('meeting quiz and risk assignees must be attendees and snapshots preserve the form shown',async()=>{const h=fixture(),p=h.form();p.modules=structuredClone(defaults.meeting);p.modules[0].label='填写时的学习文件';p.form={quiz_record:[{personId:second,content:'设备故障怎么处置',status:'correct'}],safety_prediction:{'item-1':{checked:true,remark:'作业前确认',personIds:[second]}}};assert.equal((await h.call('save',p)).ok,true);assert.equal(h.tables.records.get(p.id).module_snapshot[0].label,'填写时的学习文件');const invalid=h.form();invalid.form={quiz_record:[{personId:randomUUID(),content:'问题',status:''}]};assert.equal((await h.call('save',invalid)).error.code,'INVALID_INPUT');});

test('form organization comes from login even with all-organization grants',async()=>{const h=fixture(),employee={...h.employee,businessAuthorization:{...h.employee.businessAuthorization,grants:h.employee.businessAuthorization.grants.map(g=>({...g,all:true}))}};for(const action of ['template','previous','members','load-draft'])assert.equal((await h.call(action,{kind:'meeting',organizationId:other},employee)).error.code,'ACCESS_DENIED');assert.equal((await h.call('save',{...h.form(),organizationId:other},employee)).error.code,'ACCESS_DENIED');const p=h.form();delete p.organizationId;assert.equal((await h.call('save',p,employee)).ok,true);assert.equal(h.tables.records.get(p.id).organization_id,org);});
test('record text search applies before pagination',async()=>{const h=fixture(),p=h.form();p.form={study_content:'施工安全'};await h.call('save',p);await h.call('save',h.form());assert.equal((await h.call('list',{kind:'meeting',search:'施工安全'})).result.rows.length,1);assert.equal((await h.call('list',{kind:'meeting',search:'不存在'})).result.rows.length,0);});
test('custom modules preserve per-line remarks and defaults; safety default remarks survive config',async()=>{const h=fixture(),modules=structuredClone(defaults.meeting);modules.push({id:'custom_list_test',label:'本班重点',type:'text',custom:true,enabled:true,enableRemarks:true,enableDefaultContent:true,defaultText:'检查票亭'});modules.find(m=>m.id==='safety_prediction').items[0].remark='检查防护用品';assert.equal((await h.call('configure',{organizationId:org,type:'meeting',value:{mode:'override',modules},revision:0,requestId:randomUUID()})).ok,true);const template=(await h.call('template',{kind:'meeting'})).result.modules;assert.equal(template.at(-1).enableRemarks,true);assert.equal(template.find(m=>m.id==='safety_prediction').items[0].remark,'检查防护用品');const p=h.form();p.modules=template;p.form={custom_list_test:[{text:'检查票亭',remark:'值班员确认'}]};assert.equal((await h.call('save',p)).ok,true);assert.deepEqual(h.tables.records.get(p.id).form_data.custom_list_test,[{text:'检查票亭',remark:'值班员确认'}]);});
test('workgroup settings grant loads default modules without global configuration',async()=>{
 const h=fixture();h.employee.businessAuthorization.grants=h.employee.businessAuthorization.grants.map(g=>({...g,all:false}));
 const result=await h.call('settings',{organizationId:org});
 assert.equal(result.ok,true);assert.deepEqual(result.result.handover.value.modules,defaults.handover);assert.deepEqual(result.result.meeting.value.modules,defaults.meeting);
 assert.equal((await h.call('settings',{organizationId:other})).error.code,'ACCESS_DENIED');
 assert.equal((await h.call('settings',{})).error.code,'ACCESS_DENIED');
 assert.equal(h.calls.filter(c=>c.op==='platform.people.organization_context').length,1);
});
test('concurrent form reads serialize storage access and release the queue after failure',async()=>{
 let active=0,maxActive=0,fail=true;
 const employee=fixture().employee;
 const handlers=createShiftsHandlers({async invoke(op){
  if(op==='platform.people.organization_context')return {organizations:[{id:org,unitType:'workgroup'}]};
  active++;maxActive=Math.max(maxActive,active);
  try{await new Promise(resolve=>setTimeout(resolve,5));if(fail){fail=false;throw Error('STORAGE_BUSY');}return op.endsWith('.get')?{row:null}:{rows:[],nextCursor:null};}finally{active--;}
 }});
 const call=name=>handlers.get(name).execute({kind:'meeting',organizationId:org},new AbortController().signal,employee);
 const [draft,template,previous]=await Promise.all([call('load-draft'),call('template'),call('previous')]);
 assert.equal(maxActive,1);assert.equal(draft.error.code,'READ_FAILED');assert.equal(draft.error.writeOutcome,'not_started');assert.deepEqual(template.result.modules,defaults.meeting);assert.equal(previous.ok,true);
});
