import React,{useEffect,useState} from 'react';
import {Button,Input,Select,Field} from '../../components/ui';
import {readThemePreference} from './theme';
const messages:Record<string,string>={REGISTRATION_CONFLICT:'此工号已有账号或待审核申请，或企业微信 UserID 已被使用。',REGISTRATION_CHALLENGE_FAILED:'滑块验证已失效，请重新验证。',REGISTRATION_ORGANIZATION_INACTIVE:'所属组织已停用，请重新选择。',REGISTRATION_INVALID_INPUT:'请检查必填项；密码至少 12 位且不超过 72 字节。',REGISTRATION_RATE_LIMIT:'提交过于频繁，请稍后再试。'};
async function request<T>(path:string,body?:unknown):Promise<T>{const r=await fetch('/api/auth/registration'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(messages[v.error]??'注册服务暂不可用，请稍后重试。');return v;}
export function Registration({onBack}:{onBack:()=>void}){
 const [form,setForm]=useState({employeeNo:'',name:'',phone:'',wecomUserId:'',password:'',organizationId:''});
 const [orgs,setOrgs]=useState<{id:string;name:string}[]>([]),[challenge,setChallenge]=useState<{id:string;target:number}|null>(null),[slider,setSlider]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 useEffect(()=>{let live=true;const t=setTimeout(()=>{request<{organizations:typeof orgs}>('/organizations').then(v=>{if(live)setOrgs(v.organizations);}).catch(e=>{if(live)setError(e.message);});},200);return()=>{live=false;clearTimeout(t);};},[]);
 async function reset(){setChallenge(null);setSlider(0);try{setChallenge(await request('/challenge',{}));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void reset();},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy||!challenge)return;setBusy(true);setError('');try{await request('',{...form,challengeId:challenge.id,slider});setForm(v=>({...v,password:''}));setDone(true);}catch(e){setError((e as Error).message);await reset();}finally{setBusy(false);}}
 return <main className="afc-admin afc-theme-neutral afc-admin-login" data-theme={readThemePreference()}><div className="afc-login-container afc-registration-container"><header><img src="/brand/afc-logo-green.svg" alt=""/><h1>运管开放平台</h1></header>{done?<><p role="status">注册申请已提交，等待平台管理员审核。通过后使用工号和密码登录。</p><Button fullWidth onClick={onBack}>返回登录</Button></>:<form className="afc-registration-form" aria-label="员工注册" onSubmit={submit}>{(['employeeNo','name','phone','wecomUserId','password'] as const).map(key=><Field key={key} htmlFor={'register-'+key} label={{employeeNo:'工号 *',name:'姓名 *',phone:'手机号',wecomUserId:'企业微信 UserID',password:'密码 *'}[key]}><Input id={'register-'+key} required={['employeeNo','name','password'].includes(key)} type={key==='password'?'password':key==='phone'?'tel':'text'} minLength={key==='password'?12:key==='employeeNo'?3:undefined} maxLength={key==='name'?100:key==='wecomUserId'?255:key==='password'?72:50} autoComplete={key==='password'?'new-password':key==='employeeNo'?'username':'off'} value={form[key]} onChange={e=>setForm(v=>({...v,[key]:e.target.value}))} disabled={busy} placeholder={key==='password'?'至少 12 位':undefined}/></Field>)}<Field htmlFor="register-org" label="所属组织 *"><Select id="register-org" value={form.organizationId} onChange={e=>setForm(v=>({...v,organizationId:e.target.value}))} required disabled={busy}><option value="">请选择所属组织</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field><Field htmlFor="register-slider" label={challenge?`拖动滑块至 ${challenge.target} 验证`:'正在加载滑块…'}><input id="register-slider" type="range" min="0" max="100" value={slider} disabled={busy||!challenge} onChange={e=>setSlider(Number(e.target.value))} style={{width:'100%',accentColor:'var(--text-primary)'}}/><span>{slider}</span></Field>{error&&<p role="alert" className="afc-error afc-registration-wide">{error}</p>}<Button className="afc-registration-wide" type="submit" fullWidth disabled={busy||!challenge||Math.abs(slider-challenge.target)>2}>{busy?'提交中…':'提交注册申请'}</Button><Button className="afc-registration-wide" variant="ghost" fullWidth onClick={onBack} disabled={busy}>返回登录</Button></form>}</div></main>;
}
