import React,{useEffect,useState} from 'react';
import {Button,Input,OrganizationPicker,type OrganizationOption,Field} from '../../components/ui';
import {readThemePreference} from './theme';
const messages:Record<string,string>={REGISTRATION_CONFLICT:'此工号已有账号或待审核申请，或企业微信 UserID 已被使用。',REGISTRATION_ORGANIZATION_INACTIVE:'所属组织已停用，请重新选择。',REGISTRATION_INVALID_INPUT:'请检查必填项；密码至少 12 位且不超过 72 字节。',REGISTRATION_RATE_LIMIT:'提交过于频繁，请稍后再试。'};
async function request<T>(path:string,body?:unknown):Promise<T>{const r=await fetch('/api/auth/registration'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(messages[v.error]??'注册服务暂不可用，请稍后重试。');return v;}
export function Registration({onBack}:{onBack:()=>void}){
 const [form,setForm]=useState({employeeNo:'',name:'',phone:'',wecomUserId:'',password:'',organizationId:''});
 const [orgs,setOrgs]=useState<OrganizationOption[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 useEffect(()=>{let live=true;async function load(){try{const all:OrganizationOption[]=[];let after='';while(live){const v=await request<{organizations:OrganizationOption[]}>('/organizations'+(after?'?after='+encodeURIComponent(after):''));all.push(...v.organizations);if(v.organizations.length<100)break;const next=v.organizations.at(-1)!.id;if(next===after)throw Error('组织列表读取失败');after=next;}if(live)setOrgs(all);}catch(e){if(live)setError((e as Error).message);}}void load();return()=>{live=false;};},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await request('',form);setForm(v=>({...v,password:''}));setDone(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="afc-admin afc-theme-neutral afc-admin-login" data-theme={readThemePreference()}><div className="afc-login-container afc-registration-container"><header><img src="/brand/afc-logo-green.svg" alt=""/><h1>运管开放平台</h1></header>{done?<><p role="status">注册申请已提交，等待平台管理员审核。通过后使用工号和密码登录。</p><button type="button" className="afc-auth-text-link" onClick={onBack}>返回登录</button></>:<form className="afc-registration-form" aria-label="员工注册" onSubmit={submit}>{(['employeeNo','name','phone','wecomUserId','password'] as const).map(key=><Field key={key} htmlFor={'register-'+key} label={{employeeNo:'工号 *',name:'姓名 *',phone:'手机号',wecomUserId:'企业微信 UserID',password:'密码 *'}[key]}><Input id={'register-'+key} required={['employeeNo','name','password'].includes(key)} type={key==='password'?'password':key==='phone'?'tel':'text'} minLength={key==='password'?12:key==='employeeNo'?3:undefined} maxLength={key==='name'?100:key==='wecomUserId'?255:key==='password'?72:50} autoComplete={key==='password'?'new-password':key==='employeeNo'?'username':'off'} value={form[key]} onChange={e=>setForm(v=>({...v,[key]:e.target.value}))} disabled={busy} placeholder={key==='password'?'至少 12 位':undefined}/></Field>)}<Field htmlFor="register-org" label="所属组织 *"><OrganizationPicker id="register-org" options={orgs} value={form.organizationId} onChange={organizationId=>setForm(v=>({...v,organizationId}))} required disabled={busy}/></Field>{error&&<p role="alert" className="afc-error afc-registration-wide">{error}</p>}<Button className="afc-registration-wide" type="submit" fullWidth disabled={busy}>{busy?'提交中…':'提交注册申请'}</Button><button type="button" className="afc-auth-text-link" onClick={onBack} disabled={busy}>返回登录</button></form>}</div></main>;
}
